/**
 * Mini Card Battle - Card Master Data
 */
export const CARD_MASTER = [
  {
    id: 'golem',
    name: '大理石のゴーレム',
    rarity: 1,
    power: 5,
    skill: 'none',
    voiceCategory: 'stone',
    flavor:
      '魔法によって生命を吹き込まれた大理石の彫像。美しさと硬固さを兼ね備えている。',
  },
  {
    id: 'clone',
    name: '鏡の戦士',
    rarity: 1,
    power: 2,
    skill: 'clone',
    skillValue: 1,
    voiceCategory: 'sword',
    flavor:
      '妖精の鏡から這い出した実体のない騎士。本体と寸分違わぬ動きで幻惑する。',
  },
  {
    id: 'sniper',
    name: '森の射手',
    rarity: 1,
    power: 2,
    skill: 'snipe',
    skillValue: 4,
    voiceCategory: 'human_male_ikemen',
    flavor:
      '静寂に包まれた深い森を守るエルフの狩人。その矢は木の葉の間を縫い、目標を違わず射抜く。',
  },
  {
    id: 'cleric',
    name: '見習い修道女',
    rarity: 1,
    power: 3,
    skill: 'heal',
    skillValue: 3,
    voiceCategory: 'human_female_cute',
    flavor:
      '救済を志し修業に励む乙女。未熟ながらもその祈りは傷ついた心を癒やす。',
  },
  {
    id: 'diviner',
    name: '星詠みの占術士',
    rarity: 1,
    power: 4,
    skill: 'draw',
    skillValue: 2,
    voiceCategory: 'human_female_cool',
    flavor: '天球の運行を読み解き、運命の糸を紡ぎ直す導き手。',
  },
  {
    id: 'dinosaur',
    name: '古代の大蜥蜴',
    rarity: 1,
    power: 8,
    skill: 'takeover',
    voiceCategory: 'lizard',
    flavor:
      '古代の息吹を宿す巨大な爬虫類。その巨体を現すには、相応の代償が必要となる。',
  },
  {
    id: 'cheetah',
    name: '稲妻の猟豹',
    rarity: 1,
    power: 3,
    skill: 'quick',
    voiceCategory: 'beast',
    flavor: '稲妻を纏って戦場を駆ける最速の野獣。その爪が空気を切り裂く。',
  },
  {
    id: 'scorpion',
    name: '黒サソリ',
    rarity: 1,
    power: 3,
    skill: 'deadly',
    voiceCategory: 'insect',
    flavor:
      '夜の砂漠に潜む漆黒の巨蠍。その尾から放たれる猛毒は対象を一瞬で絶命させる。',
  },
  {
    id: 'mercenary',
    name: '傭兵',
    rarity: 1,
    power: 6,
    skill: 'convert',
    skillValue: 1,
    voiceCategory: 'human_male_warrior',
    flavor: '命が安い戦場において、彼が信じるのは己の腕と報酬だけである。',
  },
  {
    id: 'wall',
    name: '城壁',
    rarity: 1,
    power: 10,
    skill: 'defender',
    voiceCategory: 'stone',
    flavor:
      '幾多の戦火を耐え抜いた鉄壁の防塁。王国の平和を守り続ける沈黙の守護者。',
  },
  {
    id: 'leech',
    name: '巨大ヒル',
    rarity: 1,
    power: 4,
    skill: 'absorb',
    voiceCategory: 'snake',
    flavor:
      '湿った泥濘に潜む貪欲なる顎。犠牲者の血肉をすする不快な音だけが響き渡る。',
  },
  {
    id: 'fighter',
    name: 'アリーナの新入り',
    rarity: 1,
    power: 4,
    skills: [{ id: 'growth', value: 1 }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '観衆の喧騒に胸を高鳴らせる、未完の闘士。無骨なセスタスには、頂点を目指す熱意と、己の拳のみで道を切り拓く覚悟が宿っている。',
  },
  {
    id: 'falcon',
    name: '急襲する隼',
    rarity: 1,
    power: 3,
    skill: 'spread',
    skillValue: 1,
    voiceCategory: 'bird',
    flavor:
      '翼から硬い羽根を矢のように降らせた後、空から急降下して獲物を捉える。',
  },
  {
    id: 'spider',
    name: 'スパイダー',
    rarity: 1,
    power: 4,
    skill: 'bind',
    skillValue: 1,
    voiceCategory: 'insect',
    flavor:
      '暗闇に潜み、粘着質の糸を紡ぐ巨大な蜘蛛。獲物の自由を奪い、死の抱擁へと誘う。',
  },
  {
    id: 'airship',
    name: 'セレスタリアのサルベージ船',
    rarity: 1,
    power: 4,
    skill: 'salvage',
    skillValue: 1,
    voiceCategory: 'machine_old',
    flavor:
      '空飛ぶ巨大な飛行船。その甲板には、忘れ去られた過去の遺物が山のように積まれている。',
  },
  {
    id: 'skeleton',
    name: 'スケルトン',
    rarity: 1,
    power: 2,
    skill: 'split',
    skillValue: 3,
    summonId: 'token_skeleton',
    voiceCategory: 'undead',
    flavor:
      '骨と骨が組み合わさった古の戦士。一度倒してもバラバラのパーツを再構築して復活する。',
  },
  // {
  //   id: 'warden',
  //   name: '監獄長',
  //   rarity: 1,
  //   power: 6,
  //   skills: [{ id: 'takeover' }, { id: 'bind', value: 2 }],
  //   voiceCategory: 'human_male_warrior',
  //   flavor: '罪人を決して逃さぬ鉄壁の番人。',
  // },
  {
    id: 'titan',
    name: '旧式タイタン',
    rarity: 1,
    power: 8,
    skill: 'growth',
    skillValue: -2,
    voiceCategory: 'machine_old',
    flavor:
      '古代文明の造兵兵器。旧式ながらもその重厚な装甲は今なお健在である。',
  },
  {
    id: 'mantis',
    name: '旧式マンティス',
    rarity: 1,
    power: 4,
    skills: [{ id: 'quick' }, { id: 'growth', value: -2 }],
    voiceCategory: 'machine_old',
    flavor:
      '旧式の巨大なカマキリのロボット。鋭い鎌で獲物を伏せるが、過負荷による出力低下が激しい。',
  },
  {
    id: 'armsuits',
    name: '強化外骨格',
    rarity: 1,
    power: 2,
    skills: [{ id: 'equip' }, { id: 'sturdy' }],
    voiceCategory: 'machine_new',
    flavor:
      '強固な鋼鉄の装甲を纏った者は、戦場において難攻不落の城塞と化す。例え操縦者が倒れようとも、内蔵されたAIが稼働を続け、その任務を全うするだろう。',
  },
  {
    id: 'dancer',
    name: '魅惑の踊り子',
    rarity: 1,
    power: 2,
    skills: [{ id: 'bind', value: 1 }, { id: 'deadly' }],
    voiceCategory: 'human_female_sexy',
    flavor:
      '華麗な舞に目を奪われた瞬間、短剣が喉元に届く。彼女の微笑みは、甘美な死への誘いである。',
  },
  {
    id: 'drifter',
    name: 'アッシュランドの放浪者',
    rarity: 1,
    power: 4,
    skill: 'double_strike',
    voiceCategory: 'human_male_ikemen',
    flavor:
      '灼熱の砂塵を切り裂く双剣。彼の歩みの後には、切り刻まれた絶望のみが残る。',
  },
  {
    id: 'lizardman',
    name: '竜人族の斥候',
    rarity: 1,
    power: 4,
    skill: 'reinforce',
    skillValue: 2,
    voiceCategory: 'lizard',
    flavor:
      '湿地に潜み、獲物をつけ狙う追跡者。仲間を呼ぶその甲高い鳴き声は、無数の影が迫る前兆である。',
  },
  {
    id: 'commander',
    name: '前線の司令官',
    rarity: 1,
    power: 3,
    skill: 'support',
    skillValue: 2,
    voiceCategory: 'human_male_warrior',
    flavor:
      '最前線で兵を鼓舞し続ける老将。彼の掲げる軍旗は兵士たちの士気を極限まで高める。',
  },
  {
    id: 'lightpaladin',
    name: '光の聖騎士',
    rarity: 1,
    power: 5,
    skill: 'guardian',
    voiceCategory: 'human_male_ikemen',
    flavor:
      '「我が盾は、共に戦う友のためにある。」気高き精神を宿した聖なる騎士。',
  },
  {
    id: 'crenellatedwall',
    name: '民兵団の射手',
    rarity: 1,
    power: 8,
    skills: [{ id: 'spread', value: 1 }, { id: 'defender' }],
    voiceCategory: 'human_male_normal',
    flavor:
      '故郷を守るために立ち上がった志願兵たち。門の内側から放たれる矢は、侵略者を決して逃さない。',
  },
  {
    id: 'jellyfish',
    name: '発光するクラゲ',
    rarity: 1,
    power: 3,
    skill: 'bless',
    skillValue: 1,
    voiceCategory: 'monster',
    flavor: '深き暗闇の中で妖しく輝き、触れる者に不思議な活力を与える。',
  },
  {
    id: 'tortoise',
    name: '鉄亀',
    rarity: 1,
    power: 3,
    skill: 'sturdy',
    voiceCategory: 'insect',
    flavor:
      '鉱石を食べて成長し、鋼鉄の如き硬度を得た霊亀。物理的な衝撃をほぼ無効化する。',
  },
  {
    id: 'copy',
    name: '虚無の目覚め',
    rarity: 1,
    power: 4,
    skill: 'morph',
    skillValue: 1,
    voiceCategory: 'monster',
    flavor:
      'その巨大な眼差しに見つめられた時、存在の意味は虚空へと霧散し、ただ静寂のみが残される。',
  },
  {
    id: 'charger',
    name: '虹ハチドリ',
    rarity: 1,
    power: 2,
    skill: 'charge',
    skillValue: 1,
    voiceCategory: 'bird',
    flavor: '七色の翼を持つ小さな鳥。その羽ばたきは見る者に活力を与える。',
  },
  {
    id: 'bird',
    name: '新緑の導き鳥',
    rarity: 1,
    power: 1,
    skill: 'split',
    skillValue: 5,
    summonId: 'token_ent',
    voiceCategory: 'bird',
    flavor: 'その小さなさえずりが途絶えたとき、森の静寂は怒号へと変わる。',
  },
  {
    id: 'chameleon',
    name: '迷彩カメレオン',
    rarity: 1,
    power: 4,
    skill: 'immune',
    voiceCategory: 'lizard',
    flavor:
      '周囲の景色に完璧に溶け込む擬態能力。じっと潜んだその姿は、どんな熟練の狩人にも見抜くことはできない。',
  },
  {
    id: 'carpenter',
    name: '熟練の石大工',
    rarity: 1,
    power: 2,
    skills: [{ id: 'wall_create', value: 5 }],
    voiceCategory: 'human_male_old',
    flavor:
      '数十年、岩石と向き合い続けてきた職人。彼が積み上げた石壁は、いかなる軍勢の猛攻をも平然と受け流す。',
  },
  {
    id: 'incinerator',
    name: 'インシネレーター',
    rarity: 1,
    power: 4,
    skill: 'artillery',
    skillValue: 1,
    voiceCategory: 'human_female_cool',
    flavor:
      '異端の書物、教義に背く者を炎で浄化する実働部隊。マスク越しの彼女の瞳に、慈悲の色はない。',
  },
  {
    id: 'pray',
    name: '救済の祈り',
    rarity: 1,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'wall_create', value: 10 },
      { id: 'heal', value: 5 },
    ],
    voiceCategory: 'magic',
    flavor:
      '神聖なる祈りは時に癒しとなり、時に強固な守りとなって信徒を庇護する。',
  },
  {
    id: 'prisoner',
    name: '鉄面の監獄破り',
    rarity: 1,
    power: 6,
    skill: 'loss',
    skillValue: 2,
    voiceCategory: 'human_male_warrior',
    flavor:
      '重い枷を断ち切り、自由と引き換えに己の記憶を打ち捨てた。鉄面の下で獣のように吼え、正気をすり減らしながら、ただ破壊の衝動に従い暴れ狂う。',
  },
  {
    id: 'necromancer',
    name: 'ヴィス・ガルドの背教者',
    rarity: 1,
    power: 1,
    skill: 'resurrect',
    skillValue: 4,
    voiceCategory: 'human_female_cool',
    flavor:
      '『さあ、起きなさい…永遠なる奉仕の時間が始まるわ』。真紅の瞳が見つめる先、死者は再び立ち上がる。',
  },
  {
    id: 'shade',
    name: '墓の亡霊',
    rarity: 1,
    power: 4,
    skill: 'soul_bind',
    skillValue: 2,
    voiceCategory: 'undead',
    flavor:
      '古い墓地に漂う無念の霧。生者の温もりを嫌い、その魂を冷たい死の淵へと引き摺り込む。',
  },
  {
    id: 'beginnermagic',
    name: '初級魔術',
    rarity: 1,
    power: 0,
    skill: 'choice',
    skillValue: 1,
    choices: [
      { id: 'summon', value: 5, summonId: 'token_golem' },
      { id: 'support', value: 3 },
    ],
    voiceCategory: 'magic',
    flavor: '大地に流れる脈動をマナへと変換する基礎的な魔術。',
  },
  {
    id: 'snake',
    name: '蛇の使い魔',
    rarity: 1,
    power: 3,
    skill: 'toxic',
    skillValue: 3,
    voiceCategory: 'snake',
    flavor: '魔法使いに使役される毒蛇。術者の命令に従い、獲物を毒牙にかける。',
  },
  {
    id: 'shapeshifter',
    name: '変身魔導士',
    rarity: 1,
    power: 4,
    skills: [{ id: 'awake', value: 5, summonId: 'token_golem' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '「魔術とは変化、変化とは可能性だ。」自らが生み出した泥人形の姿へと消えるその瞬間まで、男は熱心に可能性を説き続けた。',
  },
  {
    id: 'ogre',
    name: '鬼',
    rarity: 1,
    power: 7,
    skill: 'brutal',
    skillValue: 2,
    voiceCategory: 'giant',
    flavor:
      '血に飢えた咆哮とともに、巨大な金棒が振り下ろされる。理性を失ったその暴虐なる一撃は、周囲のすべてを無差別に粉砕する。',
  },
  {
    id: 'omyouji',
    name: '漆黒の除霊師',
    rarity: 1,
    power: 4,
    skill: 'seal',
    skillValue: 1,
    voiceCategory: 'human_female_cool',
    flavor:
      '闇を以て闇を制する異端の術士。彼女が札をきる時、悪霊は光ではなく、より深い漆黒の結界へと封じ込められる。',
  },
  {
    id: 'ninja',
    name: '忍者',
    rarity: 1,
    power: 4,
    skill: 'stealth',
    skillValue: 1,
    voiceCategory: 'human_male_normal',
    flavor:
      '影に潜み、音もなく標的に近づく工作員。その姿を捉えることは困難である。',
  },
  {
    id: 'treasurehunter',
    name: 'アッシュランドの冒険家',
    rarity: 1,
    power: 5,
    skill: 'cleave',
    voiceCategory: 'human_male_ikemen',
    flavor:
      'しなやかな鞭を華麗に操る冒険家。敵を攻撃する際に、その長いリーチを活かして複数の対象を同時に討つ。',
  },
  {
    id: 'mummy',
    name: '王墓の番人',
    rarity: 1,
    power: 4,
    skill: 'burial',
    skillValue: 3,
    voiceCategory: 'undead',
    flavor:
      '永遠の眠りを守る呪われた守護者。その長い寿命は、守るべき秘宝と同じくらい朽ち果ててはいない。',
  },
  {
    id: 'crocodile',
    name: 'クロコダイル',
    rarity: 1,
    power: 6,
    skill: 'maintain',
    voiceCategory: 'beast',
    flavor:
      '太古の昔より大河の主として君臨し続ける巨大な爬虫類。その強靭なる顎は全てを噛み砕き、圧倒的な存在感は全てを威圧する。',
  },
  {
    id: 'zombie',
    name: '死蠅の大群',
    rarity: 1,
    power: 1,
    skills: [
      { id: 'clone', value: 2 },
      { id: 'growth', value: -1 },
    ],
    voiceCategory: 'insect',
    flavor:
      '屍から次々と湧き出し、空を黒く染め上げる不浄の群れ。おぞましい羽音を響かせて増殖する',
  },
  {
    id: 'goat',
    name: 'スケープゴート',
    rarity: 1,
    power: 3,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'charge', value: 2 },
    ],
    voiceCategory: 'monster',
    flavor:
      '不吉な儀式の供物として捧げられる山羊。その命が尽きる時、主には強大な魔力が還元される。',
  },
  {
    id: 'devil',
    name: '地獄の放火魔',
    rarity: 1,
    power: 2,
    skills: [
      { id: 'spread', value: 3 },
      { id: 'explode', value: 3 },
    ],
    voiceCategory: 'devil',
    flavor:
      '背中のタンクには地獄の業火が詰まっている。初めて武器を与えられた小悪魔は、その焦熱を振り撒くことに至上の喜びを感じていた。',
  },
  {
    id: 'cyberman',
    name: 'ライオット・キーパー',
    rarity: 2,
    power: 6,
    skills: [{ id: 'charge', value: -1 }],
    voiceCategory: 'machine_new',
    flavor:
      '「システム始動……これより排除を開始する。」最新型の暴徒鎮圧用アンドロイド。',
  },
  {
    id: 'mech',
    name: '略奪者のキメラ・メック',
    rarity: 2,
    power: 5,
    skills: [
      { id: 'choice', value: 1 },
      { id: 'explode', value: 2 },
    ],
    choices: [{ id: 'snipe', value: 2 }, { id: 'sturdy' }],
    voiceCategory: 'machine_old',
    flavor:
      'アッシュランドの盗賊団に好まれる歩行戦車。拾い集めた鉄屑で思い思いの魔改造が施されており、二つとして同じ機体は存在しない。',
  },
  {
    id: 'bigai',
    name: 'サイクロプス Mk-II',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'charge', value: -1 },
      { id: 'snipe', value: 5 },
    ],
    voiceCategory: 'machine_new',
    flavor: '単眼の狙撃特化型自律ユニット。一撃必殺の精度を誇る。',
  },
  {
    id: 'dreadnought',
    name: 'ドラゴン・ドレッドノート',
    rarity: 2,
    power: 10,
    skills: [
      { id: 'sturdy' },
      { id: 'standby', value: 3 },
      { id: 'growth', value: -2 },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '純粋な破壊を目的に建造された古代大戦の巨大兵器。冷たい鋼の奥底で重厚な機関音を響かせ、再び空を焦がす再起動の刻を静かに待っている。',
  },
  {
    id: 'mechanic',
    name: 'ダクト街の技師',
    rarity: 2,
    power: 4,
    skill: 'summon',
    skillValue: 1,
    summonId: 'token_drone',
    voiceCategory: 'human_female_normal',
    flavor:
      '廃れた近未来都市で生きる腕利きのメカニック。彼女の作るドローンはどんな狭い隙間にも潜り込む。',
  },
  {
    id: 'gladiator',
    name: '違法リングの闘士',
    rarity: 2,
    power: 7,
    skill: 'legendary',
    voiceCategory: 'machine_new',
    flavor:
      '欲望渦巻く未来都市の非合法リングに立つ鋼の闘士。冷徹なる闘志のみを胸に秘め、血とオイルに塗れた容赦なき死闘へと身を投じる。',
  },
  {
    id: 'babydragon',
    name: 'ドラゴンの雛',
    rarity: 2,
    power: 2,
    skill: 'growth',
    skillValue: 3,
    voiceCategory: 'lizard',
    flavor:
      'まだ小さなドラゴンの幼体。秘めたる魔力は無限の可能性を感じさせる。',
  },
  {
    id: 'dragonewt',
    name: '竜人族の騎兵',
    rarity: 2,
    power: 4,
    skills: [{ id: 'pierce' }, { id: 'snipe', value: 2 }],
    voiceCategory: 'horse',
    flavor:
      '竜人族の騎兵。翼は無いが、戦場を駆け抜け敵を貫き、遠方の獲物も逃さない。',
  },
  {
    id: 'wyvern',
    name: '群れのワイヴァーン',
    rarity: 2,
    power: 7,
    skills: [{ id: 'takeover' }, { id: 'reinforce', value: 1 }],
    voiceCategory: 'dragon',
    flavor:
      '空を滑る緑の影は、必ず二つ。一方を殺したと安堵するなら、それは間違いだ。その血の匂いは、雲の彼方から狂乱のもう一方を呼び寄せる。',
  },
  {
    id: 'hammer',
    name: '雷神の鎚',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'equip' },
      { id: 'snipe', value: 3 },
      { id: 'salvage', value: 1 },
    ],
    voiceCategory: 'stone',
    flavor:
      '天の怒りを顕現せし剛雷の戦鎚。主の呼応に応じて雷鳴と共に飛来し、万物を等しく打ち砕く。',
  },
  {
    id: 'berserker',
    name: '狂戦士',
    rarity: 2,
    power: 7,
    skill: 'berserk',
    skillValue: 3,
    voiceCategory: 'giant',
    flavor:
      '破壊の衝動に魂を売った禁忌の戦士。痛みすら悦びとして斧を振り回す。',
  },
  {
    id: 'drake',
    name: '熱砂地帯のドレイク',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'spread', value: 1 }],
    voiceCategory: 'lizard',
    flavor:
      '熱砂の空を舞う暴虐の亜竜。その巨翼で砂嵐を巻き起こし絶対者のように振る舞うが、真なる竜が降臨するまでの間だけ偽りの威厳を振りかざし大地を蹂躙しているに過ぎない。',
  },
  {
    id: 'nobleknight',
    name: '従者持ちの騎士',
    rarity: 2,
    power: 2,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'summon', value: 2, summonId: 'token_knight' },
      { id: 'support', value: 2 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '戦場に立つ彼の傍らには、常に忠実な影が寄り添う。名家の誇りを胸に彼が剣を掲げた時、その影は主を守る盾となり、あるいは共に敵を穿つ刃となる。',
  },
  {
    id: 'minotaur',
    name: 'ミノタウロスの傭兵',
    rarity: 2,
    power: 7,
    skills: [{ id: 'choice', value: 1 }, { id: 'cleave' }],
    choices: [
      { id: 'convert', value: 2 },
      { id: 'brutal', value: 2 },
    ],
    voiceCategory: 'giant',
    flavor:
      '圧倒的な力で敵を薙ぎ払うミノタウルスの傭兵。ただし、適切な報酬が支払われなければ、敵味方の区別なく暴れまわる。',
  },
  {
    id: 'hero',
    name: '若き勇士',
    rarity: 2,
    power: 4,
    skill: 'hero',
    skillValue: 2,
    voiceCategory: 'human_female_normal',
    flavor:
      '安物の胸当てに、誇りと希望だけを詰め込んだ新米訓練兵。その不器用な剣筋も、いつか伝説へと連なる。',
  },
  {
    id: 'crusher',
    name: '豪腕の破壊者',
    rarity: 2,
    power: 4,
    skill: 'crush',
    skillValue: 1,
    voiceCategory: 'human_male_ikemen',
    flavor:
      '巨大な武器を力任せに振るい、立ち塞がる障害物や罠を淡々と壊して回る頼れる力仕事の専門家。',
  },
  {
    id: 'horse',
    name: 'セレスタリアン・チャージャー',
    rarity: 2,
    power: 4,
    skills: [{ id: 'equip' }, { id: 'pierce' }],
    voiceCategory: 'horse',
    flavor:
      '誇り高きセレスタリアの紋章を背負う戦馬。その力強い蹄の音は、王国の勝利を告げるファンファーレである。',
  },
  {
    id: 'lion',
    name: '王家のライオン',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'quick' }],
    voiceCategory: 'beast',
    flavor:
      '黄金に輝く鬣は王家の威信を象徴し、その雄叫びは迫り来る邪悪を打ち払う誇り高き守護者。',
  },
  {
    id: 'prince',
    name: '星の王子',
    rarity: 2,
    power: 2,
    skill: 'stealth',
    skillValue: 2,
    voiceCategory: 'monster',
    flavor:
      '黒き触手に抱かれた幼き王は、遥か宇宙の深淵から、我らの空へと帰還しつつある。',
  },
  {
    id: 'slime',
    name: '這い寄るスライム',
    rarity: 2,
    power: 4,
    skills: [{ id: 'takeover' }, { id: 'clone', value: 1 }],
    voiceCategory: 'undead',
    flavor:
      '死骸に一滴でも取り付かれれば最後。剣を振り下ろす頃には、すでに二匹に増殖して君の喉元へ飛びかかっているだろう。',
  },
  {
    id: 'shark',
    name: 'メガロドン',
    rarity: 2,
    power: 6,
    skills: [
      { id: 'stealth', value: 1 },
      { id: 'standby', value: 1 },
    ],
    voiceCategory: 'insect',
    flavor:
      '深き蒼から突如として現れる規格外の巨体。その顎が海面を割る時、逃げる術は既に残されていない。',
  },
  {
    id: 'seaslug',
    name: 'ブルー・ドラゴン',
    rarity: 2,
    power: 1,
    skills: [{ id: 'bless', value: 2 }],
    voiceCategory: 'insect',
    flavor:
      '青き海を漂う幻獣。その姿を見た者には、ささやかな海の恵みがもたらされるという。',
  },
  {
    id: 'parasite',
    name: '招かれざる来訪者',
    rarity: 2,
    power: 1,
    skills: [
      { id: 'equip' },
      { id: 'clone', value: 1 },
      { id: 'growth', value: -1 },
    ],
    voiceCategory: 'insect',
    flavor:
      '宇宙の深淵から飛来した、冷たく蠢く無機生命体。音もなく宿主に取り付いて生命力を啜り、自らの似姿を静かに増殖させながら、やがて全てを空洞の石へと変えていく。',
  },
  {
    id: 'ghostship',
    name: 'ファントムポートの幽霊船',
    rarity: 2,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'stealth', value: 1 }],
    voiceCategory: 'stone',
    flavor:
      '星の光すら届かぬ静寂の海、濃霧の奥底より音もなく現れる呪われた艦。朽ち果てた帆に亡者たちの嘆きを孕み、目撃した者を永遠の深淵へと引きずり込む。',
  },
  {
    id: 'bard',
    name: '森の歌うたい',
    rarity: 2,
    power: 1,
    skills: [
      { id: 'support', value: 2 },
      { id: 'heal', value: 2 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      'ウクレレを奏でる彼を、森の動物たちは親しみを持って「先生」と呼ぶ。その歌声は傷ついた心も体も癒やす。',
  },
  {
    id: 'bear',
    name: '森の恐怖',
    rarity: 2,
    power: 3,
    skills: [{ id: 'pierce' }, { id: 'lone_wolf', value: 2 }],
    voiceCategory: 'beast',
    flavor:
      '禁域に迷い込んだ愚か者に与えられるのは、警告ではない。ただ前触れなき蹂躙のみである。',
  },
  {
    id: 'centaur',
    name: 'ケンタウロスの父',
    rarity: 2,
    power: 1,
    skills: [{ id: 'equip' }, { id: 'snipe', value: 5 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '弓の引き方も、剣の握り方も、全てはこの背中が教えた。種族の壁を超えて彼を育て上げたその姿は、間違いなく一人の「父親」のそれであった。',
  },
  {
    id: 'shaman',
    name: '樫族のシャーマン',
    rarity: 2,
    power: 4,
    skill: 'dispel',
    skillValue: 1,
    voiceCategory: 'human_male_old',
    flavor:
      '彼の呪術は敵の武装を縛り、そして砕く。千年の時を生きる老エルフの瞳には、人の造りし武具など児戯に等しい。',
  },
  {
    id: 'splite',
    name: 'スプライトの冒険者',
    rarity: 2,
    power: 2,
    skill: 'resist',
    skillValue: 3,
    voiceCategory: 'human_female_cute',
    flavor:
      '未知なる世界への憧れを胸に、安全な故郷の森を旅立ったスプライト。生来のすばしっこさと微かな光の加護が、彼女を守護している。',
  },
  {
    id: 'ranger',
    name: 'ルーン辿りのレインジャー',
    rarity: 2,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'snipe', value: 4 }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '微かに光るルーンの印だけが、彼に失くした過去を呼び覚ます。深緑の外套を揺らし、記憶の残香を辿る旅。その道を阻む理不尽なる者がいれば、一切の迷いなき必中の矢が静かに急所を射抜く。',
  },
  {
    id: 'charity',
    name: '慈愛',
    rarity: 2,
    power: 3,
    skills: [{ id: 'heal', value: 4 }, { id: 'defender' }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '古より伝わる小さな彫像。周囲に清らかな癒しと絶対の護りをもたらす。',
  },
  {
    id: 'barrier',
    name: '聖光の護り手',
    rarity: 2,
    power: 4,
    skills: [{ id: 'guardian' }, { id: 'support', value: 1 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '清浄な心で奇跡を呼ぶ賢者。その盾は、不浄なるものを一切寄せ付けない。',
  },
  {
    id: 'light',
    name: '無垢の光',
    rarity: 2,
    power: 4,
    skills: [{ id: 'equip' }, { id: 'oblivion' }],
    voiceCategory: 'human_female_cute',
    flavor:
      '優しく降り注ぐ、穢れなき無垢の光。その暖かな輝きに抱かれた時、苦しみも、悪意も、自分が何者であったかさえも安らかに白く溶け落ちていく。',
  },
  {
    id: 'doom',
    name: '破滅',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'spread', value: 6 },
      { id: 'defender' },
      { id: 'sturdy' },
      { id: 'takeover' },
    ],
    voiceCategory: 'stone',
    flavor: '古より伝わる小さな彫像。周囲に底知れぬ絶望と絶大な破滅をもたらす',
  },
  {
    id: 'flak',
    name: 'ミスリルの高射砲',
    rarity: 2,
    power: 6,
    skills: [{ id: 'defender' }, { id: 'intercept', value: 3 }],
    voiceCategory: 'machine_old',
    flavor: '高高度を狙う神聖なる対空砲。上空からの奇襲を許さない。',
  },
  {
    id: 'monk',
    name: '夜明けの番人',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'heal', value: 4 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '冷たい鋼の鎖帷子を纏い、闇夜を斬り裂く一条の光。神の教えを胸に刻み、冒涜者たちを容赦なく浄化する、悪魔にとって最も恐るべき裁きの代行者。',
  },
  {
    id: 'bat',
    name: '吸血コウモリ',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'clone', value: 1 },
      { id: 'absorb' },
    ],
    voiceCategory: 'insect',
    flavor:
      '影から忍び寄り、静かに獲物の命を啜る。その羽ばたきが聞こえた時、既に逃げ場は失われている。',
  },
  {
    id: 'franken',
    name: 'オールドヘイヴンの怪物',
    rarity: 2,
    power: 8,
    skill: 'standby',
    skillValue: 2,
    voiceCategory: 'giant',
    flavor:
      '見捨てられた街の地下深くに眠る禁断の造物。動き出せば、その怪力で全てを粉砕する。',
  },
  {
    id: 'specter',
    name: '魂の徴税人',
    rarity: 2,
    power: 4,
    skills: [{ id: 'pierce' }, { id: 'extort', value: 2 }],
    voiceCategory: 'undead',
    flavor:
      '慈悲はない。情状酌量もない。冥府の帳簿の帳尻を合わせるため、それは今日も無作為に魂を削り取っていく。',
  },
  {
    id: 'plaguedoctor',
    name: '烏羽の医師',
    rarity: 2,
    power: 3,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'heal', value: 2 },
      { id: 'toxic', value: 2 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '彼女の処方箋は、明日を繋ぐ特効薬か、あるいは安息へと誘う安楽死の劇薬か',
  },
  {
    id: 'servant',
    name: '吸血鬼の従者',
    rarity: 2,
    power: 2,
    skills: [{ id: 'equip' }, { id: 'soul_bind', value: 3 }],
    voiceCategory: 'human_female_sexy',
    flavor:
      '「ふふっ、とても頼もしいお方……どうか私を、貴方様の傍に置いてくださる？」自らの弱さを知る妖艶な吸血鬼は、永遠の夜を生き抜くため、甘い吐息と共に強き者の腕へとすり寄る。',
  },
  {
    id: 'undeadking',
    name: '亡国のデス・ロード',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'resurrect', value: 2 },
      { id: 'resurrect', value: 2 },
    ],
    voiceCategory: 'undead',
    flavor:
      '肉体が朽ち国が滅びようとも、永遠の忠誠の証である錆びた王冠を戴く骸の王。虚ろな眼窩の奥底で、死を超越した王の威光が今もなお冷たく輝いている。',
  },
  {
    id: 'cat',
    name: '食糧庫のコソ泥',
    rarity: 2,
    power: 2,
    skills: [{ id: 'quick' }, { id: 'extort', value: 2 }],
    voiceCategory: 'beast',
    flavor:
      '城の警備もなんのその、神出鬼没の小さな怪盗は宵の闇をすり抜けていく。',
  },
  {
    id: 'mage',
    name: '未熟な拡散魔導士',
    rarity: 2,
    power: 1,
    skill: 'spread',
    skillValue: 2,
    voiceCategory: 'human_female_cute',
    flavor:
      '魔導アカデミーの見習い魔導士。魔法のコントロールが苦手で、呪文を詠唱するたびに暴走した魔力が周囲へバラバラに散乱してしまう。',
  },
  {
    id: 'battlemage',
    name: 'ギルドの戦闘魔導士',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_male_warrior',
    flavor:
      '剣と魔法を操る魔導士。彼らが招集されたということは、困難な任務であることを意味する',
  },
  {
    id: 'dragonfire',
    name: 'ドラゴンファイア',
    rarity: 2,
    power: 0,
    skill: 'choice',
    skillValue: 1,
    choices: [
      { id: 'artillery', value: 2 },
      { id: 'snipe', value: 8 },
    ],
    voiceCategory: 'magic',
    flavor:
      '厳重に封印された硝子瓶。中で燻るのは、万物を灰燼に帰す竜王の怒りだ。',
  },
  {
    id: 'gargoyle',
    name: 'ガーゴイル',
    rarity: 2,
    power: 5,
    skills: [{ id: 'sturdy' }, { id: 'standby', value: 2 }],
    voiceCategory: 'stone',
    flavor:
      '塔の頂から見下ろす冷たい石の瞳。夜の帳が下りる時、それは獲物を狙う狩人となる。',
  },
  {
    id: 'ring',
    name: '願いの指輪',
    rarity: 2,
    power: 1,
    skills: [{ id: 'legendary' }, { id: 'equip' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'heal', value: 2 },
      { id: 'spread', value: 2 },
      { id: 'draw', value: 2 },
      { id: 'snipe', value: 3 },
      { id: 'support', value: 2 },
      { id: 'lone_wolf', value: 2 },
    ],
    voiceCategory: 'magic',
    flavor:
      '黄金の輪に封じられし古の魔神の強大なる奇跡。富か力か、それとも破滅か。指先に光る魅惑の輝きは、持ち主の運命を狂わせる甘い毒となる。',
  },
  {
    id: 'gashadokuro',
    name: '餓者髑髏',
    rarity: 2,
    power: 9,
    skills: [{ id: 'awake', value: 1, summonId: 'token_soul' }],
    voiceCategory: 'undead',
    flavor:
      '戦場に散った無数の亡骸が、今ここに集い、一つの巨大な骸骨の巨人を形成する。その眼窩に宿るは、尽きぬ飢餓と復讐の炎。',
  },
  {
    id: 'muramasa',
    name: '無銘の妖刀',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'equip' },
      { id: 'choice', value: 1 },
      { id: 'choice', value: 1, choiceGroup: 2 },
    ],
    choices: [
      { id: 'loss', value: 4 },
      { id: 'sacrifice', value: 2 },
    ],
    choices2: [{ id: 'absorb' }, { id: 'soul_bind', value: 2 }],
    voiceCategory: 'sword',
    flavor:
      '持ち主の魂をすり減らして無限の切れ味を誇る妖刀。だがその代償を支払うか、敵の血肉で補うかは刃が勝手に選び取る。',
  },
  {
    id: 'samurai',
    name: '山道の人斬り',
    rarity: 2,
    power: 7,
    skill: 'challenge',
    voiceCategory: 'human_male_warrior',
    flavor:
      '寂れた峠道に、血の匂いと白刃が閃く。強き者との死合いのみを渇望する修羅は、目の前の標的へと歩み寄り、静かに刀を抜く。',
  },
  {
    id: 'yukionna',
    name: '薄氷の乙女',
    rarity: 2,
    power: 3,
    skill: 'freeze',
    skillValue: 1,
    voiceCategory: 'human_female_cool',
    flavor:
      '吐息は白く、眼差しは氷よりも冷たく。彼女が優しく微笑みかける時、哀れな犠牲者の血潮は凍りつき、戦場に永遠の静寂なる像が立ち並ぶ。',
  },
  {
    id: 'tengu',
    name: '武芸の師範',
    rarity: 2,
    power: 4,
    skill: 'move',
    voiceCategory: 'human_male_warrior',
    flavor:
      '深山に棲まう、風を操り空を舞う人外の剣客。武の神髄を修めたその一太刀は、驕れる人間たちに真の恐怖と剣術の深淵を叩き込む。',
  },
  {
    id: 'nurikabe',
    name: '見下ろす巨顔',
    rarity: 2,
    power: 13,
    skills: [{ id: 'legendary' }, { id: 'defender' }],
    voiceCategory: 'stone',
    flavor:
      '宵闇の道程、突如として立ちはだかる絶対の絶望。どれほど刃を立てようとも揺るがぬその巨岩の貌は、愚かな侵入者をただ冷ややかに見下ろしている。',
  },
  {
    id: 'camel',
    name: '駄載ラクダ',
    rarity: 2,
    power: 3,
    skills: [{ id: 'equip' }, { id: 'move' }],
    voiceCategory: 'beast',
    flavor:
      '荒野を征く旅人たちの必需品。その背には重い荷物が積まれ、あるいは戦場へと駆り出される。',
  },
  {
    id: 'manticore',
    name: '鋼のマンティコア',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'maintain' },
      { id: 'sturdy' },
      { id: 'intercept', value: 2 },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '忘れ去られた古代文明の遺物であり、侵入者を排除するためだけに稼働し続ける機械魔獣。',
  },
  {
    id: 'griffin',
    name: 'グリフィン',
    rarity: 2,
    power: 7,
    skills: [{ id: 'takeover' }, { id: 'move' }, { id: 'pierce' }],
    voiceCategory: 'bird',
    flavor:
      '鷲の頭と獅子の胴体を持つ神聖なる獣。その翼は天空を制し、その爪は大地を切り裂く。',
  },
  {
    id: 'snakepriest',
    name: '蛇の神官',
    rarity: 2,
    power: 4,
    skills: [{ id: 'challenge' }, { id: 'toxic', value: 4 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '毒蛇を従え、戦士たちに過酷な試練を課す神殿の導き手。彼女の放つ猛毒に耐え抜き、その静かなる牙を掻いくぐった者のみが、真の勇者として認められる。',
  },
  {
    id: 'kitepriest',
    name: '鳶の神官',
    rarity: 2,
    power: 4,
    skill: 'recurse',
    skillValue: 4,
    voiceCategory: 'human_female_cool',
    flavor:
      '空高く舞う鳶の目を持ち、過去と未来を見通す冷徹なる巫女。彼女が紡ぐ神秘の呪文は、途切れた運命の糸を再び繋ぎ合わせ、何度でも奇跡を呼び起こす。',
  },
  {
    id: 'sentinel',
    name: '黄金の歩哨',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'guardian' }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '遺跡の深部で王の眠りを守護する黄金の機械兵士。暗い石室に、古く軋んだ駆動音が響き渡る。',
  },
  {
    id: 'dealer',
    name: 'デビル・ディーラー',
    rarity: 2,
    power: 5,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'draw', value: 3 },
    ],
    flavor:
      '「さあ、運命を選びな。代償は君の魂で十分だ。」不敵な笑みを浮かべる悪魔の占い師。',
  },
  {
    id: 'warlock',
    name: '煉獄の拷問官',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'sacrifice', value: 4 },
      { id: 'berserk', value: 4 },
      { id: 'spread', value: 4 },
    ],
    voiceCategory: 'undead',
    flavor:
      '燃え盛る炎の鞭を振るう魔界の拷問官。その一振りは敵を焼き払い、自らの魂さえも劫火の糧とする。',
  },
  {
    id: 'hand',
    name: '悪魔の手',
    rarity: 2,
    power: 2,
    skills: [{ id: 'cull' }],
    voiceCategory: 'stone',
    flavor:
      '虚空を裂いて現れる、魔界より召喚されし巨大な腕。いかなる堅牢な障害も無慈悲に握り潰す。',
  },
  {
    id: 'minion',
    name: '魔王のしもべ',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'sacrifice', value: 1 },
      { id: 'awake', value: 7, summonId: 'token_daemon' },
    ],
    voiceCategory: 'human_male_old',
    flavor: '歪んだ忠誠を誓う狂信者。彼の儀式は、強大な闇を招く呼び水となる。',
  },
  {
    id: 'cavalry',
    name: '煉獄侯爵の先陣',
    rarity: 2,
    power: 8,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'challenge' },
      { id: 'pierce' },
      { id: 'guardian' },
    ],
    voiceCategory: 'horse',
    flavor:
      '焦熱の風を切り裂き、気高き悪魔が戦場を駆ける。その立ち振る舞いはどこまでも優雅にして、振るう一撃は残酷そのもの。',
  },
  {
    id: 'wendigo',
    name: '吹雪の悪霊',
    rarity: 2,
    power: 7,
    skills: [
      { id: 'legendary' },
      { id: 'takeover' },
      { id: 'freeze', value: 2 },
    ],
    voiceCategory: 'beast',
    flavor:
      '死の嵐の中で、それは永遠の飢えを満たそうと彷徨う。すべてを喰らい、すべてを凍らせ、後には静寂な雪原だけが残される。',
  },
  {
    id: 'cyborgninja',
    name: '光刃の追跡者',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'charge', value: -2 },
      { id: 'choice', value: 2 },
    ],
    choices: [
      { id: 'stealth', value: 1 },
      { id: 'clone', value: 1 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '金属の心臓と人間の執念を併せ持つ、鋼鉄の隠密。暗闇に溶け込み、敵の虚をつく一撃は、戦局を覆す決定打となる。',
  },
  {
    id: 'booster',
    name: 'イーグルブースター',
    rarity: 3,
    power: 1,
    skills: [{ id: 'equip' }, { id: 'quick' }],
    voiceCategory: 'machine_new',
    flavor:
      '天空を駆ける鷲が如き加速力をもたらす推進器。対象は瞬く間に敵陣を強襲する。',
  },
  {
    id: 'hacker',
    name: '未来都市のハッカー',
    rarity: 3,
    power: 5,
    skills: [{ id: 'hack' }],
    voiceCategory: 'human_female_normal',
    flavor:
      '網膜に映る情報の海を泳ぎ、堅牢なセキュリティの隙を突く電子の魔術師。彼女の指先が動くとき、隠された機密データが白日の下に晒される。',
  },
  {
    id: 'cyberdragon',
    name: '試作型ドラグーン',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'spread', value: 3 },
      { id: 'charge', value: -3 },
    ],
    voiceCategory: 'machine_new',
    flavor: '試作型の重機動兵器。圧倒的な面制圧力を持つ。',
  },
  {
    id: 'egg',
    name: 'ドラゴンの卵',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'defender' },
      { id: 'growth', value: -1 },
      { id: 'split', value: 6, summonId: 'token_dragon' },
    ],
    voiceCategory: 'stone',
    flavor:
      '表面を覆う紅い殻が、内側から微かな熱を帯びている。いつか訪れる孵化の刻まで、秘めたる命は静かに力を蓄え続ける。',
  },
  {
    id: 'phoenix',
    name: 'カラドのフェニックス',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'split', value: 6, summonId: 'token_phoenix' },
      { id: 'sacrifice', value: 3 },
      { id: 'berserk', value: 3 },
      { id: 'explode', value: 3 },
    ],
    voiceCategory: 'bird',
    flavor:
      'カラド山の頂きを焦がす不滅の霊鳥。自らの命を爆炎と化し、その灰の中から幾度でも舞い戻る。',
  },
  {
    id: 'dragoon',
    name: '覇道のドラグーン',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'double_strike' },
      { id: 'awake', value: 6, summonId: 'token_dragon' },
    ],
    voiceCategory: 'human_female_assassin',
    flavor:
      '竜の力を宿す騎士。彼女の槍が閃く時、漆黒の翼が空を覆い、敵陣に絶望の業火が舞い降りる。',
  },
  {
    id: 'dragon',
    name: 'ファイア・ドラゴン',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'legendary' },
      { id: 'berserk', value: 3 },
      { id: 'spread', value: 2 },
    ],
    voiceCategory: 'dragon',
    flavor:
      '炎を纏った紅蓮の翼。その咆哮は敵を焼き払い、荒ぶる魔力は周囲をも巻き込む。',
  },
  {
    id: 'admiral',
    name: '慈悲なき提督',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'takeover' },
      { id: 'summon', value: 2, summonId: 'token_knight' },
      { id: 'summon', value: 2, summonId: 'token_knight' },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '狂気と野望を海図に描き、己の栄光のために部下をも駒として消費する冷酷なる海将。',
  },
  {
    id: 'elephant',
    name: '攻城エレファント',
    rarity: 3,
    power: 6,
    skills: [{ id: 'takeover' }, { id: 'equip' }],
    voiceCategory: 'stone',
    flavor:
      '分厚い装甲と武装を纏った、歩く攻城兵器。その圧倒的な質量と歩みは、いかなる城壁や防陣もただの瓦礫の山へと変える。',
  },
  {
    id: 'assassin',
    name: 'ギルドの暗殺者',
    rarity: 3,
    power: 1,
    skills: [{ id: 'deadly' }, { id: 'stealth', value: 1 }, { id: 'quick' }],
    voiceCategory: 'human_female_assassin',
    flavor:
      '黒い服と2つの短剣を持つ女暗殺者。一瞬の隙も逃さず、死の影から獲物を屠る。',
  },
  {
    id: 'champion',
    name: 'アリーナのチャンピオン',
    rarity: 3,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'hero', value: 3 }],
    voiceCategory: 'human_male_warrior',
    flavor: '観衆の歓声こそが彼の力。その雄姿は味方を鼓舞し、敵を圧倒する。',
  },
  {
    id: 'octopus',
    name: '深海の魔物',
    rarity: 3,
    power: 4,
    skill: 'split',
    skillValue: 2,
    summonId: 'legs',
    voiceCategory: 'monster',
    flavor:
      '深海に潜む異形の魔物。全身が筋肉の塊で、足を失ってもすぐに生えてくる。',
  },
  {
    id: 'hound',
    name: '破片の猟犬',
    rarity: 3,
    power: 4,
    skill: 'phase',
    voiceCategory: 'monster',
    flavor:
      '時間の死角から滲み出す次元の捕食者。その幾何学的な牙から逃れられる者は、過去にも未来にも存在しない。',
  },
  {
    id: 'horseshoecrab',
    name: '太古のカブトガニ',
    rarity: 3,
    power: 1,
    skills: [{ id: 'deadly' }, { id: 'bless', value: 1 }],
    voiceCategory: 'insect',
    flavor:
      '数億年の時を超えて生き続ける、生きた化石。その堅牢な甲殻と秘めた猛毒は、全ての外敵を等しく絶望へと突き落とす。',
  },
  {
    id: 'oldgod',
    name: '古の神',
    rarity: 3,
    power: 9,
    skills: [
      { id: 'legendary' },
      { id: 'takeover' },
      { id: 'stealth', value: 1 },
      { id: 'pierce' },
    ],
    voiceCategory: 'monster',
    flavor: '深海の深淵より目覚めた、名もなき異形の神。その一撃は魂を貫く。',
  },
  {
    id: 'highelf',
    name: 'ロストレイルの精鋭パトロール',
    rarity: 3,
    power: 2,
    skills: [
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
    ],
    voiceCategory: 'human_female_cool',
    flavor: '迷いの森を監視する精鋭。その神速の連射は、影すらも逃がさない。',
  },
  {
    id: 'thief',
    name: 'ギルドの錠前破り',
    rarity: 3,
    power: 3,
    skill: 'choice',
    skillValue: 1,
    choices: [
      { id: 'dispel', value: 1 },
      { id: 'crush', value: 1 },
      { id: 'salvage', value: 1 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '複雑な魔法陣の解除から力任せの破壊工作、そして遺物の回収まで。彼女の淀みない手口の前では、いかなる障害も意味を成さない。',
  },
  {
    id: 'caller',
    name: '魔琴の奏者',
    rarity: 3,
    power: 3,
    skill: 'call',
    skillValue: 3,
    voiceCategory: 'human_female_cool',
    flavor:
      '奏でられるのは森の賛歌か、それとも愚者への鎮魂歌か。ただ確かなのは、その妖しき調べを耳にしたが最後、大いなる森の軍勢から逃れる術はないということだ。',
  },
  {
    id: 'wolf',
    name: '真夜中の狩人',
    rarity: 3,
    power: 3,
    skills: [{ id: 'legendary' }, { id: 'lone_wolf', value: 3 }],
    voiceCategory: 'wolf',
    flavor:
      '月の光を浴びて強靭な力を得る孤高の戦士。群れを嫌い、独りで獲物を追い詰める。',
  },
  {
    id: 'fire',
    name: '浄化の炎',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'artillery', value: 3 },
      { id: 'defender' },
      { id: 'guardian' },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '異端を焼き払う神聖なる十字。その盾は信徒を守り、砲口は敵への裁きを下す。',
  },
  {
    id: 'punisher',
    name: 'パニッシャー',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'choice', value: 1 },
      { id: 'explode', value: 4 },
    ],
    choices: [
      { id: 'spread', value: 2 },
      { id: 'artillery', value: 2 },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '神罰は上空より舞い降りる。重火器の爆音を讃美歌とし、異端を灰へと還す教会の執行人。',
  },
  {
    id: 'carousel',
    name: 'カルーセル',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'defender' },
      { id: 'sturdy' },
      { id: 'move' },
      { id: 'immune' },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '重々しい轟音を立てて戦線を移動する、車輪を備えた巨大な鉄盾。古き歯車を軋ませながらあらゆる攻撃を無効化し、味方の絶対的な防壁となる。',
  },
  {
    id: 'empress',
    name: '蒼穹の審判者',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'legendary' },
      { id: 'heal', value: 3 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_female_normal',
    flavor: '宇宙の理を掌るオーブを掲げ、全ての魂に等しく審判を下す聖女。',
  },
  {
    id: 'vampire',
    name: '渇きの王',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'soul_bind', value: 4 },
      { id: 'growth', value: -1 },
    ],
    voiceCategory: 'undead',
    flavor:
      '冷笑を浮かべる夜の支配者. 彼の者に狙われた者は、魂の底まで吸い尽くされる。',
  },
  {
    id: 'graverobber',
    name: '優雅な墓荒らし',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'salvage', value: 1 },
      { id: 'resurrect', value: 3 },
    ],
    voiceCategory: 'human_female_normal',
    flavor:
      '朽ちた墓石を踏み躙り、泥に塗れたドレスを優雅に翻す。彼女にとって死者の尊厳など、土に眠る財宝の輝きには遠く及ばないのだ。',
  },
  {
    id: 'beast',
    name: '廃教会の獣',
    rarity: 3,
    power: 7,
    skill: 'loss',
    skillValue: 5,
    voiceCategory: 'wolf',
    flavor:
      '見捨てられた街の大橋に巣くう巨大な獣。自らが何者であったのか、記憶の全てを失ってもなお、主のいない教会を侵入者から守り続けている。',
  },
  {
    id: 'collector',
    name: 'ヘッドコレクター',
    rarity: 3,
    power: 1,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 3 },
      { id: 'resurrect', value: 8 },
      { id: 'deadly' },
    ],
    voiceCategory: 'undead',
    flavor:
      '集められた数多の魂が慟哭を上げる。彼の者が通り過ぎた後には、首のない骸だけが残される。',
  },
  {
    id: 'basilisk',
    name: 'バジリスク',
    rarity: 3,
    power: 5,
    skill: 'petrify',
    voiceCategory: 'snake',
    flavor:
      'その猛毒の視線と交わったが最後。生者の肉体は瞬く間に無機質な彫像へと変わり果て、永遠の沈黙に閉ざされる。',
  },
  {
    id: 'book',
    name: '禁書目録',
    rarity: 3,
    power: 0,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'resurrect', value: 6 },
      { id: 'charge', value: 3 },
    ],
    voiceCategory: 'magic',
    flavor:
      '禁じられた秘術が記された本。ページを捲るたび、正気は失われ、深淵の知識が魂を蝕んでいく。それでも力に飢えるなら、開くがいい。',
  },
  {
    id: 'witch',
    name: '闇の森の魔女',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'choice', value: 1 },
      { id: 'choice', value: 1, choiceGroup: 2 },
    ],
    choices: [
      { id: 'convert', value: 2 },
      { id: 'sacrifice', value: 2 },
      { id: 'berserk', value: -2 },
      { id: 'growth', value: -1 },
    ],
    choices2: [
      { id: 'draw', value: 2 },
      { id: 'heal', value: 2 },
      { id: 'spread', value: 1 },
      { id: 'soul_bind', value: 2 },
    ],
    voiceCategory: 'human_female_assassin',
    flavor:
      '深き森の奥に工房を構え、秘術を操る魔女。恐ろしい噂とは裏腹に、相応の金貨や珍しい素材さえ前払いで渡せば、大抵の厄介な依頼はきっちりとこなしてくれる。',
  },
  {
    id: 'djinn',
    name: '願いの魔神',
    rarity: 3,
    power: 1,
    skills: [
      { id: 'legendary' },
      { id: 'convert', value: 3 },
      { id: 'choice', value: 3 },
    ],
    choices: [
      { id: 'heal', value: 2 },
      { id: 'draw', value: 2 },
      { id: 'spread', value: 2 },
      { id: 'snipe', value: 3 },
      { id: 'lone_wolf', value: 2 },
      { id: 'support', value: 2 },
    ],
    voiceCategory: 'devil',
    flavor:
      'ランプの底で燻る欲望の煙。それは三度の奇跡となりて、主の運命を静かに狂わせる',
  },
  {
    id: 'fox',
    name: '魂喰いの狐',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'loss', value: 4 },
      { id: 'choice', value: 2 },
    ],
    choices: [
      { id: 'spread', value: 1 },
      { id: 'spread', value: 1 },
      { id: 'summon', value: 1, summonId: 'token_soul' },
      { id: 'summon', value: 1, summonId: 'token_soul' },
    ],
    voiceCategory: 'beast',
    flavor:
      '術者の魂すらも致命的な代償として喰らう、美しくも恐ろしき妖狐。奪った命を呪いの火として撒き散らすか、傀儡として現世に縛り付けるか、すべては彼女の気まぐれ。',
  },
  {
    id: 'kasha',
    name: '双輪の炎龍',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'takeover' },
      { id: 'quick' },
      { id: 'move' },
      { id: 'brutal', value: 2 },
    ],
    voiceCategory: 'dragon',
    flavor:
      '業火を纏い、地獄の車輪を軋ませて爆走する双頭の厄災。その神速の突進はあらゆる防壁を貫き、戦場を焦土に変えながら、ただ無残に蹂躙し尽くす。',
  },
  {
    id: 'orochi',
    name: '八岐大蛇',
    rarity: 3,
    power: 9,
    skills: [
      { id: 'takeover' },
      { id: 'double_strike' },
      { id: 'cleave' },
      { id: 'brutal', value: 3 },
    ],
    voiceCategory: 'snake',
    flavor:
      '贄の血の匂いに惹かれ、古の厄災が目を覚ます。八つの顎がもたらすのは、すべてを無に帰す純粋な破壊のみ。',
  },
  {
    id: 'shogun',
    name: '暁の大将軍',
    rarity: 3,
    power: 9,
    skills: [{ id: 'legendary' }, { id: 'challenge' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '昇る朝日を背に受け、威風堂々と戦場に立つ姿は軍神そのもの。一切の小細工を良しとせず、敵将の首を狙い真っ向から雌雄を決する。',
  },
  {
    id: 'stormpriest',
    name: '嵐の神官',
    rarity: 3,
    power: 2,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'berserk', value: 2 },
      { id: 'summon', value: 6, summonId: 'token_dragon' },
    ],
    voiceCategory: 'human_male_normal',
    flavor:
      '砂の海を統べる神の声を代弁し、軍勢を狂信へと導く神官。彼が杖を天に掲げる時、空は黒雲に覆われ、稲妻を纏った巨大な竜が戦場に顕現する。',
  },
  {
    id: 'goldship',
    name: '太陽の船',
    rarity: 3,
    power: 8,
    skills: [
      { id: 'takeover' },
      { id: 'maintain' },
      { id: 'standby', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'snipe', value: 8 },
      { id: 'intercept', value: 4 },
      { id: 'artillery', value: 4 },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '太古の神々が天空を巡るために建造したとされる、黄金に輝く巨大な飛行機関。永き眠りから目覚めたその船体は、失われた叡智の光で地上の不浄を焼き払う。',
  },
  {
    id: 'jackalpriest',
    name: 'ジャッカルの神官',
    rarity: 3,
    power: 5,
    skill: 'grave_keeper',
    voiceCategory: 'human_male_warrior',
    flavor:
      '生と死の境界に立ち、迷える魂を裁きの間へと導く孤高の番人。神聖なる王の眠りを妨げる愚者には、無慈悲なるジャッカルの牙が深く突き立てられる。',
  },
  {
    id: 'pharaoh',
    name: '不朽のファラオ',
    rarity: 3,
    power: 7,
    skills: [
      { id: 'legendary' },
      { id: 'loss', value: 4 },
      { id: 'burial', value: 6 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '神の化身として広大な砂漠を統べ、永遠の時を生きる絶対的な支配者。その絶大な力と威光の代償として、彼に仕える者たちは皆、等しく砂の底へと殉死していく運命にある。',
  },
  {
    id: 'daemon',
    name: '魔界の尖兵',
    rarity: 3,
    power: 7,
    skill: 'sacrifice',
    skillValue: 3,
    voiceCategory: 'devil',
    flavor:
      '強固な力と引き換えに契約者の魂を喰らう悪魔の兵士。その渇望は主ですら例外ではない。',
  },
  {
    id: 'daemonarmor',
    name: '悪魔の鎧',
    rarity: 3,
    power: 5,
    skills: [{ id: 'equip' }, { id: 'sacrifice', value: 2 }, { id: 'deadly' }],
    voiceCategory: 'sword',
    flavor:
      '真紅の血肉を喰らい、絶大なる力を対象に宿す呪われた甲冑。身に着けた者は代償として自らの生命を削り続ける。',
  },
  {
    id: 'succubus',
    name: '大鎌の夢魔',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'loss', value: 2 },
      { id: 'soul_bind', value: 2 },
      { id: 'absorb' },
      { id: 'cleave' },
    ],
    voiceCategory: 'human_female_sexy',
    flavor:
      '宵闇に浮かぶ冷たい微笑み。彼女の振るう大鎌は、命だけでなく、彼らが紡ぐはずだった未来の夢さえも刈り尽くす。',
  },
  {
    id: 'bahamut',
    name: '終焉の双頭竜',
    rarity: 3,
    power: 8,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 2 },
      { id: 'berserk', value: 2 },
      { id: 'double_strike' },
    ],
    voiceCategory: 'dragon',
    flavor:
      '二つの首が天を仰ぎ、終末の咆哮を上げる。その翼が振り下ろされる時、世界は劫火に包まれる。',
  },
  {
    id: 'threebears',
    name: '荒熊山賊団',
    rarity: 3,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'reinforce', value: 2 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '鬱蒼とした深森を縄張りとする、屈強な三兄弟の山賊団。熊をも素手で打ち倒すほどの圧倒的な暴力と結束力で、森に迷い込んだ獲物を決して逃がさない。',
  },
  {
    id: 'goldilocks',
    name: 'ゴールデンロックス',
    rarity: 3,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'resist', value: 6 }],
    voiceCategory: 'human_female_assassin',
    flavor:
      '鮮やかな金髪をなびかせる、孤高の武闘家。彼女は己の魂を震わせる『丁度いい強さ』の相手を求め、各地を放浪している。',
  },
  {
    id: 'badwolf',
    name: '幻影の狼',
    rarity: 3,
    power: 1,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'clone', value: 2 },
      { id: 'lone_wolf', value: 2 },
    ],
    voiceCategory: 'wolf',
    flavor:
      '森の深淵に潜む、実体なき銀狼。その姿を見た者は、一頭の獲物を追うつもりが、いつの間にか群れに囲まれていることに気付くのだ。',
  },
  {
    id: 'redhood',
    name: 'レッドフード',
    rarity: 3,
    power: 3,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'snipe', value: 5 },
      { id: 'spread', value: 1 },
    ],
    voiceCategory: 'human_female_normal',
    flavor:
      '赤い頭巾に隠された鋭い眼光。彼女のクロスボウから放たれる矢は、森の静寂を破ることなく標的の心臓を射抜く。',
  },
  {
    id: 'queen',
    name: '嫉妬の女王',
    rarity: 3,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [{ id: 'draw', value: 3 }, { id: 'deadly' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '”世界で一番美しいのは誰？”——その問いに答える者がいなくなるまで、ただ愚か者を狩り尽くすのみ。',
  },
  {
    id: 'snowwhite',
    name: 'スノウホワイト',
    rarity: 3,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'immune' }],
    voiceCategory: 'human_female_assassin',
    flavor:
      '”鏡よ鏡”。いつから私が、毒を盛られて黙っているようなお姫様だと錯覚していた？純白の鎧は復讐の誓い。',
  },
  {
    id: 'whiterider',
    name: '征服の使徒',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'contract', value: 4 },
      { id: 'snipe', value: 8 },
      { id: 'guardian' },
    ],
    voiceCategory: 'horse',
    flavor:
      '第一の封印が解かれし時、白馬に乗れる者が現る。彼は征服の上に更なる征服を重ねんとし、その矢は逃れ得ぬ運命を射抜く。',
  },
  {
    id: 'redrider',
    name: '戦争の使徒',
    rarity: 4,
    power: 5,
    skills: [{ id: 'contract', value: 4 }, { id: 'quick' }],
    voiceCategory: 'horse',
    flavor:
      '第二の封印。火の如き赤き馬に乗れる者、地上から平和を奪い去る。その大剣が振るわれる時、終わりなき争いの火蓋が切って落とされる。',
  },
  {
    id: 'blackrider',
    name: '飢餓の使徒',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'contract', value: 4 },
      { id: 'morph', value: 2 },
      { id: 'deadly' },
    ],
    voiceCategory: 'horse',
    flavor:
      '第三の封印。黒き馬に乗れる者が手にする天秤は、命の価値を量り、世界を等しく飢えと欠乏に陥れる。',
  },
  {
    id: 'palerider',
    name: '死の使徒',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'contract', value: 2 },
      { id: 'clone', value: 1 },
    ],
    voiceCategory: 'horse',
    flavor:
      '第四の封印。蒼褪めた馬に乗れる者の名は「死」。その後には黄泉が従い、生きとし生けるもの全てを静寂なる無へと誘う。',
  },
  {
    id: 'gearA',
    name: 'ストライクギア',
    rarity: 4,
    power: 2,
    skills: [
      { id: 'union', targetId: 'gearB', summonId: 'token_gearC' },
      { id: 'spread', value: 1 },
    ],
    voiceCategory: 'machine_new',
    flavor: '空を切り裂く蒼き翼。それは、来るべき覚醒の時を待つ巨神の半身。',
  },
  {
    id: 'gearB',
    name: 'グランドギア',
    rarity: 4,
    power: 8,
    skills: [
      { id: 'union', targetId: 'gearA', summonId: 'token_gearC' },
      { id: 'artillery', value: 1 },
      { id: 'defender' },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '地を這う無骨な鉄の脚。その真価は、空飛ぶ半身と交わった時にこそ発揮される。',
  },
  {
    id: 'tank',
    name: '自律戦車',
    rarity: 4,
    power: 4,
    skills: [
      {
        id: 'union',
        targetId: 'token_drone',
        summonId: 'token_reinforceddrone',
      },
      { id: 'snipe', value: 1 },
    ],
    voiceCategory: 'machine_new',
    flavor: '小型の無人攻撃兵器。',
  },
  {
    id: 'scientist',
    name: '世紀の天才科学者',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'summon', value: 1, summonId: 'token_drone' },
      { id: 'summon', value: 1, summonId: 'token_drone' },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '彼女の右に出る技術者はいない。その性格の難しさにさえ目を瞑れば、だが。',
  },
  {
    id: 'avenger',
    name: '竜人族の復讐者',
    rarity: 4,
    power: 4,
    skills: [{ id: 'retaliate', value: 2 }],
    voiceCategory: 'sword',
    flavor:
      '喪われた同胞の痛哭が、刃をより深く、より凄惨な紅に染め上げる。残されたのは、血の代償を求める果てなき渇望のみ。',
  },
  {
    id: 'wurm',
    name: '文明喰らい',
    rarity: 4,
    power: 8,
    skills: [
      { id: 'takeover' },
      { id: 'berserk', value: 4 },
      { id: 'cleave' },
      { id: 'retaliate', value: 3 },
    ],
    voiceCategory: 'monster',
    flavor:
      '砂海に栄華を誇った黄金の都は、一夜にして地図から消え去った。豊穣のオアシスも、天を突く尖塔も、今はすべてこの大蠕虫の腹の中。底なしの流砂だけが、かつての繁栄を静かに弔っている。',
  },
  {
    id: 'valkyrie',
    name: '焦熱の戦乙女',
    rarity: 4,
    power: 3,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'double_strike' },
      { id: 'stealth', value: 1 },
      { id: 'quick' },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '炎のオーラを纏い、強襲を掛ける戦乙女。一瞬の瞬きすら許さない神速の連撃が、標的を瞬く間に灰燼に帰す。',
  },
  {
    id: 'hellkite',
    name: 'ヘルカイトの君主',
    rarity: 4,
    power: 8,
    skills: [
      { id: 'legendary' },
      { id: 'apex' },
      { id: 'berserk', value: 4 },
      { id: 'spread', value: 4 },
    ],
    voiceCategory: 'dragon',
    flavor:
      '「黒き影が空を覆う時、古き王国は灰となる」――親が子に語り継ぐ、ただの古き御伽話。だがある日、空は真に黒く染まり、伝説は業火と共に舞い降りた。',
  },
  {
    id: 'darkpaladin',
    name: '闇の聖騎士',
    rarity: 4,
    power: 5,
    skill: 'substitute',
    voiceCategory: 'sword',
    flavor:
      '「勝利のためなら、味方の命すらも捨て石にすぎん。」黒鉄の鎧に身を包んだ冷徹な騎士。',
  },
  {
    id: 'elite',
    name: 'ギルドの特級剣士',
    rarity: 4,
    power: 4,
    skill: 'adversity',
    skillValue: 2,
    voiceCategory: 'human_female_normal',
    flavor:
      '優雅な気品を湛える剣士。敵に包囲される逆境下でこそ、研ぎ澄まされた鋭い剣技を披露する。',
  },
  {
    id: 'guildmaster',
    name: 'ギルドの支配人',
    rarity: 4,
    power: 1,
    skills: [
      { id: 'draw', value: 1 },
      { id: 'choice', value: 1 },
    ],
    choices: [{ id: 'support', value: 3 }, { id: 'deadly' }],
    voiceCategory: 'human_male_normal',
    flavor:
      'その指先ひとつで街の経済が回り、裏社会の命運が決まる。表と裏、どちらの顔を見せるかは彼の気分次第だ。',
  },
  {
    id: 'duelist',
    name: '血濡れの決闘者',
    rarity: 4,
    power: 4,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 2 },
      { id: 'hero', value: 2 },
      { id: 'adversity', value: 2 },
    ],
    voiceCategory: 'human_male_warrior',
    flavor:
      '無慈悲に命を刈り取る殺戮者。肉体が切り刻まれようと、血の海で最後まで立ち尽くし標的を屠る。',
  },
  {
    id: 'starfish',
    name: '旧世界からの使者',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'morph', value: 2 },
    ],
    voiceCategory: 'monster',
    flavor:
      '人類の歴史より遥か昔、深き水底から遣わされた奇妙な先触れ。彼らが地上に姿を現すとき、それは世界に大いなる変革の刻が訪れたことを意味している。',
  },
  {
    id: 'trapezohedron',
    name: 'トラペゾヘドロン',
    rarity: 4,
    power: 1,
    skill: 'invite',
    voiceCategory: 'book',
    flavor:
      '異なる次元への扉を開く多面体。深淵を覗き込むとき、そこから恐るべきものが呼び出される。',
  },
  {
    id: 'shoggoth',
    name: '蠢く泥塊',
    rarity: 4,
    power: 2,
    skill: 'double_power',
    voiceCategory: 'monster',
    flavor:
      '黒き粘液で構成された不定形の怪物。増殖と分裂を繰り返し、際限なく膨張していく。',
  },
  {
    id: 'cthulhu',
    name: '大いなる支配者',
    rarity: 4,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'takeover' },
      { id: 'choice', value: 2 },
    ],
    choices: [
      { id: 'double_power' },
      { id: 'double_power' },
      { id: 'clone', value: 1 },
      { id: 'clone', value: 1 },
    ],
    voiceCategory: 'monster',
    flavor:
      'その姿を視認した瞬間、あらゆる物理法則は崩壊を始める。ただ空に浮かぶだけで周囲の空間を歪め、無限の絶望を増殖させていく絶対の主。',
  },
  {
    id: 'piper',
    name: 'サテュロスの笛吹き',
    rarity: 4,
    power: 3,
    skill: 'explore',
    skillValue: 4,
    voiceCategory: 'human_male_ikemen',
    flavor:
      '陽気な笛の音が響く時、木々は枝を揺らし、密やかな抜け道を旅人に提示する。',
  },
  {
    id: 'wish',
    name: '森の願い',
    rarity: 4,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'summon', value: 5, summonId: 'token_ent' },
      { id: 'explore', value: 10 },
    ],
    voiceCategory: 'magic',
    flavor:
      '大地の脈動と古樹の祈りが交わるとき、森は自らの意志をもって覚醒する。巨木を立ち上がらせ、遥かなる緑の領域を押し広げていく。',
  },
  {
    id: 'cuchulainn',
    name: '追憶の魔槍使い',
    rarity: 4,
    power: 3,
    skills: [
      { id: 'loss', value: 5 },
      { id: 'snipe', value: 8 },
      { id: 'pierce' },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '色褪せた記憶の中にあっても、呪われし槍の切っ先は恐ろしいほどに冴え渡る。因果を捻じ曲げ、ただ死のみを約束する魔の刃。',
  },
  {
    id: 'elfking',
    name: 'エルフの王',
    rarity: 4,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'call', value: 4 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '千年の時を統べるエルフの王。彼の声が響く時、森の全てが呼応し、侵略者をなぎ払う軍勢と化す。',
  },
  {
    id: 'father',
    name: '銀弾の神父',
    rarity: 4,
    power: 2,
    skills: [{ id: 'choice', value: 2 }],
    choices: [
      { id: 'snipe', value: 2 },
      { id: 'snipe', value: 2 },
      { id: 'artillery', value: 1 },
      { id: 'artillery', value: 1 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '聖なる銀弾を込めた銃を携える神父。彼の祈りは邪悪を穿ち、その弾丸は罪人を浄化する。',
  },
  {
    id: 'punishment',
    name: '神罰',
    rarity: 4,
    power: 0,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'artillery', value: 3 },
      { id: 'spread', value: 4 },
    ],
    voiceCategory: 'magic',
    flavor: '天より降り注ぐ理不尽なる裁き。神の砲撃は敵陣を焼き尽くす。',
  },
  {
    id: 'spirit',
    name: 'ブラザー・オブ・オース',
    rarity: 4,
    power: 5,
    skills: [{ id: 'possession' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      'かつて背中を預け合った戦友との誓いが、彼を不屈の精霊へと変えた。その魂は今もなお、忠義という名の炎で燃え続けている。',
  },
  {
    id: 'goddess',
    name: '勝利の女神',
    rarity: 4,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'possession' }, { id: 'absorb' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '戦場を舞う美しき女神。彼女が微笑む時、勝利の天秤は静かに傾き、受けるべき傷は運命の導きによって癒やしへと変わる。',
  },
  {
    id: 'dragonzombie',
    name: '継ぎ接ぎの擬竜',
    rarity: 4,
    power: 8,
    skill: 'decay',
    voiceCategory: 'undead',
    flavor:
      '竜の威容を模して、数多の獣の屍を縫い合わせた歪な肉塊。その巨大な体躯は維持するだけで崩壊を始め、本来の力を削ぎ落としていく。',
  },
  {
    id: 'grimreaper',
    name: '死神',
    rarity: 4,
    power: 6,
    skills: [{ id: 'takeover' }, { id: 'cleave' }, { id: 'deadly' }],
    voiceCategory: 'undead',
    flavor:
      '音もなく現れ、音もなく命を刈り取る。その大鎌が一閃する時、生きとし生ける者は等しく無へと還る。',
  },
  {
    id: 'puppeteer',
    name: '放浪傀儡師',
    rarity: 4,
    power: 2,
    skill: 'puppet',
    skillValue: 5,
    voiceCategory: 'human_male_trickstar',
    flavor:
      '煙渦巻く戦場を渡り歩く、異色の傭兵。戦死者の無念を糸に宿して戦力として再利用するその手腕は、極めて非情で効率的である。',
  },
  {
    id: 'doll',
    name: '人形館の主',
    rarity: 4,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'loss', value: 5 },
      { id: 'bind', value: 2 },
      { id: 'puppet', value: 9 },
    ],
    voiceCategory: 'human_female_cute',
    flavor:
      '洋館の奥深くに座す、精巧極まる少女の人形。自らの遊び場に足を踏み入れた客人を、彼女は温かくもてなし、そして二度と外の世界へ帰ることのない調度品へと変えていく。',
  },
  {
    id: 'student',
    name: '勤勉な留学生',
    rarity: 4,
    power: 3,
    skill: 'chant',
    skillValue: 0,
    voiceCategory: 'beast',
    flavor:
      '故郷を遠く離れ、未知の魔法を学ぶために魔導アカデミーの門を叩いた若き獣人。使い慣れない言語の魔導書と格闘しながら、ひたむきに詠唱の練習を続けている。',
  },
  {
    id: 'archmage',
    name: '異端のアークメイジ',
    rarity: 4,
    power: 4,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'chant', value: 3 },
    ],
    voiceCategory: 'human_male_old',
    flavor:
      '歴戦の戦士のごとき風格を漂わせる、規格外の魔導士。星を砕くほどの極大魔法を紡ぎ出すためならば、己の血肉すらも代償として捧げる覚悟を持っている。',
  },
  {
    id: 'philosopher',
    name: '賢者の石',
    rarity: 4,
    power: 0,
    skills: [{ id: 'convert', value: 1 }, { id: 'leap' }],
    voiceCategory: 'magic',
    flavor:
      '真理を探求する者たちが生涯を捧げ、ついに到達した至高の結晶。その深紅の輝きは、自らの存在を代償とすることで次元すら越える奇跡を顕現させる。',
  },
  {
    id: 'gorgon',
    name: '魔眼の勇者',
    rarity: 4,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'petrify' }, { id: 'double_strike' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '蛇の髪を持つ美しき戦乙女。その一瞥を受けた者は石と化し、剣の一閃は必殺の一撃となる。',
  },
  {
    id: 'kunoichi',
    name: '双牙衆の刺客',
    rarity: 4,
    power: 3,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'sacrifice', value: 1 },
      { id: 'arm_self' },
      { id: 'summon', value: 3, summonId: 'token_whitewolf' },
    ],
    voiceCategory: 'human_female_normal',
    flavor:
      '己の血と痛みを代償に、獣を喚び出す双牙衆の忍者。静寂を裂く刃と鋭い牙が、連携して標的を確実に仕留める。',
  },
  {
    id: 'benkei',
    name: '刀狩りの豪傑',
    rarity: 4,
    power: 4,
    skills: [{ id: 'arm_self' }, { id: 'pierce' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '敗者の武具を奪い、己の力へと変える。その桁外れの剛腕から繰り出される一撃は、いかなる盾をも容易く貫く。',
  },
  {
    id: 'ippondatara',
    name: '異形の刀鍛冶',
    rarity: 4,
    power: 4,
    skill: 'forge',
    voiceCategory: 'sword',
    flavor:
      '深夜の山奥で槌音を響かせる、一つ目一本足の怪異。その身を炎に焦がしながら打たれた魔剣は、持ち主の魂をも喰らうという。',
  },
  {
    id: 'seimei',
    name: '天眼の陰陽師',
    rarity: 4,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'seal', value: 1 },
      { id: 'bind', value: 1 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '森羅万象を見通すその眼差しに、死角はない。涼やかな指先が印を結べば、標的は抗う間もなく縛に就く。',
  },
  {
    id: 'monolith',
    name: '叡智のモノリス',
    rarity: 4,
    power: 8,
    skills: [{ id: 'defender' }, { id: 'amplify' }],
    voiceCategory: 'stone',
    flavor:
      '星の瞬きよりも永く、その黒き石柱は荒野の静寂の中に佇んでいる。触れる者に古代の知識を授ける。',
  },
  {
    id: 'highwayman',
    name: '裏切りの相棒',
    rarity: 4,
    power: 4,
    skill: 'force',
    skillValue: 1,
    choices: [
      { id: 'artillery', value: 2 },
      { id: 'morph', value: 2 },
    ],
    voiceCategory: 'human_male_normal',
    flavor:
      '幾重もの危険な罠を共にくぐり抜けた探検の友は、最奥で目当ての財宝を手にした瞬間に冷酷な本性を現す。',
  },
  {
    id: 'sphinx',
    name: '難題の問い手',
    rarity: 4,
    power: 4,
    skill: 'force',
    skillValue: 1,
    choices: [
      { id: 'burial', value: 4 },
      { id: 'lone_wolf', value: 2 },
      { id: 'spread', value: 3 },
    ],
    voiceCategory: 'human_male_old',
    flavor:
      '砂塵の彼方に忽然と姿を現し、神域へと足を踏み入れた者の前に立ち塞がる黄金の獣。その難解な問いに対して真理を導き出せぬ者は、容赦なく熱砂の底へと永遠に葬り去られる。',
  },
  {
    id: 'cleopatra',
    name: '最後の女王',
    rarity: 4,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [{ id: 'burial', value: 5 }, { id: 'cull' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '傾きゆく帝国の命運を、その気高き美貌と底知れぬ知略によって支え続けた統治者。彼女が玉座で下した最後の冷徹な決断は、かつての栄華と共に歴史の闇へと消えていった。',
  },
  {
    id: 'baldanders',
    name: 'バルトアンデルス',
    rarity: 4,
    power: 0,
    skill: 'metamorph',
    voiceCategory: 'stone',
    flavor:
      '変幻自在の魔力を持つ怪人。その姿を捉えることはできず、あらゆる存在へと形を変える。',
  },
  {
    id: 'shuffler',
    name: 'シャッフラー',
    rarity: 4,
    power: 5,
    skill: 'shuffle',
    voiceCategory: 'human_male_trickstar',
    flavor:
      'その奇怪な手品師がカードを切り混ぜる時、確かなはずの未来さえも白紙に戻る。',
  },
  {
    id: 'invader',
    name: '彼方からの侵略者',
    rarity: 4,
    power: 0,
    skill: 'invade',
    voiceCategory: 'beast',
    flavor:
      '星の海を渡り、あらゆる次元を喰らい尽くす。彼らにとって、この世界もただの餌場に過ぎない。',
  },
  {
    id: 'dicejuggler',
    name: 'ダイスジャグラー',
    rarity: 4,
    power: 2,
    skill: 'fate',
    voiceCategory: 'human_male_trickstar',
    flavor: '賽は投げられた。君の幸運を祈ろう……できれば、私自身にもね。',
  },
  {
    id: 'homunculus',
    name: 'ホムンクルスの実験体',
    power: 0,
    skill: 'replicate',
    rarity: 4,
    voiceCategory: 'stone',
    flavor:
      '欠落した半身を埋めるため、未完成のホムンクルスは強者の力を模倣する。鏡に映る己が完全な存在であると信じて。',
  },
  {
    id: 'bell',
    name: '葬送の鐘',
    rarity: 4,
    power: 0,
    skill: 'decree',
    voiceCategory: 'magic',
    flavor:
      '鳴り響く鐘の音は、終焉の宣告。その音を聞いた者に、逃れる術はない。',
  },
  // {
  //   id: 'scarecrow',
  //   name: '呪いの案山子',
  //   power: 1,
  //   skills: [{ id: 'convert', value: 1 }, { id: 'reflect' }],
  //   rarity: 4,
  //   voiceCategory: 'undead',
  //   flavor:
  //     '燃やそうとした者は黒焦げになり、切り刻もうとした者は四肢を失った。案山子は何事もなかったかのように、今日も畑に立っている。',
  // },
  // トークンカード
  {
    id: 'token_knight',
    name: '騎士',
    rarity: 1,
    power: 2,
    isToken: true,
    skill: 'none',
    voiceCategory: 'sword',
    flavor: '号令で召喚された騎士。',
  },
  {
    id: 'token_dragon',
    name: 'ドラゴン',
    rarity: 1,
    power: 6,
    isToken: true,
    skill: 'none',
    voiceCategory: 'dragon',
    flavor: '空の支配者。',
  },
  {
    id: 'token_ignis',
    name: 'イグニス',
    rarity: 1,
    power: 7,
    isToken: true,
    skill: 'legendary',
    flavor: '降臨した竜族の姫。',
  },
  {
    id: 'token_satan',
    name: '魔王の化身',
    rarity: 1,
    power: 10,
    isToken: true,
    skill: 'none',
    flavor: '魔王サタンの強大な化身。',
  },
  {
    id: 'token_clone',
    name: '分身',
    rarity: 1,
    power: 1,
    isToken: true,
    skill: 'none',
    flavor: '本体から生み出された分身。',
  },
  {
    id: 'token_reinforce',
    name: '増援',
    rarity: 1,
    power: 4,
    isToken: true,
    skill: 'none',
    flavor: '呼び声に応え、現れた仲間。',
  },
  {
    id: 'legs',
    name: '蛸足',
    rarity: 1,
    power: 2,
    isToken: true,
    skill: 'none',
    flavor: '切り離されてもなお蠢き続ける蛸の足。',
  },
  {
    id: 'token_void',
    name: '虚空',
    rarity: 1,
    power: 0,
    isToken: true,
    skill: 'none',
    voiceCategory: 'stone',
    flavor:
      '形なき虚無の欠片。それは何も生み出さず、ただそこにあるだけの空虚。',
  },
  {
    id: 'token_ent',
    name: 'エント',
    rarity: 1,
    power: 5,
    isToken: true,
    skill: 'none',
    voiceCategory: 'stone',
    flavor:
      '永き眠りから目覚めた大樹の精霊。森を脅かす者には、容赦のない鉄槌が下される。',
  },
  {
    id: 'token_statue',
    name: '石像',
    rarity: 1,
    power: 5,
    isToken: true,
    skills: [{ id: 'defender' }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor: '石化させられた哀れな姿。',
  },
  {
    id: 'token_drone',
    name: 'ドローン',
    rarity: 1,
    power: 1,
    isToken: true,
    skill: 'none',
    voiceCategory: 'machine_new',
    flavor: '小型の索敵無人機。',
  },
  {
    id: 'token_golem',
    name: 'ゴーレム',
    rarity: 1,
    power: 5,
    isToken: true,
    skill: 'none',
    voiceCategory: 'monster',
    flavor: '土と石で構成された自律型の魔法生物。',
  },
  {
    id: 'token_wall',
    name: '防壁',
    rarity: 1,
    power: 1,
    isToken: true,
    skill: 'defender',
    voiceCategory: 'stone',
    flavor: '魔法によって創造された防壁。',
  },
  {
    id: 'token_phoenix',
    name: 'フェニックス',
    rarity: 1,
    power: 6,
    isToken: true,
    skill: 'none',
    voiceCategory: 'bird',
    flavor: '蘇った不死鳥。',
  },
  {
    id: 'token_soul',
    name: '人魂',
    rarity: 1,
    power: 1,
    isToken: true,
    skill: 'none',
    voiceCategory: 'undead',
    flavor: '彷徨う人魂。',
  },
  {
    id: 'token_gearC',
    name: '機神プロメテウス',
    rarity: 1,
    power: 10,
    isToken: true,
    skills: [
      { id: 'spread', value: 3 },
      { id: 'artillery', value: 2 },
      { id: 'immune' },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '天と地が交わり、鋼の機神が目を覚ます。その圧倒的な火力の前では、いかなる装甲も意味を成さない。',
  },
  {
    id: 'token_reinforceddrone',
    name: '強化ドローン',
    rarity: 1,
    power: 5,
    isToken: true,
    skill: 'none',
    skills: [{ id: 'snipe', value: 5 }],
    voiceCategory: 'machine_new',
    flavor: '強化されたドローン。',
  },
  {
    id: 'token_polarbear',
    name: 'ヴォイテク',
    rarity: 1,
    power: 4,
    isToken: true,
    skills: [{ id: 'legendary' }, { id: 'pierce' }],
    voiceCategory: 'beast',
    flavor: 'リナと共に戦う白熊',
  },
  {
    id: 'token_daemon',
    name: 'デーモン',
    rarity: 1,
    power: 7,
    isToken: true,
    skill: 'none',
    voiceCategory: 'devil',
    flavor: '契約により姿を現した悪魔。',
  },
  {
    id: 'token_whitewolf',
    name: '白狼',
    power: 3,
    isToken: true,
    skill: 'none',
    voiceCategory: 'wolf',
    flavor: '忍びの相棒',
  },
  {
    id: 'token_skeleton',
    name: '組み直されたスケルトン',
    rarity: 1,
    power: 3,
    isToken: true,
    skill: 'none',
    voiceCategory: 'undead',
    flavor: '再生したスケルトン',
  },
];
