/**
 * Mini Card Battle - Card Master Data
 */
export const CARD_MASTER = [
    { id: 'golem', name: '大理石のゴーレム', power: 5, skill: 'none', rarity: 1, voiceCategory: 'rock', flavor: '魔法によって生命を吹き込まれた大理石の彫像。美しさと硬固さを兼ね備えている。' },
    { id: 'clone', name: '鏡の戦士', power: 2, skill: 'clone', skillValue: 1, rarity: 1, voiceCategory: 'sword', flavor: '妖精の鏡から這い出した実体のない騎士。本体と寸分違わぬ動きで幻惑する。' },
    { id: 'sniper', name: '森の射手', power: 2, skill: 'snipe', skillValue: 4, rarity: 1, voiceCategory: 'human_male_ikemen', flavor: '静寂に包まれた深い森を守るエルフの狩人。その矢は木の葉の間を縫い、目標を違わず射抜く。' },
    { id: 'diviner', name: '星詠みの占術士', power: 4, skill: 'draw', skillValue: 2, rarity: 1, voiceCategory: 'human_female_ikemen', flavor: '天球の運行を読み解き、運命の糸を紡ぎ直す導き手。' },
    { id: 'dinosaur', name: '古代の大蜥蜴', power: 8, skill: 'takeover', rarity: 1, voiceCategory: 'lizard', flavor: '古代の息吹を宿す巨大な爬虫類。その巨体を現すには、相応の代償が必要となる。' },
    { id: 'cheetah', name: '稲妻の猟豹', power: 2, skill: 'quick', rarity: 1, voiceCategory: 'beast', flavor: '稲妻を纏って戦場を駆ける最速の野獣。その爪が空気を切り裂く。' },
    { id: 'scorpion', name: '黒サソリ', power: 3, skill: 'deadly', rarity: 1, voiceCategory: 'insect', flavor: '夜の砂漠に潜む漆黒の巨蠍。その尾から放たれる猛毒は対象を一瞬で絶命させる。' },
    { id: 'airship', name: 'セレスタリアのサルベージ船', power: 4, rarity: 1, skill: 'salvage', voiceCategory: 'machine_old', flavor: '空飛ぶ巨大な飛行船。その甲板には、忘れ去られた過去の遺物が山のように積まれている。' },
    { id: 'dancer', name: '魅惑の踊り子', power: 2, rarity: 1, skills: [{ id: 'bind', value: 1 }, { id: 'deadly' }], voiceCategory: 'human_female_ikemen', flavor: '華麗な舞に目を奪われた瞬間、短剣が喉元に届く。彼女の微笑みは、甘美な死への誘いである。' },
    { id: 'lizardman', name: '竜人族の斥候', power: 4, skill: 'reinforce', skillValue: 2, rarity: 1, voiceCategory: 'lizard', flavor: '湿地に潜み、獲物をつけ狙う追跡者。仲間を呼ぶその甲高い鳴き声は、無数の影が迫る前兆である。' },
    { id: 'ninja', name: '忍者', power: 3, skill: 'stealth', skillValue: 1, rarity: 1, voiceCategory: 'human_male_normal', flavor: '影に潜み、音もなく標的に近づく工作員。その姿を捉えることは困難である。' },
    { id: 'crenellatedwall', name: '民兵団の射手', power: 5, skills: [{ id: 'spread', value: 1 }, { id: 'defender' }], rarity: 1, voiceCategory: 'human_male_normal', flavor: '故郷を守るために立ち上がった志願兵たち。門の内側から放たれる矢は、侵略者を決して逃さない。' },
    { id: 'chameleon', name: '迷彩カメレオン', power: 3, skill: 'immune', rarity: 1, voiceCategory: 'lizard', flavor: '周囲の景色に完璧に溶け込む擬態能力。じっと潜んだその姿は、どんな熟練の狩人にも見抜くことはできない。' },
    { id: 'charger', name: '虹ハチドリ', power: 1, skill: 'charge', skillValue: 1, rarity: 1, voiceCategory: 'bird', flavor: '七色の翼を持つ小さな鳥。その羽ばたきは見る者に活力を与える。' },
    { id: 'cleric', name: '見習い修道女', power: 3, skill: 'heal', skillValue: 2, rarity: 1, voiceCategory: 'human_female_young', flavor: '救済を志し修業に励む乙女。未熟ながらもその祈りは傷ついた心を癒やす。' },
    { id: 'wall', name: '城壁', power: 10, skill: 'defender', rarity: 1, voiceCategory: 'rock', flavor: '幾多の戦火を耐え抜いた鉄壁の防塁。王国の平和を守り続ける沈黙の守護者。' },
    { id: 'necromancer', name: 'ヴィス・ガルドの背教者', power: 2, skill: 'resurrect', skillValue: 4, rarity: 1, voiceCategory: 'human_female_ikemen', flavor: '『さあ、起きなさい…永遠なる奉仕の時間が始まるわ』。真紅の瞳が見つめる先、死者は再び立ち上がる。' },
    { id: 'zombie', name: '解き放たれた囚人', power: 1, skills: [{ id: 'clone', value: 2 }, { id: 'growth', value: -1 }], rarity: 1, voiceCategory: 'undead', flavor: 'かつて地下牢に繋がれていた者たちの成れの果て。その怨念は果てることなく、仲間を呼び寄せながら朽ちてゆく。' },
    { id: 'goat', name: 'スケープゴート', power: 2, rarity: 1, skills: [{ id: 'sacrifice', value: 3 }, { id: 'charge', value: 2 }], voiceCategory: 'monster', flavor: '不吉な儀式の供物として捧げられる山羊。その命が尽きる時、主には強大な魔力が還元される。' },
    { id: 'devil', name: '地獄の放火魔', power: 2, skills: [{ id: 'spread', value: 3 }, { id: 'explode', value: 3 }], rarity: 1, voiceCategory: 'devil', flavor: '背中のタンクには地獄の業火が詰まっている。初めて武器を与えられた小悪魔は、その焦熱を振り撒くことに至上の喜びを感じていた。' },
    { id: 'titan', name: '旧式タイタン', power: 8, skill: 'growth', skillValue: -2, rarity: 2, voiceCategory: 'machine_old', flavor: '古代文明の造兵兵器。旧式ながらもその重厚な装甲は今なお健在である。' },
    { id: 'mantis', name: '旧式マンティス', power: 3, skills: [{ id: 'quick' }, { id: 'growth', value: -2 }], rarity: 2, voiceCategory: 'machine_old', flavor: '旧式の巨大なカマキリのロボット。鋭い鎌で獲物を伏せるが、過負荷による出力低下が激しい。' },
    { id: 'bigai', name: 'サイクロプス Mk-II', power: 3, skills: [{ id: 'charge', value: -1 }, { id: 'snipe', value: 5 }], rarity: 2, voiceCategory: 'machine_new', flavor: '単眼の狙撃特化型自律ユニット。一撃必殺の精度を誇る。' },
    { id: 'mechanic', name: 'ダクト街の技師', power: 4, skill: 'summon', skillValue: 1, rarity: 2, voiceCategory: 'human_female_ikemen', flavor: '廃れた近未来都市で生きる腕利きのメカニック。彼女の作るドローンはどんな狭い隙間にも潜り込む。' },
    { id: 'babydragon', name: 'ドラゴンの雛', power: 2, skill: 'growth', skillValue: 3, rarity: 2, voiceCategory: 'lizard', flavor: 'まだ小さなドラゴンの幼体。秘めたる魔力は無限の可能性を感じさせる。' },
    { id: 'dragonewt', name: '竜人族の騎兵', power: 4, skills: [{ id: 'pierce' }, { id: 'snipe', value: 2 }], rarity: 2, voiceCategory: 'horse', flavor: '竜人族の騎兵。翼は無いが、戦場を駆け抜け敵を貫き、遠方の獲物も逃さない。' },
    { id: 'berserker', name: '狂戦士', power: 7, skill: 'berserk', skillValue: 2, rarity: 2, voiceCategory: 'giant', flavor: '破壊の衝動に魂を売った禁忌の戦士。痛みすら悦びとして斧を振り回す。' },
    { id: 'wyvern', name: '群れのワイヴァーン', power: 7, skills: [{ id: 'takeover' }, { id: 'reinforce', value: 1 }], rarity: 2, voiceCategory: 'dragon', flavor: '空を滑る緑の影は、必ず二つ。一方を殺したと安堵するなら、それは間違いだ。その血の匂いは、雲の彼方から狂乱のもう一方を呼び寄せる。' },
    { id: 'commander', name: '前線の司令官', power: 3, skill: 'support', skillValue: 2, rarity: 2, voiceCategory: 'human_male_warrior', flavor: '最前線で兵を鼓舞し続ける老将。彼の掲げる軍旗は兵士たちの士気を極限まで高める。' },
    { id: 'hero', name: '若き勇士', power: 2, skill: 'hero', skillValue: 2, voiceCategory: 'human_female_young', rarity: 2, flavor: '安物の胸当てに、誇りと希望だけを詰め込んだ新米訓練兵。その不器用な剣筋も、いつか伝説へと連なる。' }, { id: 'lightpaladin', name: '光の聖騎士', power: 5, skill: 'guardian', rarity: 2, voiceCategory: 'human_male_ikemen', flavor: '「我が盾は、共に戦う友のためにある。」気高き精神を宿した聖なる騎士。' },
    { id: 'darkpaladin', name: '闇の聖騎士', power: 5, skills: [{ id: 'sacrifice', value: 2 }, { id: 'deadly' }], rarity: 2, voiceCategory: 'sword', flavor: '「勝利のためなら、この命すらも捨て石にすぎん。」黒鉄の鎧に身を包んだ冷徹な騎士。' },
    { id: 'bard', name: '森の歌うたい', power: 1, skills: [{ id: 'support', value: 2 }, { id: 'heal', value: 2 }], rarity: 2, voiceCategory: 'human_female_ikemen', flavor: 'ウクレレを奏でる彼を、森の動物たちは親しみを持って「先生」と呼ぶ。その歌声は傷ついた心も体も癒やす。' },
    { id: 'spider', name: 'スパイダー', power: 4, skill: 'bind', skillValue: 1, rarity: 2, voiceCategory: 'insect', flavor: '暗闇に潜み、粘着質の糸を紡ぐ毒蜘蛛。獲物の自由を奪い、死の抱擁へと誘う。' },
    { id: 'mage', name: '学院の雷撃魔導士', power: 2, skill: 'spread', skillValue: 2, rarity: 2, voiceCategory: 'human_female_ikemen', flavor: '魔導アカデミーの雷撃魔導士。周囲の魔力を吸収し、雷撃を放つ。' },
    { id: 'bird', name: '新緑の導き鳥', power: 1, skill: 'split', skillValue: 5, rarity: 2, voiceCategory: 'bird', flavor: 'その小さなさえずりが途絶えたとき、森の静寂は怒号へと変わる。' },
    { id: 'tortoise', name: '鉄亀', power: 4, skill: 'sturdy', rarity: 2, voiceCategory: 'insect', flavor: '鉱石を食べて成長し、鋼鉄の如き硬度を得た霊亀。物理的な衝撃をほぼ無効化する。' },
    { id: 'prince', name: '星の王子', power: 1, skill: 'stealth', skillValue: 2, rarity: 2, voiceCategory: 'lizard', voiceCategory: 'monster', flavor: '黒き触手に抱かれた幼き王は、遥か宇宙の深淵から、我らの空へと帰還しつつある。' },
    { id: 'copy', name: '虚無の目覚め', power: 4, skill: 'morph', skillValue: 1, rarity: 2, voiceCategory: 'insect', voiceCategory: 'monster', flavor: 'その巨大な眼差しに見つめられた時、存在の意味は虚空へと霧散し、ただ静寂のみが残される。' },
    { id: 'shark', name: 'メガロドン', power: 6, skills: [{ id: 'stealth', value: 1 }, { id: 'standby', value: 1 }], rarity: 2, voiceCategory: 'monster', flavor: '深き蒼から突如として現れる規格外の巨体。その顎が海面を割る時、逃げる術は既に残されていない。' },
    { id: 'barrier', name: '聖光の護り手', power: 4, skills: [{ id: 'guardian' }, { id: 'support', value: 1 }], voiceCategory: 'human_female_ikemen', rarity: 2, flavor: '清浄な心で奇跡を呼ぶ賢者。その盾は、不浄なるものを一切寄せ付けない。' },
    { id: 'incinerator', name: 'インシネレーター', power: 3, skill: 'artillery', skillValue: 1, rarity: 2, voiceCategory: 'human_female_ikemen', flavor: '異端の書物、教義に背く者を炎で浄化する実働部隊。マスク越しの彼女の瞳に、慈悲の色はない。' },
    { id: 'charity', name: '慈愛', power: 3, skills: [{ id: 'heal', value: 4 }, { id: 'defender' }, { id: 'sturdy' }], rarity: 2, voiceCategory: 'rock', flavor: '古より伝わる小さな彫像。周囲に清らかな癒しと絶対の護りをもたらす。' },
    { id: 'doom', name: '破滅', power: 3, skills: [{ id: 'spread', value: 6 }, { id: 'defender' }, { id: 'takeover' }], rarity: 2, voiceCategory: 'rock', flavor: '古より伝わる小さな彫像。周囲に底知れぬ絶望と絶大な破滅をもたらす' },
    { id: 'plaguedoctor', name: '烏羽の医師', power: 2, rarity: 2, skills: [{ id: 'choice' }], choices: [{ id: 'heal', value: 2 }, { id: 'toxic', value: 2 }], voiceCategory: 'human_female_ikemen', flavor: '彼女の処方箋は、明日を繋ぐ特効薬か、あるいは安息へと誘う安楽死の劇薬か' },
    { id: 'shade', name: '墓の亡霊', power: 4, skill: 'soul_bind', skillValue: 2, rarity: 2, voiceCategory: 'undead', flavor: '古い墓地に漂う無念の霧。生者の温もりを嫌い、その魂を冷たい死の淵へと引き摺り込む。' },
    { id: 'specter', name: '魂の徴税人', power: 4, skills: [{ id: 'pierce' }, { id: 'extort', value: 1 }], rarity: 2, voiceCategory: 'undead', flavor: '慈悲はない。情状酌量もない。冥府の帳簿の帳尻を合わせるため、それは今日も無作為に魂を削り取っていく。' },
    { id: 'franken', name: 'オールドヘイヴンの怪物', power: 8, skill: 'standby', skillValue: 2, rarity: 2, voiceCategory: 'giant', flavor: '見捨てられた街の地下深くに眠る禁断の造物。動き出せば、その怪力で全てを粉砕する。' },
    { id: 'warlock', name: '煉獄の拷問官', power: 4, skills: [{ id: 'sacrifice', value: 4 }, { id: 'berserk', value: 4 }, { id: 'spread', value: 4 }], rarity: 2, voiceCategory: 'undead', flavor: '燃え盛る炎の鞭を振るう魔界の拷問官。その一振りは敵を焼き払い、自らの魂さえも劫火の糧とする。' },
    { id: 'dealer', name: 'デビル・ディーラー', power: 5, skills: [{ id: 'sacrifice', value: 2 }, { id: 'draw', value: 4 }], rarity: 2, flavor: '「さあ、運命を選びな。代償は君の魂で十分だ。」不敵な笑みを浮かべる悪魔の占い師。' },
    { id: 'cyberdragon', name: '試作型ドラグーン', power: 5, skills: [{ id: 'legendary' }, { id: 'spread', value: 3 }, { id: 'charge', value: -3 }], rarity: 3, voiceCategory: 'machine_new', flavor: '試作型の重機動兵器。圧倒的な面制圧力を持つ。' },
    { id: 'cyberman', name: 'ライオット・キーパー', power: 6, skills: [{ id: 'charge', value: -1 }], rarity: 3, voiceCategory: 'machine_new', flavor: '「システム始動……これより排除を開始する。」最新型の暴徒鎮圧用ドロイド。' },
    { id: 'dragon', name: 'ファイア・ドラゴン', power: 6, skills: [{ id: 'legendary' }, { id: 'berserk', value: 2 }, { id: 'spread', value: 2 }], rarity: 3, voiceCategory: 'dragon', flavor: '炎を纏った紅蓮の翼。その咆哮は敵を焼き払い、荒ぶる魔力は周囲をも巻き込む。' },
    { id: 'drifter', name: 'アッシュランドの放浪者', power: 4, rarity: 3, skill: 'double_strike', voiceCategory: 'human_male_ikemen', flavor: '灼熱の砂塵を切り裂く双剣。彼の歩みの後には、切り刻まれた絶望のみが残る。' },
    { id: 'champion', name: 'アリーナのチャンピオン', power: 1, skills: [{ id: 'legendary' }, { id: 'hero', value: 3 }], rarity: 3, voiceCategory: 'human_male_warrior', flavor: '観衆の歓声こそが彼の力。その雄姿は味方を鼓舞し、敵を圧倒する。' },
    { id: 'assassin', name: 'ギルドの暗殺者', power: 1, skills: [{ id: 'deadly' }, { id: 'stealth', value: 1 }, { id: 'quick' }], rarity: 3, voiceCategory: 'human_female_assassin', flavor: '黒い服と2つの短剣を持つ若い女暗殺者。一瞬の隙も逃さず、死の影から獲物を屠る。' },
    { id: 'oldgod', name: '古の神', power: 10, skills: [{ id: 'legendary' }, { id: 'takeover' }, { id: 'pierce' }], rarity: 3, voiceCategory: 'monster', flavor: '深海の深淵より目覚めた、名もなき異形の神。その一撃は魂を貫く。' },
    { id: 'octopus', name: '深海の魔物', power: 4, skill: 'split', skillValue: 2, rarity: 3, voiceCategory: 'monster', flavor: '深海に潜む異形の魔物。全身が筋肉の塊で、足を失ってもすぐに生えてくる。' },
    { id: 'wolf', name: '真夜中の狩人', power: 3, skills: [{ id: 'legendary' }, { id: 'lone_wolf', value: 3 }], rarity: 3, voiceCategory: 'wolf', flavor: '月の光を浴びて強靭な力を得る孤高の戦士。群れを嫌い、独りで獲物を追い詰める。' },
    { id: 'highelf', name: 'ロストレイルの精鋭パトロール', power: 2, skills: [{ id: 'snipe', value: 1 }, { id: 'snipe', value: 1 }, { id: 'snipe', value: 1 }, { id: 'snipe', value: 1 }, { id: 'snipe', value: 1 }], rarity: 3, voiceCategory: 'human_female_ikemen', flavor: '迷いの森を監視する精鋭。その神速の連射は、影すらも逃がさない。' },
    { id: 'empress', name: '蒼穹の審判者', power: 3, skills: [{ id: 'legendary' }, { id: 'heal', value: 3 }, { id: 'snipe', value: 3 }], rarity: 3, voiceCategory: 'human_female_young', flavor: '宇宙の理を掌るオーブを掲げ、全ての魂に等しく審判を下す聖女。' },
    { id: 'fire', name: '浄化の炎', power: 6, skills: [{ id: 'artillery', value: 3 }, { id: 'defender' }, { id: 'guardian' }], rarity: 3, voiceCategory: 'machine_old', flavor: '異端を焼き払う神聖なる十字。その盾は信徒を守り、砲口は敵への裁きを下す。' },
    { id: 'collector', name: 'ヘッドコレクター', power: 1, skills: [{ id: 'legendary' }, { id: 'sacrifice', value: 3 }, { id: 'resurrect', value: 9 }, { id: 'deadly' }], rarity: 3, voiceCategory: 'undead', flavor: '集められた数多の魂が慟哭を上げる。彼の者が通り過ぎた後には、首のない骸だけが残される。' },
    { id: 'vampire', name: '渇きの王', power: 6, skills: [{ id: 'sacrifice', value: 2 }, { id: 'soul_bind', value: 4 }, { id: 'growth', value: -2 }], rarity: 3, voiceCategory: 'undead', flavor: '冷笑を浮かべる夜の支配者. 彼の者に狙われた者は、魂の底まで吸い尽くされる。' },
    { id: 'bahamut', name: '終焉の双頭龍', power: 9, rarity: 3, skills: [{ id: 'legendary' }, { id: 'sacrifice', value: 2 }, { id: 'berserk', value: 2 }, { id: 'double_strike' }], voiceCategory: 'dragon', flavor: '二つの首が天を仰ぎ、終末の咆哮を上げる。その翼が振り下ろされる時、世界は劫火に包まれる。' },
    { id: 'daemon', name: '魔界の尖兵', power: 7, skill: 'sacrifice', skillValue: 3, rarity: 3, voiceCategory: 'devil', flavor: '強固な力と引き換えに契約者の魂を喰らう悪魔の兵士。その渇望は主ですら例外ではない。' },
    { id: 'badwolf', name: '幻影の狼', power: 1, rarity: 3, skills: [{ id: 'legendary' }, { id: 'choice' }], choices: [{ id: 'clone', value: 2 }, { id: 'lone_wolf', value: 2 }], voiceCategory: 'wolf', flavor: '森の深淵に潜む、実体なき銀狼。その姿を見た者は、一頭の獲物を追うつもりが、いつの間にか群れに囲まれていることに気付くのだ。' },
    { id: 'redhood', name: 'レッドフード', power: 3, rarity: 3, skills: [{ id: 'legendary' }, { id: 'choice' }], choices: [{ id: 'snipe', value: 5 }, { id: 'spread', value: 1 }], voiceCategory: 'human_female_ikemen', flavor: '赤い頭巾に隠された鋭い眼光。彼女のクロスボウから放たれる矢は、森の静寂を破ることなく標的の心臓を射抜く。' },
    { id: 'queen', name: '嫉妬の女王', power: 4, rarity: 3, skills: [{ id: 'legendary' }, { id: 'choice' }], choices: [{ id: 'draw', value: 3 }, { id: 'deadly' }], voiceCategory: 'human_female_ikemen', flavor: '”世界で一番美しいのは誰？”——その問いに答える者がいなくなるまで、ただ愚か者を狩り尽くすのみ。' },
    { id: 'snowwhite', name: 'スノウホワイト', power: 5, rarity: 3, skills: [{ id: 'legendary' }, { id: 'immune' }], voiceCategory: 'human_female_assassin', flavor: '”鏡よ鏡”。いつから私が、毒を盛られて黙っているようなお姫様だと錯覚していた？純白の鎧は復讐の誓い。' },
    { id: 'whiterider', name: '征服の使徒', power: 6, rarity: 4, skills: [{ id: 'contract', value: 4 }, { id: 'snipe', value: 8 }, { id: 'guardian' }], voiceCategory: 'horse', flavor: '第一の封印が解かれし時、白馬に乗れる者が現る。彼は征服の上に更なる征服を重ねんとし、その矢は逃れ得ぬ運命を射抜く。' },
    { id: 'redrider', name: '戦争の使徒', power: 4, rarity: 4, skills: [{ id: 'contract', value: 4 }, { id: 'quick' }], voiceCategory: 'horse', flavor: '第二の封印。火の如き赤き馬に乗れる者、地上から平和を奪い去る。その大剣が振るわれる時、終わりなき争いの火蓋が切って落とされる。' },
    { id: 'blackrider', name: '飢餓の使徒', power: 5, rarity: 4, skills: [{ id: 'contract', value: 4 }, { id: 'morph', value: 2 }, { id: 'deadly' }], voiceCategory: 'horse', flavor: '第三の封印。黒き馬に乗れる者が手にする天秤は、命の価値を量り、世界を等しく飢えと欠乏に陥れる。' },
    { id: 'palerider', name: '死の使徒', power: 4, rarity: 4, skills: [{ id: 'contract', value: 4 }, { id: 'clone', value: 1 }], voiceCategory: 'horse', flavor: '第四の封印。蒼褪めた馬に乗れる者の名は「死」。その後には黄泉が従い、生きとし生けるもの全てを静寂なる無へと誘う。' },
    { id: 'baldanders', name: 'バルトアンデルス', power: 0, skill: 'metamorph', rarity: 4, voiceCategory: 'rock', flavor: '変幻自在の魔力を持つ怪人。その姿を捉えることはできず、あらゆる存在へと形を変える。' },
    { id: 'shuffler', name: 'シャッフラー', power: 5, skill: 'shuffle', rarity: 4, voiceCategory: 'human_male_normal', flavor: 'その奇怪な手品師がカードを切り混ぜる時、確かなはずの未来さえも白紙に戻る。' },
    { id: 'dicejuggler', name: 'ダイスジャグラー', rarity: 4, power: 2, skill: 'fate', flavor: '賽は投げられた。君の幸運を祈ろう……できれば、私自身にもね。', voiceCategory: 'human_ikemen' },
    // トークンカード
    { id: 'token_knight', name: '騎士', power: 1, skill: 'none', isToken: true, rarity: 1, voiceCategory: 'sword', flavor: 'セレスティアの号令で召喚された騎士。' },
    { id: 'token_ignis', name: 'イグニス', power: 7, skill: 'none', isToken: true, rarity: 1, flavor: '降臨した竜族の姫。' },
    { id: 'token_satan', name: '魔王の化身', power: 10, skill: 'none', isToken: true, rarity: 1, flavor: '魔王サタンの強大な化身。' },
    { id: 'token_clone', name: '分身', power: 1, skill: 'none', isToken: true, rarity: 1, flavor: '本体から生み出された分身。' },
    { id: 'token_reinforce', name: '増援', power: 4, skill: 'none', isToken: true, rarity: 1, flavor: '呼び声に応え、現れた仲間。' },
    { id: 'legs', name: '蛸足', power: 1, skill: 'none', isToken: true, rarity: 1, flavor: '切り離されてもなお蠢き続ける蛸の足。' },
    { id: 'token_void', name: '虚空', power: 1, skill: 'none', isToken: true, rarity: 1, flavor: '形なき虚無の欠片。それは何も生み出さず、ただそこにあるだけの空虚。' },
    { id: 'token_ent', name: 'エント', power: 5, skill: 'none', isToken: true, rarity: 1, flavor: '永き眠りから目覚めた大樹の精霊。森を脅かす者には、容赦のない鉄槌が下される。' },
    { id: 'token_drone', name: 'ドローン', power: 1, skill: 'none', isToken: true, rarity: 1, voiceCategory: 'machine_new', flavor: '小型の索敵無人機。' }
];
