/**
 * Mini Card Battle - Card Master Data
 */
export const CARD_MASTER = [
  {
    id: 'golem',
    obtain: ['initial'],
    name: '大理石のゴーレム',
    rarity: 1,
    power: 5,
    voiceCategory: 'stone',
    flavor:
      '魔法によって生命を吹き込まれた大理石の彫像。美しさと硬固さを兼ね備えている。',
  },
  {
    id: 'clone',
    obtain: ['initial', 'cthulhu_easy', 'knight_easy'],
    name: '鏡の戦士',
    rarity: 1,
    power: 3,
    skills: [{ id: 'clone', value: 1 }],
    voiceCategory: 'sword',
    flavor:
      '妖精の鏡から這い出した実体のない騎士。本体と寸分違わぬ動きで幻惑する。',
  },
  {
    id: 'sniper',
    obtain: ['initial', 'elf_easy', 'witch_easy'],
    name: '森の射手',
    rarity: 1,
    power: 2,
    skills: [{ id: 'snipe', value: 4 }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '静寂に包まれた深い森を守るエルフの狩人。その矢は木の葉の間を縫い、目標を違わず射抜く。',
  },
  {
    id: 'falcon',
    obtain: ['initial', 'elf_easy', 'priest_easy'],
    name: '急襲する隼',
    rarity: 1,
    power: 3,
    skills: [{ id: 'spread', value: 1 }],
    voiceCategory: 'bird',
    flavor:
      '翼から硬い羽根を矢のように降らせた後、空から急降下して獲物を捉える。',
  },
  {
    id: 'cleric',
    obtain: ['initial', 'cleric_easy', 'witch_easy'],
    name: '見習い修道女',
    rarity: 1,
    power: 3,
    skills: [{ id: 'heal', value: 3 }],
    voiceCategory: 'human_female_cute',
    flavor:
      '救済を志し修業に励む乙女。未熟ながらもその祈りは傷ついた心を癒やす。',
  },
  {
    id: 'diviner',
    obtain: ['initial', 'cthulhu_easy', 'devilhunter_easy'],
    name: '星詠みの占術士',
    rarity: 1,
    power: 4,
    skills: [{ id: 'draw', value: 2 }],
    voiceCategory: 'human_female_cool',
    flavor: '天球の運行を読み解き、運命の糸を紡ぎ直す導き手。',
  },
  {
    id: 'dinosaur',
    obtain: ['initial', 'dragon_easy', 'devilhunter_easy'],
    name: '古代の大蜥蜴',
    rarity: 1,
    power: 8,
    skills: [{ id: 'takeover' }],
    voiceCategory: 'lizard',
    flavor:
      '古代の息吹を宿す巨大な爬虫類。その巨体を現すには、相応の代償が必要となる。',
  },
  {
    id: 'cheetah',
    obtain: ['initial', 'android_easy', 'elf_easy'],
    name: '稲妻の猟豹',
    rarity: 1,
    power: 3,
    skills: [{ id: 'quick' }],
    voiceCategory: 'beast',
    flavor: '稲妻を纏って戦場を駆ける最速の野獣。その爪が空気を切り裂く。',
  },
  {
    id: 'scorpion',
    obtain: ['initial', 'cleric_easy', 'priest_easy'],
    name: '黒サソリ',
    rarity: 1,
    power: 3,
    skills: [{ id: 'deadly' }],
    voiceCategory: 'insect',
    flavor: '漆黒の巨蠍。その尾から放たれる猛毒は対象を一瞬で絶命させる。',
  },
  {
    id: 'mercenary',
    obtain: ['initial', 'dragon_easy', 'knight_easy'],
    name: '傭兵',
    rarity: 1,
    power: 6,
    skills: [{ id: 'convert', value: 1 }],
    voiceCategory: 'human_male_warrior',
    flavor: '命が安い戦場において、彼が信じるのは己の腕と報酬だけである。',
  },
  {
    id: 'wall',
    obtain: ['initial', 'cleric_easy', 'knight_easy'],
    name: '城壁',
    rarity: 1,
    power: 10,
    skills: [{ id: 'defender' }],
    voiceCategory: 'stone',
    flavor:
      '幾多の戦火を耐え抜いた鉄壁の防塁。王国の平和を守り続ける沈黙の守護者。',
  },
  {
    id: 'leech',
    obtain: ['initial', 'witch_easy', 'oni_easy'],
    name: '巨大ヒル',
    rarity: 1,
    power: 4,
    skills: [{ id: 'absorb' }],
    voiceCategory: 'snake',
    flavor:
      '湿った泥濘に潜む貪欲なる顎。犠牲者の血肉をすする不快な音だけが響き渡る。',
  },
  {
    id: 'fighter',
    obtain: ['initial', 'dragon_easy', 'oni_easy'],
    name: 'アリーナの新入り',
    rarity: 1,
    power: 4,
    skills: [{ id: 'growth', value: 1 }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '観衆の喧騒に胸を高鳴らせる、未完の闘士。無骨なセスタスには、頂点を目指す熱意と、己の拳のみで道を切り拓く覚悟が宿っている。',
  },
  {
    id: 'tortoise',
    obtain: ['initial', 'android_easy', 'cthulhu_easy'],
    name: '鉄亀',
    rarity: 1,
    power: 4,
    skills: [{ id: 'sturdy' }],
    voiceCategory: 'insect',
    flavor:
      '鉱石を食べて成長し、鋼鉄の如き硬度を得た霊亀。物理的な衝撃をほぼ無効化する。',
  },
  {
    id: 'spider',
    obtain: ['initial', 'cthulhu_easy', 'devilhunter_easy'],
    name: 'スパイダー',
    rarity: 1,
    power: 4,
    skills: [{ id: 'bind', value: 2 }],
    voiceCategory: 'insect',
    flavor:
      '暗闇に潜み、粘着質の糸を紡ぐ巨大な蜘蛛。獲物の自由を奪い、死の抱擁へと誘う。',
  },
  {
    id: 'airship',
    obtain: ['initial', 'android_easy', 'priest_easy'],
    name: 'マキニアのサルベージ船',
    rarity: 1,
    power: 4,
    skills: [{ id: 'salvage', value: 1 }],
    voiceCategory: 'machine_old',
    flavor:
      '空飛ぶ巨大な飛行船。その甲板には、忘れ去られた過去の遺物が山のように積まれている。',
  },
  {
    id: 'hedgehog',
    obtain: ['initial', 'devilhunter_easy', 'oni_easy'],
    name: '威嚇する針鼠',
    rarity: 1,
    power: 3,
    skills: [{ id: 'intercept', value: 2 }],
    voiceCategory: 'beast',
    flavor:
      'その不機嫌そうな丸いフォルムに騙されて手を伸ばした者は、皆一様に手を血に染めて後悔することになる。',
  },
  {
    id: 'bandit',
    obtain: ['initial', 'elf_easy', 'oni_easy'],
    name: '山賊',
    rarity: 1,
    power: 4,
    skills: [{ id: 'extort', value: 2 }],
    voiceCategory: 'human_male_normal',
    flavor:
      '通りかかる者の富を狙う略奪者。決して優れた戦士ではないが、容赦なく全てを奪い去るため旅人から深く恐れられている。',
  },
  {
    id: 'snake',
    obtain: ['initial', 'witch_easy', 'priest_easy'],
    name: '猛毒コブラ',
    rarity: 1,
    power: 3,
    skills: [{ id: 'toxic', value: 3 }],
    voiceCategory: 'snake',
    flavor:
      '草むらに潜み、獲物を待ち伏せる極めて危険な毒蛇。その牙から注がれる猛毒は、屈強な戦士すらも容易く死に至らしめる。',
  },
  {
    id: 'butcher',
    obtain: ['initial', 'android_easy', 'dragon_easy'],
    name: '大斧の処刑人',
    rarity: 1,
    power: 8,
    skills: [{ id: 'execute' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      'その一撃は全てを終わらせる。あるいは、無辜の民を巻き込む。処刑人は常に選択を迫られる。',
  },
  {
    id: 'crenellatedwall',
    obtain: ['initial', 'cleric_easy', 'knight_easy'],
    name: '民兵団の射手',
    rarity: 1,
    power: 8,
    skills: [{ id: 'defender' }, { id: 'spread', value: 1 }],
    voiceCategory: 'human_male_normal',
    flavor:
      '故郷を守るために立ち上がった志願兵たち。門の内側から放たれる矢は、侵略者を決して逃さない。',
  },
  {
    id: 'fireatronach',
    obtain: ['satan_easy', 'void_easy', 'succubus_easy', 'warlock_easy'],
    name: '炎の精霊',
    rarity: 1,
    power: 3,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'snipe', value: 5 },
    ],
    voiceCategory: 'stone',
    flavor:
      '高濃度の魔力で形成された炎の精霊。揺らめく灼熱の炎は、離れた標的をも的確に捕捉し、圧倒的な熱量で焼き尽くす。',
  },
  {
    id: 'iceatronach',
    obtain: ['satan_easy', 'void_easy', 'succubus_easy', 'warlock_easy'],
    name: '氷の精霊',
    rarity: 1,
    power: 5,
    skills: [{ id: 'growth', value: -1 }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '高濃度の魔力で形成された氷の精霊。絶対零度の冷気を纏い、いかなる衝撃にも揺るがない極寒の盾として君臨する。',
  },
  {
    id: 'windatronach',
    obtain: ['satan_easy', 'void_easy', 'succubus_easy', 'warlock_easy'],
    name: '風の精霊',
    rarity: 1,
    power: 5,
    skills: [{ id: 'move' }, { id: 'brutal', value: 2 }],
    voiceCategory: 'stone',
    flavor:
      '高濃度の魔力で形成された風の精霊。戦場を縦横無尽に駆け巡り、荒れ狂う烈風となって瞬く間に敵陣を圧倒する。',
  },
  {
    id: 'lightningatronach',
    obtain: ['satan_easy', 'void_easy', 'succubus_easy', 'warlock_easy'],
    name: '雷の精霊',
    rarity: 1,
    power: 7,
    skills: [{ id: 'explode', value: 4 }],
    voiceCategory: 'stone',
    flavor:
      '高濃度の魔力で形成された雷の精霊。死の間際に激しい放電を引き起こす。',
  },
  {
    id: 'mantis',
    obtain: ['android_easy', 'android_normal'],
    name: '旧式マンティス',
    rarity: 1,
    power: 4,
    skills: [{ id: 'quick' }, { id: 'growth', value: -2 }],
    voiceCategory: 'machine_old',
    flavor:
      '旧式の巨大なカマキリのロボット。鋭い鎌で獲物を伏せるが、過負荷による出力低下が激しい。',
  },
  {
    id: 'titan',
    obtain: ['android_easy'],
    name: '旧式タイタン',
    rarity: 1,
    power: 8,
    skills: [{ id: 'growth', value: -2 }],
    voiceCategory: 'machine_old',
    flavor:
      '古代文明の造兵兵器。旧式ながらもその重厚な装甲は今なお健在である。',
  },
  {
    id: 'cyberman',
    obtain: ['android_normal'],
    name: 'ライオット・キーパー',
    rarity: 1,
    power: 7,
    skills: [{ id: 'spend', value: 1 }],
    voiceCategory: 'machine_new',
    flavor:
      '「システム始動……これより排除を開始する。」最新型の暴徒鎮圧用アンドロイド。',
  },
  {
    id: 'mechanic',
    obtain: ['android_normal', 'android_hard'],
    name: 'ダクト街の技師',
    rarity: 1,
    power: 4,
    skills: [{ id: 'summon', value: 1, summonId: 'token_drone' }],
    voiceCategory: 'human_female_normal',
    flavor:
      '廃れた近未来都市で生きる腕利きのメカニック。彼女の作るドローンはどんな狭い隙間にも潜り込む。',
  },
  {
    id: 'lizardman',
    obtain: ['dragon_easy'],
    name: '竜人族の斥候',
    rarity: 1,
    power: 4,
    skills: [{ id: 'reinforce', value: 2 }],
    voiceCategory: 'lizard',
    flavor:
      '湿地に潜み、獲物をつけ狙う追跡者。仲間を呼ぶその甲高い鳴き声は、無数の影が迫る前兆である。',
  },
  {
    id: 'goblin',
    obtain: ['dragon_easy', 'dragon_normal'],
    name: 'ゴブリンの司令官',
    rarity: 1,
    power: 6,
    skills: [{ id: 'berserk', value: 2 }],
    voiceCategory: 'giant',
    flavor:
      '彼が前線で指揮を執る時、最も命の危険に晒されるのは敵ではなく、彼のすぐ隣に陣取った者たちである。',
  },
  {
    id: 'twister',
    obtain: ['dragon_normal'],
    name: '竜巻',
    rarity: 1,
    power: 7,
    skills: [{ id: 'defender' }, { id: 'growth', value: 2 }],
    voiceCategory: 'stone',
    flavor:
      '砂漠の熱風が巻き起こす竜巻。砂と岩を巻き込みながら容赦なく荒れ狂い、哀れな旅人たちの行く手を塞ぐ。',
  },
  {
    id: 'dancer',
    obtain: ['dragon_normal', 'dragon_hard'],
    name: '魅惑の踊り子',
    rarity: 1,
    power: 2,
    skills: [{ id: 'bind', value: 1 }, { id: 'deadly' }],
    voiceCategory: 'human_female_sexy',
    flavor:
      '華麗な舞に目を奪われた瞬間、短剣が喉元に届く。彼女の微笑みは、甘美な死への誘いである。',
  },
  {
    id: 'commander',
    obtain: ['knight_easy', 'knight_normal'],
    name: '前線の司令官',
    rarity: 1,
    power: 3,
    skills: [{ id: 'support', value: 2 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '最前線で兵を鼓舞し続ける老将。彼の掲げる軍旗は兵士たちの士気を極限まで高める。',
  },
  {
    id: 'nobleknight',
    obtain: ['knight_easy'],
    name: '従者持ちの騎士',
    rarity: 1,
    power: 3,
    skills: [{ id: 'summon', value: 2, summonId: 'token_knight' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '彼の傍らには常に忠実な影が寄り添う。彼が剣を掲げる時、その影は主を守る盾となり、敵を穿つ刃となる。',
  },
  {
    id: 'lightpaladin',
    obtain: ['knight_normal'],
    name: '光の聖騎士',
    rarity: 1,
    power: 5,
    skills: [{ id: 'guardian' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '「我が盾は、共に戦う友のためにある。」気高き精神を宿した聖なる騎士。',
  },
  {
    id: 'hero',
    obtain: ['knight_normal', 'knight_hard'],
    name: '若き勇士',
    rarity: 1,
    power: 4,
    skills: [{ id: 'hero', value: 2 }],
    voiceCategory: 'human_female_normal',
    flavor:
      '安物の胸当てに、誇りと希望だけを詰め込んだ新米訓練兵。その不器用な剣筋も、いつか伝説へと連なる。',
  },
  {
    id: 'jellyfish',
    obtain: ['cthulhu_easy', 'cthulhu_normal'],
    name: '発光するクラゲ',
    rarity: 1,
    power: 3,
    skills: [{ id: 'bless', value: 1 }],
    voiceCategory: 'monster',
    flavor: '深き暗闇の中で妖しく輝き、触れる者に不思議な活力を与える。',
  },
  {
    id: 'fish',
    obtain: ['cthulhu_easy'],
    name: '魚群の壁',
    rarity: 1,
    power: 6,
    skills: [{ id: 'defender' }, { id: 'clone', value: 1 }],
    voiceCategory: 'sea',
    flavor: '一匹の力は弱いが、無数に集まることで強固な壁となる。',
  },
  {
    id: 'eye',
    obtain: ['cthulhu_normal', 'cthulhu_hard'],
    name: '虚無の目覚め',
    rarity: 1,
    power: 4,
    skills: [{ id: 'morph', value: 1 }],
    voiceCategory: 'monster',
    flavor:
      'その巨大な眼差しに見つめられた時、存在の意味は虚空へと霧散し、ただ静寂のみが残される。',
  },
  {
    id: 'slime',
    obtain: ['cthulhu_normal'],
    name: '這い寄るスライム',
    rarity: 1,
    power: 5,
    skills: [{ id: 'takeover' }, { id: 'clone', value: 1 }],
    voiceCategory: 'undead',
    flavor:
      '死骸に一滴でも取り付かれれば最後。剣を振り下ろす頃には、すでに二匹に増殖して君の喉元へ飛びかかっているだろう。',
  },
  {
    id: 'bard',
    obtain: ['elf_easy', 'elf_normal'],
    name: '陽気な歌うたい',
    rarity: 1,
    power: 2,
    skills: [
      { id: 'support', value: 2 },
      { id: 'heal', value: 2 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      'ウクレレを奏でる彼を、森の動物たちは親しみを持って「先生」と呼ぶ。その歌声は傷ついた心も体も癒やす。',
  },
  {
    id: 'charger',
    obtain: ['elf_easy'],
    name: '虹ハチドリ',
    rarity: 1,
    power: 2,
    skills: [{ id: 'charge', value: 1 }],
    voiceCategory: 'bird',
    flavor: '七色の翼を持つ小さな鳥。その羽ばたきは見る者に活力を与える。',
  },
  {
    id: 'pray',
    obtain: ['elf_normal', 'elf_high'],
    name: '森の祈り',
    rarity: 1,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'summon', value: 5, summonId: 'token_ent' },
      { id: 'heal', value: 5 },
    ],
    voiceCategory: 'magic',
    flavor:
      '大地の脈動と古樹の祈りが交わるとき、森は自らの意志をもって覚醒する。',
  },
  {
    id: 'bear',
    obtain: ['elf_normal', 'elf_hard'],
    name: '森の恐怖',
    rarity: 1,
    power: 3,
    skills: [{ id: 'lone_wolf', value: 2 }],
    voiceCategory: 'beast',
    flavor:
      '禁域に迷い込んだ愚か者に与えられるのは、警告ではない。ただ前触れなき蹂躙のみである。',
  },
  {
    id: 'incinerator',
    obtain: ['cleric_easy', 'cleric_normal'],
    name: 'インシネレーター',
    rarity: 1,
    power: 4,
    skills: [{ id: 'artillery', value: 1 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '異端の書物、教義に背く者を炎で浄化する実働部隊。マスク越しの彼女の瞳に、慈悲の色はない。',
  },
  {
    id: 'instructor',
    obtain: ['cleric_easy'],
    name: '熱心な教導師',
    rarity: 1,
    power: 4,
    skills: [{ id: 'immune' }],
    voiceCategory: 'human_male_old',
    flavor: '分厚い教典を片手に、休むことなく教えを説き続ける厳格な導き手。',
  },
  {
    id: 'flak',
    obtain: ['cleric_normal'],
    name: 'ミスリルの高射砲',
    rarity: 1,
    power: 7,
    skills: [{ id: 'defender' }, { id: 'intercept', value: 2 }],
    voiceCategory: 'machine_old',
    flavor: '高高度を狙う神聖なる対空砲。上空からの奇襲を許さない。',
  },
  {
    id: 'charity',
    obtain: ['cleric_normal', 'cleric_hard'],
    name: '慈愛',
    rarity: 1,
    power: 3,
    skills: [{ id: 'defender' }, { id: 'heal', value: 4 }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '古より伝わる小さな彫像。周囲に清らかな癒しと絶対の護りをもたらす。',
  },
  {
    id: 'shade',
    obtain: ['devilhunter_easy', 'devilhunter_normal'],
    name: '墓の亡霊',
    rarity: 1,
    power: 4,
    skills: [{ id: 'soul_bind', value: 2 }],
    voiceCategory: 'undead',
    flavor:
      '古い墓地に漂う無念の霧。生者の温もりを嫌い、その魂を冷たい死の淵へと引き摺り込む。',
  },
  {
    id: 'prisoner',
    obtain: ['devilhunter_easy'],
    name: '鉄面の監獄破り',
    rarity: 1,
    power: 6,
    skills: [{ id: 'loss', value: 2 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '自由と引き換えに記憶を捨てた囚人。鉄面の下で正気をすり減らし、ただ破壊の衝動に従って暴れ狂う。',
  },
  {
    id: 'franken',
    obtain: ['devilhunter_normal'],
    name: 'オールドヘイヴンの怪物',
    rarity: 1,
    power: 8,
    skills: [{ id: 'standby', value: 2 }],
    voiceCategory: 'giant',
    flavor:
      '見捨てられた街の地下深くに眠る禁断の造物。動き出せば、その怪力で全てを粉砕する。',
  },
  {
    id: 'necromancer',
    obtain: ['devilhunter_normal', 'devilhunter_hard'],
    name: 'ヴィス・ガルドの背教者',
    rarity: 1,
    power: 1,
    skills: [{ id: 'resurrect', value: 4 }],
    voiceCategory: 'human_female_sexy',
    flavor:
      '『さあ、起きなさい…永遠なる奉仕の時間が始まるわ』。真紅の瞳が見つめる先、死者は再び立ち上がる。',
  },
  {
    id: 'beginnermagic',
    obtain: ['witch_easy', 'witch_normal', 'witch_high'],
    name: '初級魔術',
    rarity: 1,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'summon', value: 5, summonId: 'token_golem' },
      { id: 'support', value: 3 },
    ],
    voiceCategory: 'magic',
    flavor: '大地に流れる脈動をマナへと変換する基礎的な魔術。',
  },
  {
    id: 'shapeshifter',
    obtain: ['witch_easy'],
    name: '変身魔導士',
    rarity: 1,
    power: 4,
    skills: [{ id: 'awake', value: 5, summonId: 'token_golem' }],
    voiceCategory: 'human_male_old',
    flavor:
      '「魔術とは変化、変化とは可能性だ。」自らが生み出した泥人形の姿へと消えるその瞬間まで、男は熱心に可能性を説き続けた。',
  },
  {
    id: 'dragonfire',
    obtain: ['witch_normal', 'witch_high'],
    name: 'ドラゴンファイア',
    rarity: 1,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'artillery', value: 2 },
      { id: 'snipe', value: 8 },
    ],
    voiceCategory: 'magic',
    flavor:
      '厳重に封印された硝子瓶。中で燻るのは、万物を灰燼に帰す竜王の怒りだ。',
  },
  {
    id: 'mage',
    obtain: ['witch_normal', 'witch_hard'],
    name: '未熟な拡散魔導士',
    rarity: 1,
    power: 1,
    skills: [{ id: 'spread', value: 2 }],
    voiceCategory: 'human_female_cute',
    flavor:
      '魔導アカデミーの見習い魔導士。魔法のコントロールが苦手で、暴走した魔力が周囲へバラバラに散乱してしまう。',
  },
  {
    id: 'ninja',
    obtain: ['oni_easy', 'oni_normal'],
    name: '忍者',
    rarity: 1,
    power: 4,
    skills: [{ id: 'stealth', value: 1 }],
    voiceCategory: 'human_male_normal',
    flavor:
      '影に潜み、音もなく標的に近づく工作員。その姿を捉えることは困難である。',
  },
  {
    id: 'ogre',
    obtain: ['oni_easy'],
    name: '鬼',
    rarity: 1,
    power: 7,
    skills: [{ id: 'brutal', value: 2 }],
    voiceCategory: 'giant',
    flavor:
      '血に飢えた咆哮とともに、巨大な金棒が振り下ろされる。理性を失ったその暴虐なる一撃は、周囲のすべてを無差別に粉砕する。',
  },
  {
    id: 'tengu',
    obtain: ['oni_normal'],
    name: '武芸の師範',
    rarity: 1,
    power: 4,
    skills: [{ id: 'move' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '深山に棲まう、風を操り空を舞う人外の剣客。武の神髄を修めたその一太刀は、驕れる人間たちに真の恐怖と剣術の深淵を叩き込む。',
  },
  {
    id: 'omyouji',
    obtain: ['oni_normal', 'oni_hard'],
    name: '漆黒の除霊師',
    rarity: 1,
    power: 4,
    skills: [{ id: 'seal', value: 1 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '闇を以て闇を制する異端の術士。彼女が札をきる時、悪霊は光ではなく、より深い漆黒の結界へと封じ込められる。',
  },
  {
    id: 'vulture',
    obtain: ['priest_easy'],
    name: '屍肉漁り',
    rarity: 1,
    power: 4,
    skills: [{ id: 'recurse', value: 4 }],
    voiceCategory: 'bird',
    flavor:
      '過酷な砂漠では死すら無駄にならない。屍を貪る禿鷹の胃袋で、命は新たな形へと生まれ変わる。',
  },
  {
    id: 'drifter',
    obtain: ['priest_easy', 'priest_normal'],
    name: 'アッシュランドの放浪者',
    rarity: 1,
    power: 4,
    skills: [{ id: 'double_strike' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '灼熱の砂塵を切り裂く双剣。彼の歩みの後には、切り刻まれた絶望のみが残る。',
  },
  {
    id: 'treasurehunter',
    obtain: ['priest_normal'],
    name: 'アッシュランドの冒険家',
    rarity: 1,
    power: 5,
    skills: [{ id: 'cleave' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      'しなやかな鞭を華麗に操る冒険家。敵を攻撃する際に、その長いリーチを活かして複数の対象を同時に討つ。',
  },
  {
    id: 'mummy',
    obtain: ['priest_normal', 'priest_hard'],
    name: '王墓の番人',
    rarity: 1,
    power: 4,
    skills: [{ id: 'burial', value: 3 }],
    voiceCategory: 'undead',
    flavor:
      '永遠の眠りを守る呪われた守護者。その長い寿命は、守るべき秘宝と同じくらい朽ち果ててはいない。',
  },
  {
    id: 'voidbraver',
    obtain: ['void_easy'],
    name: 'ホロウ・ブレイバー',
    rarity: 1,
    power: 2,
    skills: [{ id: 'sublimation', value: 2 }],
    voiceCategory: 'stone',
    flavor:
      'その仮面の下には、もはや人の心は存在しない。虚無の魂が、ただ彼の体を動かしているだけだ。',
  },
  {
    id: 'voidcleric',
    obtain: ['void_easy', 'void_normal'],
    name: 'ホロウ・クレリック',
    rarity: 1,
    power: 3,
    skills: [{ id: 'heal_void', value: 2 }],
    voiceCategory: 'stone',
    flavor:
      '音も、痛みも、感情すら存在しない。祈りの代わりに紡がれる静寂が、兵士たちの傷を無感覚のまま塞いでいく。',
  },
  {
    id: 'voidsniper',
    obtain: ['void_normal', 'void_hard'],
    name: 'ホロウ・スナイパー',
    rarity: 1,
    power: 2,
    skills: [{ id: 'snipe_void', value: 3 }],
    voiceCategory: 'stone',
    flavor:
      '銃声も、閃光も存在しない。放たれた虚無の弾丸は、標的の存在そのものを空間ごと精確にえぐり取る。',
  },
  {
    id: 'voidcommander',
    obtain: ['void_normal'],
    name: 'ホロウ・コマンダー',
    rarity: 1,
    power: 3,
    skills: [{ id: 'support_void', value: 2 }],
    voiceCategory: 'stone',
    flavor:
      '言葉による命令は不要。虚空を介した冷徹な意思の伝達により、名もなき軍勢は完璧な連携で獲物を蹂躙する。',
  },
  {
    id: 'harpy',
    obtain: ['succubus_easy', 'succubus_normal'],
    name: '荒ぶるハーピー',
    rarity: 1,
    power: 4,
    skills: [{ id: 'dodge', value: 5 }],
    voiceCategory: 'human_female_normal',
    flavor: '空を舞う半人半鳥の怪物。獲物を鋭い爪で切り刻む。',
  },
  {
    id: 'curtain',
    obtain: ['succubus_easy'],
    name: 'ブラッド・カーテン',
    rarity: 1,
    power: 10,
    skills: [{ id: 'defender' }, { id: 'guardian' }],
    voiceCategory: 'undead',
    flavor:
      '侵入者を惑わす血色の帳。触れた者の方向感覚を奪い、永遠に迷宮を彷徨わせる。',
  },
  {
    id: 'siren',
    obtain: ['succubus_normal', 'succubus_hard'],
    name: '幻惑の歌姫',
    rarity: 1,
    power: 1,
    skills: [{ id: 'dominate', value: 3 }],
    voiceCategory: 'human_female_sexy',
    flavor:
      '美しき旋律は嵐を呼び、青き翼は絶望を連れてくる。魅入られた者たちは己の意志を永遠に手放す。',
  },
  {
    id: 'baphomet',
    obtain: ['succubus_normal'],
    name: '集会の主',
    rarity: 1,
    power: 7,
    skills: [{ id: 'takeover' }, { id: 'heal', value: 3 }],
    voiceCategory: 'devil',
    flavor:
      '黒ミサを司る山羊頭の魔神。悪魔たちの誓いを束ね、血の契約を仲介する。',
  },
  {
    id: 'minion',
    obtain: ['warlock_easy'],
    name: '魔王のしもべ',
    rarity: 1,
    power: 2,
    skills: [{ id: 'awake', value: 7, summonId: 'token_daemon' }],
    voiceCategory: 'human_male_old',
    flavor: '歪んだ忠誠を誓う狂信者。彼の儀式は、強大な闇を招く呼び水となる。',
  },
  {
    id: 'skeleton',
    obtain: ['warlock_easy', 'warlock_normal'],
    name: 'スケルトン・ソルジャー',
    rarity: 1,
    power: 3,
    skills: [{ id: 'split', value: 3, summonId: 'token_skeleton' }],
    voiceCategory: 'undead',
    flavor:
      '骨と骨が組み合わさった古の戦士。一度倒してもバラバラのパーツを再構築して復活する。',
  },
  {
    id: 'skeletondefender',
    obtain: ['warlock_normal', 'warlock_hard'],
    name: 'スケルトン・ウォリアー',
    rarity: 1,
    power: 6,
    skills: [
      { id: 'standby', value: 2 },
      { id: 'split', value: 3, summonId: 'token_skeleton' },
    ],
    voiceCategory: 'undead',
    flavor:
      '生前の規格外な巨体を、さらに巨大な鎧とメイスで武装した骸骨の重衛兵。',
  },
  {
    id: 'ritual',
    obtain: ['warlock_normal'],
    name: '教団の儀式',
    rarity: 1,
    power: 0,
    skills: [{ id: 'takeover' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'summon', value: 7, summonId: 'token_daemon' },
      { id: 'cull', value: 2 },
    ],
    voiceCategory: 'magic',
    flavor: '漆黒の祭壇で行われる禁忌の儀式。その祈りは、闇の王を呼び覚ます。',
  },
  {
    id: 'largemouth',
    obtain: ['satan_easy', 'satan_normal'],
    name: '肉裂き大口',
    rarity: 1,
    power: 6,
    skills: [{ id: 'sacrifice', value: 2 }],
    voiceCategory: 'monster',
    flavor: '生者の絶望と血の匂いだけが、底なしの飢えを満たす道標となる',
  },
  {
    id: 'fly',
    obtain: ['satan_easy'],
    name: '死蠅の大群',
    rarity: 1,
    power: 1,
    skills: [{ id: 'clone', value: 2 }],
    voiceCategory: 'insect',
    flavor:
      '屍から次々と湧き出し、空を黒く染め上げる不浄の群れ。おぞましい羽音を響かせて増殖する',
  },
  {
    id: 'hand',
    obtain: ['satan_normal', 'satan_hard'],
    name: '悪魔の手',
    rarity: 1,
    power: 2,
    skills: [{ id: 'cull', value: 1 }],
    voiceCategory: 'stone',
    flavor:
      '虚空を裂いて現れる、魔界より召喚されし巨大な腕。いかなる堅牢な障害も無慈悲に握り潰す。',
  },
  {
    id: 'devil',
    obtain: ['satan_normal'],
    name: '地獄の放火魔',
    rarity: 1,
    power: 2,
    skills: [
      { id: 'spread', value: 2 },
      { id: 'explode', value: 2 },
    ],
    voiceCategory: 'devil',
    flavor:
      '背中のタンクには地獄の業火が詰まっている。初めて武器を与えられた小悪魔は、その焦熱を振り撒くことに至上の喜びを感じていた。',
  },
  {
    id: 'liberator',
    obtain: ['exchange_fortune'],
    name: '革命派の解放者',
    rarity: 1,
    power: 4,
    skills: [{ id: 'ambush', value: 1, summonId: 'token_automata' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '退屈な日常は彼女との出会いで終わった。今や彼は、抑圧された者たちを導く革命の炎である。',
  },
  {
    id: 'scrapper',
    obtain: ['exchange_fortune'],
    name: '暴走する解体者',
    rarity: 1,
    power: 8,
    skills: [{ id: 'defender' }, { id: 'startup' }, { id: 'pierce' }],
    voiceCategory: 'machine_new',
    flavor:
      '都市開発のために造られた巨大な鉄の腕は、今や全てを瓦礫へと変える恐るべき破壊兵器と化した。',
  },
  {
    id: 'dwarf',
    obtain: ['exchange_fortune'],
    name: '熟練の鍛冶師',
    rarity: 1,
    power: 4,
    skills: [{ id: 'forge' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '飛び散る火の粉を物ともせず、重い金槌を振るう男。彼が魂を込めて鍛えた剣は、多くの戦士の命を救った。',
  },
  {
    id: 'fenrir',
    obtain: ['exchange_fortune'],
    name: '炎の魔狼',
    rarity: 1,
    power: 4,
    skills: [{ id: 'sacrifice', value: 2 }, { id: 'quick' }],
    voiceCategory: 'wolf',
    flavor:
      'その身を焦がす炎は、尽きることのない飢えと怒りの顕れ。獲物を見つけたが最後、燃え盛る牙が瞬く間に喉笛を食いちぎる。',
  },
  {
    id: 'bigeye',
    obtain: ['android_easy', 'android_normal', 'android_hard'],
    name: 'サイクロプス Mk-II',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'spend', value: 1 },
      { id: 'snipe', value: 5 },
    ],
    voiceCategory: 'machine_new',
    flavor: '単眼の狙撃特化型自律ユニット。一撃必殺の精度を誇る。',
  },
  {
    id: 'scavenger',
    obtain: ['android_easy'],
    name: 'スカベンジャー',
    rarity: 2,
    power: 3,
    skills: [{ id: 'salvage', value: 2 }],
    voiceCategory: 'human_male_normal',
    flavor:
      '誰かが捨てたガラクタも、彼の目利きと技術があれば、再び輝きを取り戻す宝へと変わる。',
  },
  {
    id: 'dreadnought',
    obtain: ['android_normal'],
    name: 'ドラゴン・ドレッドノート',
    rarity: 2,
    power: 10,
    skills: [{ id: 'standby', value: 3 }],
    voiceCategory: 'machine_old',
    flavor:
      '純粋な破壊を目的に建造された古代大戦の巨大兵器。冷たい鋼の奥底で重厚な機関音を響かせ、再び空を焦がす再起動の刻を静かに待っている。',
  },
  {
    id: 'cop',
    obtain: ['android_normal', 'android_hard', 'android_high'],
    name: 'ボーダー・エンフォーサー',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'challenge' },
      { id: 'bind', value: 1 },
      { id: 'summon', value: 1, summonId: 'token_drone' },
    ],
    voiceCategory: 'machine_new',
    flavor:
      'ドローンで逃亡者を路地裏へと追い詰め、一切の感情を交えずに手錠をかける。この街に、彼らから逃れられる暗がりなど存在しない。',
  },
  {
    id: 'armsuits',
    obtain: ['android_hard'],
    name: '強化外骨格',
    rarity: 2,
    power: 3,
    skills: [{ id: 'equip' }, { id: 'sturdy' }],
    voiceCategory: 'machine_new',
    flavor:
      '鋼鉄の装甲を纏う者は戦場で難攻不落の城塞と化す。例え操縦者が倒れても、内蔵AIが稼働を続け、その任務を全うするだろう。',
  },
  {
    id: 'gladiator',
    obtain: ['android_tutorial', 'android_normal', 'android_hard'],
    name: '違法リングの闘士',
    rarity: 2,
    power: 7,
    skills: [{ id: 'legendary' }],
    voiceCategory: 'machine_new',
    flavor:
      '欲望渦巻く未来都市の非合法リングに立つ鋼の闘士。冷徹なる闘志のみを胸に秘め、血とオイルに塗れた容赦なき死闘へと身を投じる。',
  },
  {
    id: 'dragonewt',
    obtain: ['dragon_easy', 'dragon_normal', 'dragon_hard', 'dragon_high'],
    name: '竜人族の騎兵',
    rarity: 2,
    power: 4,
    skills: [{ id: 'snipe', value: 2 }, { id: 'pierce' }],
    voiceCategory: 'horse',
    flavor:
      '竜人族の騎兵。翼は無いが、戦場を駆け抜け敵を貫き、遠方の獲物も逃さない。',
  },
  {
    id: 'egg',
    obtain: ['dragon_easy'],
    name: 'ドラゴンの卵',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'defender' },
      { id: 'growth', value: -2 },
      { id: 'split', value: 6, summonId: 'token_dragon' },
    ],
    voiceCategory: 'stone',
    flavor:
      '表面を覆う紅い殻が、内側から微かな熱を帯びている。いつか訪れる孵化の刻まで、秘めたる命は静かに力を蓄え続ける。',
  },
  {
    id: 'babydragon',
    obtain: ['dragon_normal'],
    name: 'ドラゴンの雛',
    rarity: 2,
    power: 3,
    skills: [{ id: 'growth', value: 2 }],
    voiceCategory: 'lizard',
    flavor:
      'まだ小さなドラゴンの幼体。秘めたる魔力は無限の可能性を感じさせる。',
  },
  {
    id: 'wyvern',
    obtain: ['dragon_normal', 'dragon_hard'],
    name: '群れのワイヴァーン',
    rarity: 2,
    power: 7,
    skills: [{ id: 'takeover' }, { id: 'reinforce', value: 1 }],
    voiceCategory: 'dragon',
    flavor:
      '空を滑る緑の影は、必ず二つ。一方を殺したと安堵するなら、それは間違いだ。その血の匂いは、雲の彼方からもう一方を呼び寄せる。',
  },
  {
    id: 'berserker',
    obtain: ['dragon_hard', 'dragon_high'],
    name: '狂戦士',
    rarity: 2,
    power: 7,
    skills: [{ id: 'berserk', value: 4 }],
    voiceCategory: 'giant',
    flavor:
      '破壊の衝動に魂を売った禁忌の戦士。痛みすら悦びとして斧を振り回す。',
  },
  {
    id: 'drake',
    obtain: ['dragon_tutorial', 'dragon_normal', 'dragon_hard'],
    name: '熱砂地帯のドレイク',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'spread', value: 1 }],
    voiceCategory: 'lizard',
    flavor:
      '熱砂の空を舞い砂嵐を起こす暴虐の亜竜。しかしそれは、真なる竜が降臨するまでの間だけ振りかざす偽りの威厳に過ぎない。',
  },
  {
    id: 'horse',
    obtain: ['knight_easy', 'knight_high'],
    name: 'セレスタリアン・チャージャー',
    rarity: 2,
    power: 4,
    skills: [{ id: 'equip' }, { id: 'pierce' }],
    voiceCategory: 'horse',
    flavor:
      '誇り高きセレスタリアの紋章を背負う戦馬。その力強い蹄の音は、王国の勝利を告げるファンファーレである。',
  },
  {
    id: 'minotaur',
    obtain: ['knight_easy', 'knight_normal', 'knight_hard'],
    name: 'ミノタウロスの傭兵',
    rarity: 2,
    power: 6,
    skills: [
      { id: 'choice', value: 1 },
      { id: 'choice', value: 1, choiceGroup: 2 },
    ],
    choices: [
      { id: 'convert', value: 2 },
      { id: 'brutal', value: 2 },
    ],
    choices2: [{ id: 'pierce' }, { id: 'cleave' }],
    voiceCategory: 'giant',
    flavor:
      '圧倒的な力で敵を薙ぎ払うミノタウルスの傭兵。ただし、適切な報酬が支払われなければ、敵味方の区別なく暴れまわる。',
  },
  {
    id: 'crusher',
    obtain: ['knight_normal'],
    name: '豪腕の破壊者',
    rarity: 2,
    power: 5,
    skills: [{ id: 'crush' }],
    voiceCategory: 'stone',
    flavor:
      '巨大な武器を力任せに振るい、立ち塞がる障害物や罠を淡々と壊して回る頼れる力仕事の専門家。',
  },
  {
    id: 'elephant',
    obtain: ['knight_normal', 'knight_hard'],
    name: '攻城エレファント',
    rarity: 2,
    power: 6,
    skills: [{ id: 'equip' }, { id: 'takeover' }],
    voiceCategory: 'stone',
    flavor:
      '分厚い装甲と武装を纏った、歩く攻城兵器。その圧倒的な質量と歩みは、いかなる城壁や防陣もただの瓦礫の山へと変える。',
  },
  {
    id: 'sergeant',
    obtain: ['knight_hard'],
    name: '鉄血の教官',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'berserk', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'summon', value: 2, summonId: 'token_knight' },
      { id: 'support', value: 4 },
    ],
    voiceCategory: 'human_female_assassin',
    flavor:
      '彼女の前で甘えは許されない。過酷な試練を与えることで、兵士たちを真の戦士へと鍛え上げているのだ。',
  },
  {
    id: 'lion',
    obtain: ['knight_tutorial', 'knight_normal', 'knight_hard', 'knight_high'],
    name: '王家のライオン',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'quick' }],
    voiceCategory: 'beast',
    flavor:
      '黄金に輝く鬣は王家の威信を象徴し、その雄叫びは迫り来る邪悪を打ち払う誇り高き守護者。',
  },
  {
    id: 'seaslug',
    obtain: ['cthulhu_easy', 'cthulhu_normal', 'cthulhu_hard'],
    name: 'ブルー・ドラゴン',
    rarity: 2,
    power: 1,
    skills: [{ id: 'bless', value: 2 }],
    voiceCategory: 'sea',
    flavor:
      '青き海を漂う幻獣。その姿を見た者には、ささやかな海の恵みがもたらされるという。',
  },
  {
    id: 'prince',
    obtain: ['cthulhu_easy'],
    name: '星の王子',
    rarity: 2,
    power: 2,
    skills: [{ id: 'stealth', value: 2 }],
    voiceCategory: 'monster',
    flavor:
      '黒き触手に抱かれた幼き王は、遥か宇宙の深淵から、我らの空へと帰還しつつある。',
  },
  {
    id: 'shark',
    obtain: ['cthulhu_normal'],
    name: 'メガロドン',
    rarity: 2,
    power: 6,
    skills: [
      { id: 'standby', value: 2 },
      { id: 'stealth', value: 2 },
    ],
    voiceCategory: 'sea',
    flavor:
      '深き蒼から突如として現れる規格外の巨体。その顎が海面を割る時、逃げる術は既に残されていない。',
  },
  {
    id: 'sahagin',
    obtain: ['cthulhu_normal', 'cthulhu_hard'],
    name: 'アビス・ガーディアン',
    rarity: 2,
    power: 6,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'bind', value: 1 },
      { id: 'pierce' },
    ],
    voiceCategory: 'monster',
    flavor:
      '深海の神殿の番人。捕らえた獲物を暗い水底へ引きずり込み、手にした鋭い銛で無慈悲に貫く。',
  },
  {
    id: 'parasite',
    obtain: ['cthulhu_hard'],
    name: '招かれざる来訪者',
    rarity: 2,
    power: 1,
    skills: [{ id: 'equip' }, { id: 'clone', value: 1 }],
    voiceCategory: 'insect',
    flavor:
      '宇宙の深淵から飛来した無機生命体。宿主に取り付いて生命力を啜り、増殖しながらやがて全てを空洞の石へと変えていく。',
  },
  {
    id: 'ghostship',
    obtain: ['cthulhu_tutorial', 'cthulhu_normal', 'cthulhu_hard'],
    name: 'ファントムポートの幽霊船',
    rarity: 2,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'stealth', value: 1 }],
    voiceCategory: 'stone',
    flavor:
      '濃霧の奥底より音もなく現れる呪われた船。朽ち果てた帆に亡者たちの嘆きを孕み、目撃した者を永遠の深淵へと引きずり込む。',
  },
  {
    id: 'splite',
    obtain: ['elf_easy', 'elf_normal', 'elf_hard'],
    name: 'スプライトの冒険者',
    rarity: 2,
    power: 2,
    skills: [{ id: 'dodge', value: 4 }],
    voiceCategory: 'human_female_cute',
    flavor:
      '未知なる世界への憧れを胸に、故郷の森を旅立ったスプライト。生来のすばしっこさと微かな光の加護が、彼女を守護している。',
  },
  {
    id: 'bird',
    obtain: ['elf_easy'],
    name: '新緑の導き鳥',
    rarity: 2,
    power: 1,
    skills: [{ id: 'split', value: 5, summonId: 'token_ent' }],
    voiceCategory: 'bird',
    flavor: 'その小さなさえずりが途絶えたとき、森の静寂は怒号へと変わる。',
  },
  {
    id: 'shaman',
    obtain: ['elf_normal'],
    name: '樫族のシャーマン',
    rarity: 2,
    power: 5,
    skills: [{ id: 'dispel' }],
    voiceCategory: 'human_male_old',
    flavor:
      '彼の呪術は敵の武装を縛り、そして砕く。千年の時を生きる老エルフの瞳には、人の造りし武具など児戯に等しい。',
  },
  {
    id: 'centaur',
    obtain: ['elf_normal', 'elf_hard'],
    name: 'ヴェルドールの狩猟者',
    rarity: 2,
    power: 2,
    skills: [{ id: 'choice', value: 1 }],
    choices: [{ id: 'quick' }, { id: 'snipe', value: 3 }],
    voiceCategory: 'human_male_warrior',
    flavor: '疾風のごとき俊敏さと、百発百中の射撃技術を併せ持つ誇り高き戦士。',
  },
  {
    id: 'darkelf',
    obtain: ['elf_hard'],
    name: 'ダンジョン・シーカー',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'lone_wolf', value: 2 },
      { id: 'stealth', value: 1 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '未踏の迷宮を踏破する熟練の探索者。鋭い勘と身のこなしで、幾多の危険をくぐり抜ける。',
  },
  {
    id: 'ranger',
    obtain: ['elf_tutorial', 'elf_normal', 'elf_hard'],
    name: 'ルーン辿りのレインジャー',
    rarity: 2,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'snipe', value: 4 }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '微かに光るルーンを道標に、失った記憶を辿る旅。その道を阻む者がいれば、迷いなき必中の矢が静かに急所を射抜く。',
  },
  {
    id: 'demolisher',
    obtain: ['cleric_easy', 'cleric_normal', 'cleric_hard'],
    name: 'デモリッシャー',
    rarity: 2,
    power: 3,
    skills: [{ id: 'artillery', value: 2 }],
    voiceCategory: 'human_male_normal',
    flavor: '教会の爆破工作員。彼の持つ箱は異端を裁くための聖なる祭壇である。',
  },
  {
    id: 'pegasus',
    obtain: ['cleric_easy'],
    name: '聖なるペガサス',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'equip' },
      { id: 'heal', value: 3 },
      { id: 'draw', value: 1 },
    ],
    voiceCategory: 'horse',
    flavor:
      '美しい有翼の馬。性格は温厚だが警戒心が強く、自らが認めた乗り手以外が触れることは叶わない。',
  },
  {
    id: 'doom',
    obtain: ['cleric_normal'],
    name: '破滅',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'takeover' },
      { id: 'defender' },
      { id: 'spread', value: 6 },
      { id: 'sturdy' },
    ],
    voiceCategory: 'stone',
    flavor: '古より伝わる小さな彫像。周囲に底知れぬ絶望と絶大な破滅をもたらす',
  },
  {
    id: 'acolyte',
    obtain: ['cleric_normal', 'cleric_hard'],
    name: '天球のアコライト',
    rarity: 2,
    power: 2,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'heal', value: 3 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_male_old',
    flavor: '天球の運行を読み解き、聖女の審判を補佐する老神官。',
  },
  {
    id: 'angelstatue',
    obtain: ['cleric_hard'],
    name: '天使の像',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'defender' },
      { id: 'awake', value: 7, summonId: 'token_angel' },
      { id: 'sturdy' },
    ],
    voiceCategory: 'stone',
    flavor:
      '朽ちた廃教会で、沈黙のまま祭壇を守り続ける石像。信仰の光が再び灯る時、真の姿を取り戻すという。',
  },
  {
    id: 'monk',
    obtain: ['cleric_tutorial', 'cleric_normal', 'cleric_hard'],
    name: '夜明けの番人',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'heal', value: 4 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '闇夜を切り裂く一条の光。神の教えを胸に刻み、冒涜者を容赦なく浄化する、悪魔に恐れられし裁きの代行者。',
  },
  {
    id: 'bat',
    obtain: ['devilhunter_easy', 'devilhunter_normal', 'devilhunter_hard'],
    name: '吸血コウモリ',
    rarity: 2,
    power: 2,
    skills: [{ id: 'clone', value: 1 }, { id: 'absorb' }],
    voiceCategory: 'insect',
    flavor:
      '影から忍び寄り、静かに獲物の命を啜る。その羽ばたきが聞こえた時、既に逃げ場は失われている。',
  },
  {
    id: 'cook',
    obtain: ['devilhunter_easy'],
    name: '恐怖の調理長',
    rarity: 2,
    power: 5,
    skills: [{ id: 'execute' }, { id: 'heal', value: 5 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '彼の作る肉シチューは絶品だが、何の肉を使っているかは誰も聞こうとしない。',
  },
  {
    id: 'specter',
    obtain: ['devilhunter_normal', 'devilhunter_hard'],
    name: '魂の徴税人',
    rarity: 2,
    power: 7,
    skills: [{ id: 'takeover' }, { id: 'pierce' }, { id: 'extort', value: 2 }],
    voiceCategory: 'undead',
    flavor:
      '慈悲はない。情状酌量もない。冥府の帳簿の帳尻を合わせるため、それは今日も無作為に魂を削り取っていく。',
  },
  {
    id: 'plaguedoctor',
    obtain: ['devilhunter_normal', 'devilhunter_high'],
    name: '烏羽の医師',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'heal', value: 3 },
      { id: 'toxic', value: 3 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '彼女の処方箋は、明日を繋ぐ特効薬か、あるいは安息へと誘う安楽死の劇薬か',
  },
  {
    id: 'servant',
    obtain: ['devilhunter_hard'],
    name: '吸血鬼の従者',
    rarity: 2,
    power: 3,
    skills: [{ id: 'equip' }, { id: 'soul_bind', value: 2 }],
    voiceCategory: 'human_female_sexy',
    flavor:
      '「どうか私を、貴方様の傍に」自らの弱さを知る妖艶な吸血鬼は、永遠の夜を生き抜くため、強き者の腕へとすり寄る。',
  },
  {
    id: 'undeadking',
    obtain: ['devilhunter_tutorial', 'devilhunter_normal', 'devilhunter_hard'],
    name: '亡国のデス・ロード',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'resurrect', value: 2 },
      { id: 'resurrect', value: 2 },
    ],
    voiceCategory: 'undead',
    flavor:
      '国が滅びようとも錆びた王冠を戴く骸の王。その眼窩の奥で、死を超越した威光が今も冷たく輝く。',
  },
  {
    id: 'cat',
    obtain: ['witch_easy'],
    name: '食糧庫のコソ泥',
    rarity: 2,
    power: 2,
    skills: [{ id: 'quick' }, { id: 'extort', value: 2 }],
    voiceCategory: 'beast',
    flavor:
      '城の警備もなんのその、神出鬼没の小さな怪盗は宵の闇をすり抜けていく。',
  },
  {
    id: 'iceblast',
    obtain: ['witch_easy', 'witch_normal', 'witch_hard'],
    name: 'アイスブラスト',
    rarity: 2,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'bind', value: 3 },
      { id: 'freeze', value: 1 },
    ],
    voiceCategory: 'magic',
    flavor: '冷気が染み出す氷結の塊。触れた者はたちまち動きを奪われる。',
  },
  {
    id: 'ring',
    obtain: ['witch_normal'],
    name: '願いの指輪',
    rarity: 2,
    power: 1,
    skills: [
      { id: 'equip' },
      { id: 'convert', value: 1 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'heal', value: 2 },
      { id: 'draw', value: 2 },
      { id: 'snipe', value: 3 },
      { id: 'spread', value: 2 },
      { id: 'support', value: 2 },
      { id: 'lone_wolf', value: 2 },
    ],
    voiceCategory: 'devil',
    flavor:
      '黄金の輪に封じられし古の魔神の強大なる奇跡。富か力か、それとも破滅か。指先に光る魅惑の輝きは、持ち主の運命を狂わせる甘い毒となる。',
  },
  {
    id: 'battlemage',
    obtain: ['witch_normal', 'witch_hard'],
    name: 'ギルドの戦闘魔導士',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_male_normal',
    flavor:
      '剣と魔法を操る魔導士。彼らが招集されたということは、困難な任務であることを意味する',
  },
  {
    id: 'gargoyle',
    obtain: ['witch_hard'],
    name: 'ガーゴイル',
    rarity: 2,
    power: 6,
    skills: [{ id: 'standby', value: 2 }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '塔の頂から見下ろす冷たい石の瞳。夜の帳が下りる時、それは獲物を狙う狩人となる。',
  },
  {
    id: 'wizard',
    obtain: ['witch_tutorial', 'witch_normal', 'witch_hard'],
    name: 'アカデミーの大魔導士',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'summon', value: 5, summonId: 'token_golem' },
    ],
    voiceCategory: 'human_male_normal',
    flavor:
      '彼が紡ぐ古代の呪文は、無機物すらも忠実な下僕へと変え、戦場に絶対的な力をもたらす。',
  },
  {
    id: 'gashadokuro',
    obtain: ['oni_easy'],
    name: '餓者髑髏',
    rarity: 2,
    power: 9,
    skills: [{ id: 'awake', value: 1, summonId: 'token_soul' }],
    voiceCategory: 'undead',
    flavor:
      '戦場に散った無数の亡骸が、今ここに集い、一つの巨大な骸骨の巨人を形成する。その眼窩に宿るは、尽きぬ飢餓と復讐の炎。',
  },
  {
    id: 'samurai',
    obtain: ['oni_easy', 'oni_normal', 'oni_hard'],
    name: '山道の人斬り',
    rarity: 2,
    power: 7,
    skills: [{ id: 'challenge' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '寂れた峠道に、血の匂いと白刃が閃く。強き者との死合いのみを渇望する修羅は、目の前の標的へと歩み寄り、静かに刀を抜く。',
  },
  {
    id: 'yukionna',
    obtain: ['oni_normal'],
    name: '薄氷の乙女',
    rarity: 2,
    power: 3,
    skills: [{ id: 'freeze', value: 1 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '吐息は白く、眼差しは氷よりも冷たく。彼女が優しく微笑みかける時、哀れな犠牲者の血潮は凍りつき、戦場に永遠の静寂なる像が立ち並ぶ。',
  },
  {
    id: 'muramasa',
    obtain: ['oni_normal', 'oni_hard', 'oni_high'],
    name: '無銘の妖刀',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'equip' },
      { id: 'brutal', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [{ id: 'absorb' }, { id: 'soul_bind', value: 2 }],
    voiceCategory: 'sword',
    flavor:
      '無限の切れ味を誇る妖刀。振るうたびに、共に戦う者の血肉を啜り尽くす。',
  },
  {
    id: 'biwa',
    obtain: ['oni_hard'],
    name: '盲目の怪僧',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'seal', value: 1 },
      { id: 'summon', value: 1, summonId: 'token_soul' },
    ],
    voiceCategory: 'undead',
    flavor:
      '朽ちた琵琶を掻き鳴らす、盲目の僧。その音色は迷える魂を呼び寄せ、生者の力を奪い去る。',
  },
  {
    id: 'nurikabe',
    obtain: ['oni_tutorial', 'oni_normal', 'oni_hard'],
    name: '見下ろす巨顔',
    rarity: 2,
    power: 13,
    skills: [{ id: 'legendary' }, { id: 'defender' }],
    voiceCategory: 'stone',
    flavor:
      '宵闇に突如立ちはだかる絶対の絶望。どれほど刃を立てようとも揺るがぬ巨岩は、侵入者を冷たく見下ろす。',
  },
  {
    id: 'camel',
    obtain: ['priest_easy'],
    name: '駄載ラクダ',
    rarity: 2,
    power: 3,
    skills: [{ id: 'equip' }, { id: 'move' }],
    voiceCategory: 'beast',
    flavor:
      '荒野を征く旅人たちの必需品。その背には重い荷物が積まれ、あるいは戦場へと駆り出される。',
  },
  {
    id: 'manticore',
    obtain: ['priest_easy', 'priest_normal', 'priest_hard'],
    name: '鋼のマンティコア',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'standby', value: 2 },
      { id: 'intercept', value: 2 },
      { id: 'sturdy' },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '忘れ去られた古代文明の遺物であり、侵入者を排除するためだけに稼働し続ける機械魔獣。',
  },
  {
    id: 'kitepriest',
    obtain: ['priest_normal'],
    name: '鳶の神官',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'burial', value: 2 },
      { id: 'recurse', value: 2 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '空高く舞う鳶の目を持ち、過去と未来を見通す冷徹なる巫女。神秘の呪文で、途切れた運命の糸を再び紡ぐ。',
  },
  {
    id: 'griffin',
    obtain: ['priest_normal', 'priest_hard'],
    name: 'グリフィン',
    rarity: 2,
    power: 7,
    skills: [{ id: 'takeover' }, { id: 'move' }, { id: 'pierce' }],
    voiceCategory: 'bird',
    flavor:
      '鷲の頭と獅子の胴体を持つ神聖なる獣。その翼は天空を制し、その爪は大地を切り裂く。',
  },
  {
    id: 'snakepriest',
    obtain: ['priest_hard'],
    name: '蛇の神官',
    rarity: 2,
    power: 4,
    skills: [{ id: 'challenge' }, { id: 'toxic', value: 4 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '毒蛇を従え、戦士に過酷な試練を課す神殿の導き手。猛毒に耐え抜き、その牙を掻いくぐった者のみが真の勇者と認められる。',
  },
  {
    id: 'sentinel',
    obtain: ['priest_tutorial', 'priest_normal', 'priest_hard'],
    name: '黄金の歩哨',
    rarity: 2,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'guardian' }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '遺跡の深部で王の眠りを守護する黄金の機械兵士。暗い石室に、古く軋んだ駆動音が響き渡る。',
  },
  {
    id: 'daemonarmor',
    obtain: ['satan_easy', 'void_easy', 'succubus_easy', 'warlock_easy'],
    name: '悪魔の鎧',
    rarity: 2,
    power: 5,
    skills: [{ id: 'equip' }, { id: 'sacrifice', value: 2 }, { id: 'deadly' }],
    voiceCategory: 'sword',
    flavor:
      '真紅の血肉を喰らい、絶大なる力を対象に宿す呪われた甲冑。身に着けた者は代償として自らの生命を削り続ける。',
  },
  {
    id: 'killermachine',
    obtain: [
      'satan_normal',
      'void_normal',
      'succubus_normal',
      'warlock_normal',
    ],
    name: '殺戮歩行機械',
    rarity: 2,
    power: 6,
    skills: [{ id: 'brutal', value: 3 }, { id: 'double_strike' }],
    voiceCategory: 'machine_new',
    flavor:
      'ただ破壊のためだけに戦場を闊歩する殺戮の権化。その双腕の刃が止まるのは、周囲のすべてが灰燼に帰した時のみである。',
  },
  {
    id: 'bountyhunter',
    obtain: ['void_easy', 'void_normal', 'void_hard'],
    name: '賞金稼ぎ',
    rarity: 2,
    power: 7,
    skills: [{ id: 'convert', value: 2 }],
    voiceCategory: 'sword',
    flavor:
      '扉が開かれた瞬間、酒場の喧騒は凍りついた。こぼれ落ちた麦酒が床に染み込むより早く、冷たい斧が振り下ろされる。',
  },
  {
    id: 'blackknight',
    obtain: ['void_normal', 'void_hard'],
    name: '黒騎士',
    rarity: 2,
    power: 4,
    skills: [{ id: 'convert', value: 1 }, { id: 'deadly' }, { id: 'pierce' }],
    voiceCategory: 'horse',
    flavor:
      '主君を持たず、盾の紋章を塗りつぶした傭兵騎士。鍛え上げた槍捌きで過酷な戦場を生き抜く。',
  },
  {
    id: 'voiddog',
    obtain: ['void_hard'],
    name: '虚無の捕食者',
    rarity: 2,
    power: 2,
    skills: [{ id: 'sublimation', value: 1 }, { id: 'quick' }],
    voiceCategory: 'stone',
    flavor:
      '次元の裂け目より現れる漆黒の魔獣。獲物の存在そのものを貪り喰らう。',
  },
  {
    id: 'traveler',
    obtain: ['void_normal', 'void_hard'],
    name: '追放された旅人',
    rarity: 2,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'deadly' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '村を救った英雄は病魔に冒され、故郷を追われた。かつて自らが守り抜いた世界に背を向けて。',
  },
  {
    id: 'goat',
    obtain: ['succubus_easy', 'succubus_normal', 'succubus_hard'],
    name: 'スケープゴート',
    rarity: 2,
    power: 3,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'charge', value: 2 },
    ],
    voiceCategory: 'monster',
    flavor:
      '不吉な儀式の供物として捧げられる山羊。その命が尽きる時、主には強大な魔力が還元される。',
  },
  {
    id: 'alraune',
    obtain: ['succubus_normal', 'succubus_hard'],
    name: '茨の妖精',
    rarity: 2,
    power: 2,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'dominate', value: 2 },
      { id: 'toxic', value: 2 },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '深き森で微睡む紫の花に魅入られてはならない。その甘き香りは、命を蝕む死の胞子か、あるいは永遠に目覚めぬ隷属の夢への誘いなのだから。',
  },
  {
    id: 'shatter',
    obtain: ['succubus_hard'],
    name: 'マインドシャッター',
    rarity: 2,
    power: 0,
    skills: [{ id: 'choice', value: 1 }],
    choices: [
      { id: 'dominate', value: 4 },
      { id: 'burial', value: 8 },
    ],
    voiceCategory: 'magic',
    flavor:
      '生涯をかけた魔道の探求も一瞬で白紙と化す。理性を砕かれ、残るのは傀儡としての服従か、完全な忘却か。',
  },
  {
    id: 'incubus',
    obtain: ['succubus_normal', 'succubus_hard'],
    name: '夜の貴公子',
    rarity: 2,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'absorb' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '宵闇を纏い、妖しく微笑む魔界の住人。視線に捕らえられたが最後、理性は脆くも崩れ去る。',
  },
  {
    id: 'enchanter',
    obtain: ['warlock_easy', 'warlock_normal', 'warlock_hard'],
    name: 'ダーク・エンチャンター',
    rarity: 2,
    power: 4,
    skills: [{ id: 'grant_deadly' }],
    voiceCategory: 'human_male_old',
    flavor:
      '闇の魔力を注ぎ込み、魂を調律する老魔術師。その秘術を施された者は、敵を確実に葬る致命の刃となる。',
  },
  {
    id: 'metalworker',
    obtain: ['warlock_normal', 'warlock_hard'],
    name: '教団の職工',
    rarity: 2,
    power: 4,
    skills: [{ id: 'grant_sturdy' }],
    voiceCategory: 'devil',
    flavor:
      '仲間の肉体を無慈悲に改造する悪魔。身を捩るほどの激痛の代償として、冷たく強固な金属の体を与える。',
  },
  {
    id: 'priestess',
    obtain: ['warlock_hard'],
    name: '聖餐の司祭',
    rarity: 2,
    power: 4,
    skills: [{ id: 'execute' }, { id: 'resurrect', value: 5 }],
    voiceCategory: 'human_female_sexy',
    flavor: '一つの命を奪うことで、深淵より悪魔を呼び覚ます。',
  },
  {
    id: 'skeletonlord',
    obtain: ['warlock_normal', 'warlock_hard'],
    name: 'スケルトン・ロード',
    rarity: 2,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'split', value: 3, summonId: 'token_skeleton' },
    ],
    voiceCategory: 'undead',
    flavor:
      '迷宮を彷徨う骸の王。その体が砕け散る時、呪われた骨は新たな兵士として立ち上がる。',
  },
  {
    id: 'dealer',
    obtain: ['satan_easy', 'satan_normal', 'satan_hard'],
    name: 'デビル・ディーラー',
    rarity: 2,
    power: 5,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'draw', value: 3 },
    ],
    voiceCategory: 'devil',
    flavor:
      '「さあ、運命を選びな。代償は君の魂で十分だ。」不敵な笑みを浮かべる悪魔の占い師。',
  },
  {
    id: 'cavalry',
    obtain: ['satan_normal', 'satan_hard', 'satan_high'],
    name: '煉獄侯爵の先陣',
    rarity: 2,
    power: 5,
    skills: [{ id: 'challenge' }, { id: 'hero', value: 2 }, { id: 'pierce' }],
    voiceCategory: 'horse',
    flavor:
      '焦熱の風を切り裂き、気高き悪魔が戦場を駆ける。その立ち振る舞いはどこまでも優雅にして、振るう一撃は残酷そのもの。',
  },
  {
    id: 'warlock',
    obtain: ['satan_hard'],
    name: '煉獄の拷問官',
    rarity: 2,
    power: 4,
    skills: [
      { id: 'sacrifice', value: 4 },
      { id: 'berserk', value: 4 },
      { id: 'spread', value: 4 },
    ],
    voiceCategory: 'undead',
    flavor:
      '燃え盛る炎の鞭を振るう魔界の拷問官。その一振りは敵を焼き払い、自らの魂さえも劫火の糧とする。',
  },
  {
    id: 'wendigo',
    obtain: ['satan_normal', 'satan_hard'],
    name: '吹雪の悪霊',
    rarity: 2,
    power: 7,
    skills: [
      { id: 'legendary' },
      { id: 'takeover' },
      { id: 'freeze', value: 2 },
    ],
    voiceCategory: 'beast',
    flavor:
      '死の嵐の中で、それは永遠の飢えを満たそうと彷徨う。すべてを喰らい、すべてを凍らせ、後には静寂な雪原だけが残される。',
  },
  {
    id: 'employee',
    obtain: ['exchange_fortune'],
    name: '真面目な使用人',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'split', value: 1, summonId: 'token_automata' },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '「お掃除、お洗濯、そして侵入者の排除。当社の新モデルです！今なら旧式は無料で引き取ります！」',
  },
  {
    id: 'detective',
    obtain: ['exchange_fortune'],
    name: '復讐に燃える捜査官',
    rarity: 2,
    power: 6,
    skills: [
      { id: 'ambush', value: 1, summonId: 'token_automata' },
      { id: 'execute' },
    ],
    voiceCategory: 'human_male_warrior',
    flavor:
      '機械の暴走事故で娘を奪われた刑事。彼の心には、決して埋まることのない穴がある。',
  },
  {
    id: 'berserkir',
    obtain: ['exchange_fortune'],
    name: 'アグニカの信奉者',
    rarity: 2,
    power: 1,
    skills: [{ id: 'forge' }, { id: 'quick' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '彼らにとって戦いとは、神に捧げる儀式である。狂信的な叫びと共に振るわれる武具は、戦いの中でより鋭く研ぎ澄まされていく。',
  },
  {
    id: 'mjolnir',
    obtain: ['exchange_fortune'],
    name: '雷神の鎚',
    rarity: 2,
    power: 2,
    skills: [
      { id: 'equip' },
      { id: 'snipe', value: 3 },
      { id: 'salvage', value: 1 },
    ],
    voiceCategory: 'stone',
    flavor:
      '天の怒りを顕現せし剛雷の戦鎚。主の呼応に応じて雷鳴と共に飛来し、万物を等しく打ち砕く。',
  },
  {
    id: 'cyborgninja',
    obtain: ['android_normal', 'android_hard'],
    name: '光刃の追跡者',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'spend', value: 2 },
      { id: 'choice', value: 2 },
    ],
    choices: [
      { id: 'stealth', value: 1 },
      { id: 'clone', value: 1 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '金属の心臓と人間の執念を併せ持つ、鋼鉄の隠密。暗闇に溶け込み、敵の虚をつく一撃は、戦局を覆す決定打となる。',
  },
  {
    id: 'booster',
    obtain: ['android_normal', 'android_hard', 'android_high'],
    name: 'イーグルブースター',
    rarity: 3,
    power: 1,
    skills: [{ id: 'equip' }, { id: 'quick' }],
    voiceCategory: 'machine_new',
    flavor:
      '天空を駆ける鷲が如き加速力をもたらす推進器。対象は瞬く間に敵陣を強襲する。',
  },
  {
    id: 'hacker',
    obtain: ['android_hard'],
    name: '未来都市のハッカー',
    rarity: 3,
    power: 5,
    skills: [{ id: 'hack' }],
    voiceCategory: 'human_female_normal',
    flavor:
      '網膜に映る情報の海を泳ぎ、堅牢なセキュリティの隙を突く電子の魔術師。彼女の指先が動くとき、隠された機密データが白日の下に晒される。',
  },
  {
    id: 'cyberdragon',
    obtain: ['android_hard', 'android_high'],
    name: '試作型ドラグーン',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'spend', value: 2 },
      { id: 'spread', value: 3 },
    ],
    voiceCategory: 'machine_new',
    flavor: '試作型の重機動兵器。圧倒的な面制圧力を持つ。',
  },
  {
    id: 'catoblepas',
    obtain: ['dragon_normal', 'dragon_hard'],
    name: '瘴気のカトブレパス',
    rarity: 3,
    power: 5,
    skills: [{ id: 'miasma' }],
    voiceCategory: 'monster',
    flavor:
      '瘴気を撒き散らす災いの魔獣。その息吹が触れたものは命の芽吹きすら阻まれる。',
  },
  {
    id: 'dragoon',
    obtain: ['dragon_normal', 'dragon_hard'],
    name: '覇道のドラグーン',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'double_strike' },
      { id: 'awake', value: 6, summonId: 'token_dragon' },
    ],
    voiceCategory: 'human_female_assassin',
    flavor:
      '竜の力を宿す騎士。彼女の槍が閃く時、漆黒の翼が空を覆い、敵陣に絶望の業火が舞い降りる。',
  },
  {
    id: 'phoenix',
    obtain: ['dragon_hard', 'dragon_high'],
    name: 'カラドのフェニックス',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'berserk', value: 3 },
      { id: 'explode', value: 3 },
      { id: 'split', value: 6, summonId: 'token_phoenix' },
    ],
    voiceCategory: 'bird',
    flavor:
      'カラド山の頂きを焦がす不滅の霊鳥。自らの命を爆炎と化し、その灰の中から幾度でも舞い戻る。',
  },
  {
    id: 'dragon',
    obtain: ['dragon_hard', 'dragon_high'],
    name: 'ファイア・ドラゴン',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'legendary' },
      { id: 'berserk', value: 4 },
      { id: 'spread', value: 2 },
    ],
    voiceCategory: 'dragon',
    flavor:
      '炎を纏った紅蓮の翼。その咆哮は敵を焼き払い、荒ぶる魔力は周囲をも巻き込む。',
  },
  {
    id: 'admiral',
    obtain: ['knight_normal', 'knight_hard'],
    name: '慈悲なき提督',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'execute' },
      { id: 'summon', value: 2, summonId: 'token_knight' },
      { id: 'summon', value: 2, summonId: 'token_knight' },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '狂気と野望を海図に描き、己の栄光のために部下をも駒として消費する冷酷なる将軍。',
  },
  {
    id: 'assassin',
    obtain: ['knight_normal', 'knight_hard', 'knight_high'],
    name: 'ギルドの暗殺者',
    rarity: 3,
    power: 1,
    skills: [{ id: 'stealth', value: 1 }, { id: 'quick' }, { id: 'deadly' }],
    voiceCategory: 'human_female_assassin',
    flavor: '2本の短剣を持つ女暗殺者。一瞬の隙も逃さず、死の影から獲物を屠る。',
  },
  {
    id: 'kingslayer',
    obtain: ['knight_hard'],
    name: 'キングスレイヤー',
    rarity: 3,
    power: 5,
    skills: [{ id: 'treason' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '狂気に満ちた前王を討った悲劇の騎士。その剣に刻まれた反逆の罪は、永遠に彼を縛り続ける。',
  },
  {
    id: 'champion',
    obtain: ['knight_hard'],
    name: 'アリーナのチャンピオン',
    rarity: 3,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'hero', value: 3 }],
    voiceCategory: 'human_male_warrior',
    flavor: '観衆の歓声こそが彼の力。その雄姿は味方を鼓舞し、敵を圧倒する。',
  },
  {
    id: 'octopus',
    obtain: ['cthulhu_normal', 'cthulhu_hard', 'cthulhu_high'],
    name: '深海の魔物',
    rarity: 3,
    power: 4,
    skills: [{ id: 'split', value: 2, summonId: 'token_legs' }],
    voiceCategory: 'monster',
    flavor:
      '深海に潜む異形の魔物。全身が筋肉の塊で、足を失ってもすぐに生えてくる。',
  },
  {
    id: 'hound',
    obtain: ['cthulhu_normal', 'cthulhu_hard'],
    name: '破片の猟犬',
    rarity: 3,
    power: 5,
    skills: [{ id: 'phase' }],
    voiceCategory: 'monster',
    flavor:
      '時間の死角から滲み出す次元の捕食者。その幾何学的な牙から逃れられる者は、過去にも未来にも存在しない。',
  },
  {
    id: 'horseshoecrab',
    obtain: ['cthulhu_hard'],
    name: '太古のカブトガニ',
    rarity: 3,
    power: 1,
    skills: [{ id: 'bless', value: 1 }, { id: 'deadly' }],
    voiceCategory: 'insect',
    flavor:
      '数億年の時を超えて生き続ける、生きた化石。その堅牢な甲殻と秘めた猛毒は、全ての外敵を等しく絶望へと突き落とす。',
  },
  {
    id: 'oldgod',
    obtain: ['cthulhu_hard', 'cthulhu_high'],
    name: '古の神',
    rarity: 3,
    power: 9,
    skills: [
      { id: 'legendary' },
      { id: 'takeover' },
      { id: 'stealth', value: 1 },
      { id: 'pierce' },
    ],
    voiceCategory: 'monster',
    flavor: '深海の深淵より目覚めた、名もなき異形の神。その一撃は魂を貫く。',
  },
  {
    id: 'highelf',
    obtain: ['elf_normal', 'elf_hard'],
    name: 'ロストレイルの精鋭パトロール',
    rarity: 3,
    power: 1,
    skills: [
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
      { id: 'snipe', value: 1 },
    ],
    voiceCategory: 'human_female_cool',
    flavor: '迷いの森を監視する精鋭。その神速の連射は、影すらも逃がさない。',
  },
  {
    id: 'thief',
    obtain: ['elf_normal', 'elf_hard'],
    name: 'ギルドの錠前破り',
    rarity: 3,
    power: 3,
    skills: [{ id: 'choice', value: 1 }],
    choices: [{ id: 'dispel' }, { id: 'crush' }, { id: 'salvage', value: 1 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '複雑な魔法陣の解除から力任せの破壊工作、そして遺物の回収まで。彼女の淀みない手口の前では、いかなる障害も意味を成さない。',
  },
  {
    id: 'caller',
    obtain: ['elf_hard', 'elf_high'],
    name: '魔琴の奏者',
    rarity: 3,
    power: 3,
    skills: [{ id: 'call', value: 3 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '森の賛歌か愚者への鎮魂歌か。確かなのは、その妖しき調べを耳にしたが最後、大いなる森の軍勢から逃れる術はないということ。',
  },
  {
    id: 'wolf',
    obtain: ['elf_hard', 'elf_high'],
    name: '真夜中の狩人',
    rarity: 3,
    power: 3,
    skills: [{ id: 'legendary' }, { id: 'lone_wolf', value: 3 }],
    voiceCategory: 'wolf',
    flavor:
      '月の光を浴びて強靭な力を得る孤高の戦士。群れを嫌い、独りで獲物を追い詰める。',
  },
  {
    id: 'fire',
    obtain: ['cleric_normal', 'cleric_hard', 'cleric_high'],
    name: '浄化の炎',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'defender' },
      { id: 'artillery', value: 3 },
      { id: 'guardian' },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '異端を焼き払う神聖なる十字。その盾は信徒を守り、砲口は敵への裁きを下す。',
  },
  {
    id: 'punisher',
    obtain: ['cleric_normal', 'cleric_hard', 'cleric_high'],
    name: 'パニッシャー',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'choice', value: 1 },
      { id: 'explode', value: 4 },
    ],
    choices: [
      { id: 'spread', value: 2 },
      { id: 'artillery', value: 2 },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '神罰は上空より舞い降りる。重火器の爆音を讃美歌とし、異端を灰へと還す教会の執行人。',
  },
  {
    id: 'carousel',
    obtain: ['cleric_hard'],
    name: 'カルーセル',
    rarity: 3,
    power: 7,
    skills: [
      { id: 'defender' },
      { id: 'move' },
      { id: 'sturdy' },
      { id: 'immune' },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '重々しい轟音を立てて戦線を移動する、車輪を備えた巨大な鉄盾。古き歯車を軋ませながらあらゆる攻撃を無効化し、味方の絶対的な防壁となる。',
  },
  {
    id: 'empress',
    obtain: ['cleric_hard', 'cleric_high'],
    name: '蒼穹の審判者',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'legendary' },
      { id: 'heal', value: 3 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_female_normal',
    flavor: '宇宙の理を掌るオーブを掲げ、全ての魂に等しく審判を下す聖女。',
  },
  {
    id: 'vampire',
    obtain: ['devilhunter_normal', 'devilhunter_hard', 'devilhunter_high'],
    name: '渇きの王',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'growth', value: -1 },
      { id: 'soul_bind', value: 4 },
    ],
    voiceCategory: 'undead',
    flavor:
      '冷笑を浮かべる夜の支配者. 彼の者に狙われた者は、魂の底まで吸い尽くされる。',
  },
  {
    id: 'graverobber',
    obtain: ['devilhunter_normal', 'devilhunter_hard'],
    name: '優雅な墓荒らし',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'salvage', value: 1 },
      { id: 'resurrect', value: 3 },
    ],
    voiceCategory: 'human_female_normal',
    flavor:
      '朽ちた墓石を踏み躙り、泥に塗れたドレスを優雅に翻す。彼女にとって死者の尊厳など、土に眠る財宝の輝きには遠く及ばないのだ。',
  },
  {
    id: 'beast',
    obtain: ['devilhunter_hard', 'devilhunter_high'],
    name: '廃教会の獣',
    rarity: 3,
    power: 7,
    skills: [{ id: 'loss', value: 4 }],
    voiceCategory: 'wolf',
    flavor:
      '見捨てられた街の大橋に巣くう巨大な獣。自らが何者であったのか、記憶の全てを失ってもなお、主のいない教会を侵入者から守り続けている。',
  },
  {
    id: 'collector',
    obtain: ['devilhunter_hard', 'devilhunter_high'],
    name: 'ヘッドコレクター',
    rarity: 3,
    power: 1,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 3 },
      { id: 'resurrect', value: 8 },
      { id: 'deadly' },
    ],
    voiceCategory: 'undead',
    flavor:
      '集められた数多の魂が慟哭を上げる。彼の者が通り過ぎた後には、首のない骸だけが残される。',
  },
  {
    id: 'book',
    obtain: ['witch_normal', 'witch_hard'],
    name: '禁書目録',
    rarity: 3,
    power: 0,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'resurrect', value: 6 },
      { id: 'charge', value: 3 },
    ],
    voiceCategory: 'magic',
    flavor:
      '禁じられた秘術が記された本。ページを捲るたび、正気は失われ、深淵の知識が魂を蝕んでいく。それでも力に飢えるなら、開くがいい。',
  },
  {
    id: 'witch',
    obtain: ['witch_normal', 'witch_hard'],
    name: '闇の森の魔女',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'choice', value: 1 },
      { id: 'choice', value: 1, choiceGroup: 2 },
    ],
    choices: [
      { id: 'convert', value: 2 },
      { id: 'sacrifice', value: 2 },
    ],
    choices2: [
      { id: 'spread', value: 2 },
      { id: 'lone_wolf', value: 2 },
    ],
    voiceCategory: 'human_female_assassin',
    flavor:
      '森の奥で秘術を操る魔女。恐ろしい噂とは裏腹に、相応の金貨や珍しい素材を前払いすれば、大抵の厄介な依頼はこなしてくれる。',
  },
  {
    id: 'basilisk',
    obtain: ['witch_hard'],
    name: 'バジリスク',
    rarity: 3,
    power: 5,
    skills: [{ id: 'petrify' }],
    voiceCategory: 'snake',
    flavor:
      'その猛毒の視線と交わったが最後。生者の肉体は瞬く間に無機質な彫像へと変わり果て、永遠の沈黙に閉ざされる。',
  },
  {
    id: 'djinn',
    obtain: ['witch_hard', 'witch_high'],
    name: '願いの魔神',
    rarity: 3,
    power: 1,
    skills: [
      { id: 'legendary' },
      { id: 'convert', value: 3 },
      { id: 'choice', value: 3 },
    ],
    choices: [
      { id: 'heal', value: 2 },
      { id: 'draw', value: 2 },
      { id: 'snipe', value: 3 },
      { id: 'spread', value: 2 },
      { id: 'lone_wolf', value: 2 },
      { id: 'support', value: 2 },
    ],
    voiceCategory: 'devil',
    flavor:
      'ランプの底で燻る欲望の煙。それは三度の奇跡となりて、主の運命を静かに狂わせる',
  },
  {
    id: 'fox',
    obtain: ['oni_normal', 'oni_hard', 'oni_high'],
    name: '魂喰いの狐',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'loss', value: 4 },
      { id: 'choice', value: 2 },
    ],
    choices: [
      { id: 'spread', value: 1 },
      { id: 'spread', value: 1 },
      { id: 'summon', value: 1, summonId: 'token_soul' },
      { id: 'summon', value: 1, summonId: 'token_soul' },
    ],
    voiceCategory: 'beast',
    flavor:
      '術者の魂すら喰らう美しくも恐ろしき妖狐。奪った命を呪いの火として撒き散らすか、傀儡として縛り付けるかは彼女の気まぐれ。',
  },
  {
    id: 'tomoe',
    obtain: ['oni_normal', 'oni_hard', 'oni_high'],
    name: '戦姫',
    rarity: 3,
    power: 5,
    skills: [{ id: 'challenge' }, { id: 'quick' }, { id: 'pierce' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '月夜の戦場に舞う女武者。疾風の如き薙刀の刺突が、群がる妖魔を容赦なく貫き伏せる。',
  },
  {
    id: 'kasha',
    obtain: ['oni_hard', 'oni_high'],
    name: '双輪の炎龍',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'takeover' },
      { id: 'quick' },
      { id: 'move' },
      { id: 'brutal', value: 2 },
    ],
    voiceCategory: 'dragon',
    flavor:
      '業火を纏い爆走する厄災の龍。その神速の突進はあらゆる防壁を貫き、戦場を焦土に変え蹂躙し尽くす。',
  },
  {
    id: 'shogun',
    obtain: ['oni_hard', 'oni_high'],
    name: '暁の大将軍',
    rarity: 3,
    power: 9,
    skills: [{ id: 'legendary' }, { id: 'challenge' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '昇る朝日を背に受け、威風堂々と戦場に立つ姿は軍神そのもの。一切の小細工を良しとせず、敵将の首を狙い真っ向から雌雄を決する。',
  },
  {
    id: 'stormpriest',
    obtain: ['priest_normal', 'priest_hard', 'priest_high'],
    name: '嵐の神官',
    rarity: 3,
    power: 2,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'summon', value: 6, summonId: 'token_dragon' },
      { id: 'berserk', value: 2 },
    ],
    voiceCategory: 'human_male_normal',
    flavor:
      '砂の海を統べる神の声を代弁し、軍勢を狂信へと導く神官。彼が杖を天に掲げる時、空は黒雲に覆われ、稲妻を纏った巨大な竜が戦場に顕現する。',
  },
  {
    id: 'goldship',
    obtain: ['priest_normal', 'priest_hard', 'priest_high'],
    name: '太陽の船',
    rarity: 3,
    power: 8,
    skills: [
      { id: 'takeover' },
      { id: 'standby', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'snipe', value: 6 },
      { id: 'intercept', value: 3 },
      { id: 'artillery', value: 3 },
    ],
    voiceCategory: 'machine_old',
    flavor:
      '太古の神々が天空を巡るために建造した黄金の巨大飛行機関。永き眠りから目覚め、失われた叡智の光で地上の不浄を焼き払う。',
  },
  {
    id: 'jackalpriest',
    obtain: ['priest_hard'],
    name: 'ジャッカルの神官',
    rarity: 3,
    power: 5,
    skills: [{ id: 'grave_keeper' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '生と死の境界で魂を導く孤高の番人。王の眠りを妨げる愚者には、無慈悲なジャッカルの牙が突き立てられる。',
  },
  {
    id: 'pharaoh',
    obtain: ['priest_hard', 'priest_high'],
    name: '不朽のファラオ',
    rarity: 3,
    power: 7,
    skills: [
      { id: 'legendary' },
      { id: 'loss', value: 4 },
      { id: 'burial', value: 6 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '神の化身として広大な砂漠を統べる永遠の支配者。その絶大な威光の代償として、仕える者は皆砂の底へと殉死していく。',
  },
  {
    id: 'daemon',
    obtain: [
      'satan_normal',
      'satan_hard',
      'satan_high',
      'void_normal',
      'void_hard',
      'succubus_normal',
      'succubus_hard',
      'warlock_normal',
      'warlock_hard',
    ],
    name: '魔界の尖兵',
    rarity: 3,
    power: 7,
    skills: [{ id: 'sacrifice', value: 3 }],
    voiceCategory: 'devil',
    flavor:
      '強固な力と引き換えに契約者の魂を喰らう悪魔の兵士。その渇望は主ですら例外ではない。',
  },
  {
    id: 'juggernaut',
    obtain: ['satan_hard', 'void_hard', 'succubus_hard', 'warlock_hard'],
    name: 'ジャガーノート',
    rarity: 3,
    power: 10,
    skills: [{ id: 'takeover' }, { id: 'spend', value: 1 }],
    voiceCategory: 'machine_new',
    flavor:
      '圧倒的な質量と装甲で全てを蹂躙する超大型兵器。臨界まで充填されたエネルギーの解放を伴う突撃は、いかなる軍勢をも粉砕する。',
  },
  {
    id: 'great',
    obtain: ['void_normal', 'void_hard'],
    name: '忘れられた英雄',
    rarity: 3,
    power: 8,
    skills: [{ id: 'convert', value: 3 }],
    voiceCategory: 'giant',
    flavor:
      '歴史書から抹消された救世の騎士。今や彼は、かつて愛した世界を蹂躙する最悪の巨城として君臨している。',
  },
  {
    id: 'voidwalker',
    obtain: ['void_hard'],
    name: '虚空歩き',
    rarity: 3,
    power: 5,
    skills: [{ id: 'legendary' }, { id: 'sublimation', value: 2 }],
    voiceCategory: 'stone',
    flavor: '次元の狭間である虚空を自在に渡り歩く、実体を持たない影の旅人。',
  },
  {
    id: 'succubus',
    obtain: ['succubus_normal', 'succubus_hard'],
    name: '大鎌の夢魔',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'loss', value: 2 },
      { id: 'soul_bind', value: 2 },
      { id: 'absorb' },
      { id: 'cleave' },
    ],
    voiceCategory: 'human_female_sexy',
    flavor:
      '宵闇に浮かぶ冷たい微笑み。彼女の振るう大鎌は、命だけでなく、彼らが紡ぐはずだった未来の夢さえも刈り尽くす。',
  },
  {
    id: 'samael',
    obtain: ['succubus_hard'],
    name: '囁く蛇',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 3 },
      { id: 'dominate', value: 6 },
    ],
    voiceCategory: 'snake',
    flavor:
      '暗闇より忍び寄り、甘美な禁忌を囁く魔蛇。唆された者は破滅へと歩む。',
  },
  {
    id: 'spy',
    obtain: ['warlock_normal', 'warlock_hard'],
    name: '悪魔の密偵',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'awake', value: 7, summonId: 'token_daemon' },
    ],
    voiceCategory: 'human_male_trickstar',
    flavor:
      '人々の欲望が渦巻く夜会は、彼にとって最高の狩り場である。優雅な立ち振る舞いで獲物を油断させ、破滅への生贄として漆黒の祭壇へと送り込んでいく。',
  },
  {
    id: 'dread',
    obtain: ['warlock_hard'],
    name: '戦慄の先導者',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 3 },
      { id: 'summon', value: 3, summonId: 'token_skeleton' },
      { id: 'choice', value: 1 },
    ],
    choices: [{ id: 'grant_deadly' }, { id: 'grant_sturdy' }],
    voiceCategory: 'devil',
    flavor:
      '絶望の空の下、悪魔の王は亡者の軍勢を率いる。その黒き矛が示す先にあるのは、絶対的な死と破壊のみ。',
  },
  {
    id: 'bahamut',
    obtain: ['satan_normal', 'satan_hard', 'satan_high'],
    name: '終焉の双頭竜',
    rarity: 3,
    power: 8,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'berserk', value: 3 },
      { id: 'loss', value: 3 },
      { id: 'double_strike' },
    ],
    voiceCategory: 'dragon',
    flavor:
      '二つの首が天を仰ぎ、終末の咆哮を上げる。その翼が振り下ろされる時、世界は劫火に包まれる。',
  },
  {
    id: 'darkgeneral',
    obtain: ['satan_hard', 'satan_high'],
    name: '蒼炎の魔将軍',
    rarity: 3,
    power: 7,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 3 },
      { id: 'execute' },
      { id: 'cull', value: 1 },
      { id: 'cull', value: 1 },
    ],
    voiceCategory: 'horse',
    flavor:
      '冥界より喚び出された不死の軍勢を率いる将軍。彼の通った跡には、青き炎に灼かれた骸と、永遠に続く夜だけが残される。',
  },
  {
    id: 'motorcycle',
    obtain: ['exchange_fortune'],
    name: '”ナイトランナー”',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'defender' },
      { id: 'startup' },
      { id: 'stealth', value: 2 },
      { id: 'move' },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '極限までチューンアップされた駆動系と、排気音すら闇に溶かす規格外の静音機構。闇夜を滑るように疾走する姿から、いつしかその愛称が定着した。',
  },
  {
    id: 'agent',
    obtain: ['exchange_fortune'],
    name: '革命派のエージェント',
    rarity: 3,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'ambush', value: 1, summonId: 'token_automata' },
      { id: 'ambush', value: 1, summonId: 'token_automata' },
    ],
    voiceCategory: 'human_female_assassin',
    flavor:
      '夜の街を自在に駆け抜ける凄腕のエージェント。その鋭い刃は、腐敗した体制を容赦なく切り裂く。',
  },
  {
    id: 'valkyria',
    obtain: ['exchange_fortune'],
    name: '焦熱の戦乙女',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'berserk', value: 3 },
      { id: 'quick' },
      { id: 'dodge', value: 6 },
      { id: 'double_strike' },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '炎のオーラを纏い、強襲を掛ける戦乙女。神速の連撃が、標的を瞬く間に灰燼に帰す。',
  },
  {
    id: 'gungnir',
    obtain: ['exchange_fortune'],
    name: '”巨人殺し”',
    rarity: 3,
    power: 6,
    skills: [
      { id: 'equip' },
      { id: 'legendary' },
      { id: 'salvage', value: 1 },
      { id: 'pierce' },
    ],
    voiceCategory: 'sword',
    flavor: 'かつて天を突く巨躯を貫き、大地に縫い留めたとされる神器。',
  },
  {
    id: 'gaston',
    obtain: ['exchange_high'],
    name: '傲慢な銃士',
    rarity: 3,
    power: 3,
    skills: [
      { id: 'legendary' },
      { id: 'hero', value: 2 },
      { id: 'snipe', value: 3 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '村一番の狩人を自負する男。その腕前以上に、揺るぎない自信だけは誰にも負けない。',
  },
  {
    id: 'rosenberg',
    obtain: ['exchange_high'],
    name: 'ローゼンベルク',
    rarity: 3,
    power: 4,
    skills: [
      { id: 'legendary' },
      { id: 'awake_legendary', value: 8, summonId: 'token_thebeast' },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '野獣の力をその身に宿した女暗殺者。静かな殺意の奥で、獣性が獲物を待ち続ける。',
  },
  {
    id: 'badwolf',
    obtain: ['exchange_defense'],
    name: '幻影の狼',
    rarity: 3,
    power: 2,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'clone', value: 2 },
      { id: 'lone_wolf', value: 2 },
    ],
    voiceCategory: 'wolf',
    flavor:
      '森の深淵に潜む、実体なき銀狼。その姿を見た者は、一頭の獲物を追うつもりが、いつの間にか群れに囲まれていることに気付くのだ。',
  },
  {
    id: 'redhood',
    obtain: ['exchange_defense'],
    name: 'レッドフード',
    rarity: 3,
    power: 3,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'snipe', value: 6 },
      { id: 'spread', value: 2 },
    ],
    voiceCategory: 'human_female_normal',
    flavor:
      '赤い頭巾に隠された鋭い眼光。彼女のクロスボウから放たれる矢は、森の静寂を破ることなく標的の心臓を射抜く。',
  },
  {
    id: 'queen',
    obtain: ['exchange_challenge'],
    name: '嫉妬の女王',
    rarity: 3,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'cull', value: 1 }],
    voiceCategory: 'human_female_cool',
    flavor:
      '”世界で一番美しいのは誰？”——その問いに答える者がいなくなるまで、ただ愚か者を狩り尽くすのみ。',
  },
  {
    id: 'snowwhite',
    obtain: ['exchange_challenge'],
    name: 'スノウホワイト',
    rarity: 3,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'immune' }],
    voiceCategory: 'human_female_assassin',
    flavor:
      '”鏡よ鏡”。いつから私が、毒を盛られて黙っているようなお姫様だと錯覚していた？純白の鎧は復讐の誓い。',
  },
  {
    id: 'threebears',
    obtain: ['exchange_tournament'],
    name: '荒熊山賊団',
    rarity: 3,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'reinforce', value: 2 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '深森を縄張りとする屈強な三兄弟の山賊団。圧倒的な暴力と結束力で、迷い込んだ獲物を決して逃がさない。',
  },
  {
    id: 'goldilocks',
    obtain: ['exchange_tournament'],
    name: 'ゴールデンロックス',
    rarity: 3,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'dodge', value: 5 }],
    voiceCategory: 'human_female_assassin',
    flavor:
      '鮮やかな金髪をなびかせる、孤高の武闘家。彼女は己の魂を震わせる『丁度いい強さ』の相手を求め、各地を放浪している。',
  },
  {
    id: 'whiterider',
    obtain: ['satan_high'],
    name: '征服の使徒',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'contract', value: 4 },
      { id: 'snipe', value: 7 },
      { id: 'guardian' },
    ],
    voiceCategory: 'horse',
    flavor:
      '第一の封印が解かれし時、白馬に乗れる者が現る。彼は征服の上に更なる征服を重ねんとし、その矢は逃れ得ぬ運命を射抜く。',
  },
  {
    id: 'redrider',
    obtain: ['satan_high'],
    name: '戦争の使徒',
    rarity: 4,
    power: 5,
    skills: [{ id: 'contract', value: 4 }, { id: 'quick' }],
    voiceCategory: 'horse',
    flavor:
      '第二の封印。火の如き赤き馬に乗れる者、地上から平和を奪い去る。その大剣が振るわれる時、終わりなき争いの火蓋が切って落とされる。',
  },
  {
    id: 'blackrider',
    obtain: ['satan_high'],
    name: '飢餓の使徒',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'contract', value: 4 },
      { id: 'morph', value: 2 },
      { id: 'deadly' },
    ],
    voiceCategory: 'horse',
    flavor:
      '第三の封印。黒き馬に乗れる者が手にする天秤は、命の価値を量り、世界を等しく飢えと欠乏に陥れる。',
  },
  {
    id: 'palerider',
    obtain: ['satan_high'],
    name: '死の使徒',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'contract', value: 2 },
      { id: 'clone', value: 1 },
    ],
    voiceCategory: 'horse',
    flavor:
      '第四の封印。蒼褪めた馬に乗れる者の名は「死」。その後には黄泉が従い、生きとし生けるもの全てを静寂なる無へと誘う。',
  },
  {
    id: 'gearA',
    obtain: ['android_high'],
    name: 'ストライクギア',
    rarity: 4,
    power: 2,
    skills: [
      { id: 'union', targetId: 'gearB', summonId: 'token_gearC' },
      { id: 'spread', value: 1 },
    ],
    voiceCategory: 'machine_new',
    flavor: '空を切り裂く蒼き翼。それは、来るべき覚醒の時を待つ巨神の半身。',
  },
  {
    id: 'gearB',
    obtain: ['android_high'],
    name: 'グランドギア',
    rarity: 4,
    power: 8,
    skills: [
      { id: 'union', targetId: 'gearA', summonId: 'token_gearC' },
      { id: 'defender' },
      { id: 'artillery', value: 1 },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '地を這う無骨な鉄の脚。その真価は、空飛ぶ半身と交わった時にこそ発揮される。',
  },
  {
    id: 'tank',
    obtain: ['android_high'],
    name: '自律戦車',
    rarity: 4,
    power: 4,
    skills: [
      {
        id: 'union',
        targetId: 'token_drone',
        summonId: 'token_reinforceddrone',
      },
      { id: 'snipe', value: 2 },
    ],
    voiceCategory: 'machine_new',
    flavor: '小型の無人攻撃兵器。',
  },
  {
    id: 'scientist',
    obtain: ['android_high'],
    name: '世紀の天才科学者',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'legendary' },
      { id: 'summon', value: 1, summonId: 'token_drone' },
      { id: 'summon', value: 1, summonId: 'token_drone' },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '彼女の右に出る技術者はいない。その性格の難しさにさえ目を瞑れば、だが。',
  },
  {
    id: 'avenger',
    obtain: ['dragon_high'],
    name: '竜人族の復讐者',
    rarity: 4,
    power: 4,
    skills: [{ id: 'retaliate', value: 2 }],
    voiceCategory: 'sword',
    flavor: '喪われた同胞の痛哭が、鱗をより深く、より凄惨な紅に染め上げる。',
  },
  {
    id: 'wurm',
    obtain: ['dragon_high'],
    name: '文明喰らい',
    rarity: 4,
    power: 7,
    skills: [
      { id: 'takeover' },
      { id: 'berserk', value: 4 },
      { id: 'retaliate', value: 2 },
      { id: 'cleave' },
    ],
    voiceCategory: 'monster',
    flavor:
      '黄金の都を一夜にして飲み込んだ大蠕虫。豊穣のオアシスも尖塔も今は全て腹の中。流砂がかつての繁栄を静かに弔う。',
  },
  {
    id: 'rocktitan',
    obtain: ['dragon_high'],
    name: 'ロックタイタン',
    rarity: 4,
    power: 10,
    skills: [{ id: 'apex' }, { id: 'choice', value: 1 }],
    choices: [{ id: 'immune' }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor:
      '大地より生まれし不屈の巨神。その硬躯は、いかなる災厄をも跳ね返す。',
  },
  {
    id: 'hellkite',
    obtain: ['dragon_high'],
    name: 'ヘルカイトの君主',
    rarity: 4,
    power: 10,
    skills: [
      { id: 'legendary' },
      { id: 'apex' },
      { id: 'berserk', value: 6 },
      { id: 'spread', value: 6 },
    ],
    voiceCategory: 'dragon',
    flavor:
      '「黒き影が空を覆う時、古き王国は灰となる」というただの御伽話。だがある日空は黒く染まり、伝説は業火と共に舞い降りた。',
  },
  {
    id: 'darkpaladin',
    obtain: ['knight_high'],
    name: '闇の聖騎士',
    rarity: 4,
    power: 5,
    skills: [{ id: 'substitute' }],
    voiceCategory: 'sword',
    flavor:
      '「勝利のためなら、味方の命すらも捨て石にすぎん。」黒鉄の鎧に身を包んだ冷徹な騎士。',
  },
  {
    id: 'elite',
    obtain: ['knight_high'],
    name: 'ギルドの特級剣士',
    rarity: 4,
    power: 4,
    skills: [{ id: 'adversity', value: 2 }],
    voiceCategory: 'human_female_normal',
    flavor:
      '優雅な気品を湛える剣士。敵に包囲される逆境下でこそ、研ぎ澄まされた鋭い剣技を披露する。',
  },
  {
    id: 'guildmaster',
    obtain: ['knight_high'],
    name: 'ギルドの支配人',
    rarity: 4,
    power: 1,
    skills: [
      { id: 'draw', value: 1 },
      { id: 'choice', value: 1 },
    ],
    choices: [{ id: 'support', value: 3 }, { id: 'deadly' }],
    voiceCategory: 'human_male_normal',
    flavor: 'その指先ひとつで街の経済が回り、裏社会の命運が決まる。',
  },
  {
    id: 'duelist',
    obtain: ['knight_high'],
    name: '血濡れの決闘者',
    rarity: 4,
    power: 4,
    skills: [
      { id: 'legendary' },
      { id: 'sacrifice', value: 2 },
      { id: 'hero', value: 2 },
      { id: 'adversity', value: 2 },
    ],
    voiceCategory: 'human_male_warrior',
    flavor:
      '無慈悲に命を刈り取る殺戮者。肉体が切り刻まれようと、血の海で最後まで立ち尽くし標的を屠る。',
  },
  {
    id: 'starfish',
    obtain: ['cthulhu_high'],
    name: '旧世界からの使者',
    rarity: 4,
    power: 5,
    skills: [
      { id: 'convert', value: 2 },
      { id: 'morph', value: 2 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '人類の歴史より遥か昔、深き水底から遣わされた先触れ。地上に現れる時、世界に大いなる変革が訪れる。',
  },
  {
    id: 'trapezohedron',
    obtain: ['cthulhu_high'],
    name: 'トラペゾヘドロン',
    rarity: 4,
    power: 0,
    skills: [{ id: 'invite' }],
    voiceCategory: 'magic',
    flavor:
      '異なる次元への扉を開く多面体。深淵を覗き込むとき、そこから恐るべきものが呼び出される。',
  },
  {
    id: 'shoggoth',
    obtain: ['cthulhu_high'],
    name: '蠢く泥塊',
    rarity: 4,
    power: 2,
    skills: [{ id: 'double_power' }],
    voiceCategory: 'monster',
    flavor:
      '黒き粘液で構成された不定形の怪物。増殖と分裂を繰り返し、際限なく膨張していく。',
  },
  {
    id: 'cthulhu',
    obtain: ['cthulhu_high'],
    name: '大いなる支配者',
    rarity: 4,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'takeover' },
      { id: 'choice', value: 2 },
    ],
    choices: [
      { id: 'double_power' },
      { id: 'double_power' },
      { id: 'clone', value: 1 },
      { id: 'clone', value: 1 },
    ],
    voiceCategory: 'monster',
    flavor:
      'その姿を視認した瞬間、あらゆる物理法則は崩壊を始める。無限の絶望を増殖させていく絶対の主。',
  },
  {
    id: 'piper',
    obtain: ['elf_high'],
    name: 'サテュロスの笛吹き',
    rarity: 4,
    power: 3,
    skills: [{ id: 'explore' }],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '陽気な笛の音が響く時、木々は枝を揺らし、密やかな抜け道を旅人に提示する。',
  },
  {
    id: 'cuchulainn',
    obtain: ['elf_high'],
    name: '追憶の魔槍使い',
    rarity: 4,
    power: 3,
    skills: [
      { id: 'loss', value: 4 },
      { id: 'snipe', value: 6 },
      { id: 'pierce' },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '色褪せた記憶の中にあっても、呪われし槍の切っ先は恐ろしいほどに冴え渡る。',
  },
  {
    id: 'rampage',
    obtain: ['elf_high'],
    name: 'ランペイジ',
    rarity: 4,
    power: 0,
    skills: [
      { id: 'takeover' },
      { id: 'call', value: 3 },
      { id: 'call', value: 3 },
    ],
    voiceCategory: 'magic',
    flavor: '一本の木が切り倒された時、無数の獣たちが目を覚ました。',
  },
  {
    id: 'elfking',
    obtain: ['elf_high'],
    name: 'エルフの王',
    rarity: 4,
    power: 4,
    skills: [{ id: 'legendary' }, { id: 'call', value: 4 }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '千年の時を統べるエルフの王。彼の声が響く時、森の全てが呼応し、侵略者をなぎ払う軍勢と化す。',
  },
  {
    id: 'father',
    obtain: ['cleric_high'],
    name: '銀弾の神父',
    rarity: 4,
    power: 2,
    skills: [{ id: 'choice', value: 2 }],
    choices: [
      { id: 'snipe', value: 2 },
      { id: 'snipe', value: 2 },
      { id: 'artillery', value: 1 },
      { id: 'artillery', value: 1 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '聖なる銀弾を込めた銃を携える神父。彼の祈りは邪悪を穿ち、その弾丸は罪人を浄化する。',
  },
  {
    id: 'punishment',
    obtain: ['cleric_high'],
    name: '神罰',
    rarity: 4,
    power: 0,
    skills: [
      { id: 'sacrifice', value: 2 },
      { id: 'choice', value: 1 },
    ],
    choices: [
      { id: 'artillery', value: 3 },
      { id: 'spread', value: 3 },
    ],
    voiceCategory: 'magic',
    flavor: '天より降り注ぐ理不尽なる裁き。神の砲撃は敵陣を焼き尽くす。',
  },
  {
    id: 'spirit',
    obtain: ['cleric_high'],
    name: 'ブラザー・オブ・オース',
    rarity: 4,
    power: 5,
    skills: [{ id: 'possession' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      'かつて背中を預け合った戦友との誓いが、彼を不屈の精霊へと変えた。その魂は今もなお、忠義という名の炎で燃え続けている。',
  },
  {
    id: 'goddess',
    obtain: ['cleric_high'],
    name: '勝利の女神',
    rarity: 4,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'possession' }, { id: 'absorb' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '戦場を舞う美しき女神。彼女が微笑む時、勝利の天秤は静かに傾き、受けるべき傷は運命の導きによって癒やしへと変わる。',
  },
  {
    id: 'dragonzombie',
    obtain: ['devilhunter_high'],
    name: '継ぎ接ぎの擬竜',
    rarity: 4,
    power: 8,
    skills: [{ id: 'decay' }],
    voiceCategory: 'undead',
    flavor:
      '竜の威容を模して、数多の獣の屍を縫い合わせた歪な肉塊。その巨大な体躯は維持するだけで崩壊を始める。',
  },
  {
    id: 'grimreaper',
    obtain: ['devilhunter_high'],
    name: '死神',
    rarity: 4,
    power: 6,
    skills: [{ id: 'takeover' }, { id: 'cleave' }, { id: 'deadly' }],
    voiceCategory: 'undead',
    flavor:
      '音もなく現れ、音もなく命を刈り取る。その大鎌が一閃する時、生きとし生ける者は等しく無へと還る。',
  },
  {
    id: 'puppeteer',
    obtain: ['devilhunter_high'],
    name: '放浪傀儡師',
    rarity: 4,
    power: 2,
    skills: [{ id: 'puppet', value: 5 }],
    voiceCategory: 'human_male_trickstar',
    flavor:
      '煙渦巻く戦場を渡り歩く、異色の傭兵。その手腕は、極めて非情で効率的である。',
  },
  {
    id: 'doll',
    obtain: ['devilhunter_high'],
    name: '人形館の主',
    rarity: 4,
    power: 2,
    skills: [
      { id: 'legendary' },
      { id: 'loss', value: 4 },
      { id: 'bind', value: 2 },
      { id: 'puppet', value: 8 },
    ],
    voiceCategory: 'human_female_cute',
    flavor:
      '洋館の奥深くに座す精巧な少女の人形。足を踏み入れた客人をもてなし、二度と外へ帰ることのない調度品へと変えていく。',
  },
  {
    id: 'student',
    obtain: ['witch_high'],
    name: '勤勉な留学生',
    rarity: 4,
    power: 3,
    skills: [{ id: 'chant', value: 0 }],
    voiceCategory: 'beast',
    flavor:
      '魔法を学ぶためアカデミーの門を叩いた若き獣人。不慣れな言語の魔導書と格闘しながら、ひたむきに詠唱の練習を続けている。',
  },
  {
    id: 'archmage',
    obtain: ['witch_high'],
    name: '異端のアークメイジ',
    rarity: 4,
    power: 4,
    skills: [
      { id: 'sacrifice', value: 3 },
      { id: 'chant', value: 3 },
    ],
    voiceCategory: 'human_male_old',
    flavor:
      '規格外の魔導士。星を砕く極大魔法を紡ぐためならば、己の血肉すら代償として捧げる覚悟を持つ。',
  },
  {
    id: 'philosopher',
    obtain: ['witch_high'],
    name: '賢者の石',
    rarity: 4,
    power: 0,
    skills: [{ id: 'convert', value: 1 }, { id: 'leap' }],
    voiceCategory: 'magic',
    flavor:
      '探求者たちが生涯を捧げて到達した至高の結晶。その深紅の輝きは、存在を代償に次元を超える奇跡を起こす。',
  },
  {
    id: 'gorgon',
    obtain: ['witch_high'],
    name: '魔眼の勇者',
    rarity: 4,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'petrify' }, { id: 'double_strike' }],
    voiceCategory: 'human_female_cool',
    flavor:
      '蛇の髪を持つ美しき戦乙女。その一瞥を受けた者は石と化し、剣の一閃は必殺の一撃となる。',
  },
  {
    id: 'kunoichi',
    obtain: ['oni_high'],
    name: '双牙衆の刺客',
    rarity: 4,
    power: 3,
    skills: [
      { id: 'convert', value: 1 },
      { id: 'sacrifice', value: 1 },
      { id: 'summon', value: 3, summonId: 'token_whitewolf' },
      { id: 'arm_self' },
    ],
    voiceCategory: 'human_female_normal',
    flavor:
      '己の血と痛みを代償に、獣を喚び出す双牙衆の忍者。静寂を裂く刃と鋭い牙が、連携して標的を確実に仕留める。',
  },
  {
    id: 'benkei',
    obtain: ['oni_high'],
    name: '刀狩りの豪傑',
    rarity: 4,
    power: 4,
    skills: [{ id: 'arm_self' }, { id: 'pierce' }],
    voiceCategory: 'human_male_warrior',
    flavor:
      '敗者の武具を奪い、己の力へと変える。その桁外れの剛腕から繰り出される一撃は、いかなる盾をも容易く貫く。',
  },
  {
    id: 'orochi',
    obtain: ['oni_high'],
    name: '神々の宿敵',
    rarity: 4,
    power: 6,
    skills: [
      { id: 'brutal', value: 6 },
      { id: 'double_strike' },
      { id: 'cleave' },
    ],
    voiceCategory: 'snake',
    flavor:
      '贄の血の匂いに惹かれ、古の厄災が目を覚ます。八つの顎がもたらすのは、すべてを無に帰す純粋な破壊のみ。',
  },
  {
    id: 'seimei',
    obtain: ['oni_high'],
    name: '天眼の陰陽師',
    rarity: 4,
    power: 6,
    skills: [{ id: 'legendary' }, { id: 'choice', value: 1 }],
    choices: [
      { id: 'seal', value: 1 },
      { id: 'bind', value: 1 },
    ],
    voiceCategory: 'human_male_ikemen',
    flavor:
      '森羅万象を見通すその眼差しに、死角はない。涼やかな指先が印を結べば、標的は抗う間もなく縛に就く。',
  },
  {
    id: 'highwayman',
    obtain: ['priest_high'],
    name: '裏切りの相棒',
    rarity: 4,
    power: 4,
    skills: [{ id: 'force', value: 1 }],
    choices: [
      { id: 'artillery', value: 2 },
      { id: 'morph', value: 2 },
    ],
    voiceCategory: 'human_male_normal',
    flavor:
      '幾重もの危険な罠を共にくぐり抜けた探検の友は、最奥で目当ての財宝を手にした瞬間に冷酷な本性を現す。',
  },
  {
    id: 'sphinx',
    obtain: ['priest_high'],
    name: '難題の問い手',
    rarity: 4,
    power: 4,
    skills: [{ id: 'force', value: 1 }],
    choices: [
      { id: 'lone_wolf', value: 2 },
      { id: 'clone', value: 1 },
    ],
    voiceCategory: 'human_male_old',
    flavor:
      '神域へ足を踏み入れた者の前に立ち塞がる黄金の獣。その難解な問いに答えられぬ者は、容赦なく熱砂の底へ葬られる。',
  },
  {
    id: 'uroboros',
    obtain: ['priest_high'],
    name: '白銀の円環',
    rarity: 4,
    power: 5,
    skills: [{ id: 'samsara' }],
    voiceCategory: 'snake',
    flavor:
      '始まりは終わりであり、終わりは始まり。白銀の円環は、永遠に続く死と再生を紡ぎ出す。',
  },
  {
    id: 'cleopatra',
    obtain: ['priest_high'],
    name: '最後の女王',
    rarity: 4,
    power: 4,
    skills: [
      { id: 'legendary' },
      { id: 'dominate', value: 5 },
      { id: 'execute' },
    ],
    voiceCategory: 'human_female_cool',
    flavor:
      '傾きゆく帝国を、美貌と知略で支え続けた統治者。彼女が下した最後の冷徹な決断は、かつての栄華と共に歴史の闇へ消えた。',
  },
  {
    id: 'light',
    obtain: ['achievement'],
    name: '無垢の光',
    rarity: 4,
    power: 5,
    skills: [{ id: 'oblivion' }],
    voiceCategory: 'human_female_cute',
    flavor:
      '優しく降り注ぐ、穢れなき無垢の光。苦しみも、悪意も、自分が何者であったかさえも安らかに白く溶け落ちていく。',
  },
  {
    id: 'baldanders',
    obtain: ['achievement'],
    name: 'バルトアンデルス',
    rarity: 4,
    power: 0,
    skills: [{ id: 'metamorph' }],
    voiceCategory: 'stone',
    flavor:
      '変幻自在の魔力を持つ怪人。その姿を捉えることはできず、あらゆる存在へと形を変える。',
  },
  {
    id: 'shuffler',
    obtain: ['achievement'],
    name: 'シャッフラー',
    rarity: 4,
    power: 5,
    skills: [{ id: 'shuffle' }],
    voiceCategory: 'human_male_trickstar',
    flavor:
      'その奇怪な手品師がカードを切り混ぜる時、確かなはずの未来さえも白紙に戻る。',
  },
  {
    id: 'crown',
    obtain: ['achievement'],
    name: '道化師',
    rarity: 4,
    power: 5,
    skills: [{ id: 'teleport' }],
    voiceCategory: 'human_male_trickstar',
    flavor:
      '狂おしき道化師が舞台に立つ時、戦場は血塗られたサーカスへと変わる。残るのは幻影と、抗えぬ絶望のみ。',
  },
  {
    id: 'scarecrow',
    obtain: ['achievement'],
    name: '呪いの案山子',
    power: 1,
    rarity: 4,
    skills: [{ id: 'reflect' }],
    voiceCategory: 'undead',
    flavor:
      '燃やそうとした者は黒焦げになり、切り刻もうとした者は四肢を失った。案山子は何事もなかったかのように、今日も畑に立っている。',
  },
  {
    id: 'invader',
    obtain: ['achievement'],
    name: '彼方からの侵略者',
    rarity: 4,
    power: 0,
    skills: [{ id: 'invade' }],
    voiceCategory: 'beast',
    flavor:
      '星の海を渡り、あらゆる次元を喰らい尽くす。彼らにとって、この世界もただの餌場に過ぎない。',
  },
  {
    id: 'dicejuggler',
    obtain: ['achievement'],
    name: 'ダイスジャグラー',
    rarity: 4,
    power: 5,
    skills: [{ id: 'fate' }],
    voiceCategory: 'human_male_trickstar',
    flavor: '賽は投げられた。君の幸運を祈ろう……できれば、私自身にもね。',
  },
  {
    id: 'jason',
    obtain: ['achievement'],
    name: '不吉な殺人鬼',
    rarity: 4,
    power: 0,
    skills: [{ id: 'portent' }],
    voiceCategory: 'sword',
    flavor: '流れた血の数だけ殺意は研ぎ澄まされ、惨劇の夜を繰り返す。',
  },
  {
    id: 'homunculus',
    obtain: ['achievement'],
    name: 'ホムンクルスの実験体',
    power: 0,
    skills: [{ id: 'replicate' }],
    rarity: 4,
    voiceCategory: 'stone',
    flavor:
      '欠落した半身を埋めるため、未完成のホムンクルスは強者の力を模倣する。鏡に映る己が完全な存在であると信じて。',
  },
  {
    id: 'bell',
    obtain: ['achievement'],
    name: '葬送の鐘',
    rarity: 4,
    power: 0,
    skills: [{ id: 'decree' }],
    voiceCategory: 'magic',
    flavor:
      '鳴り響く鐘の音は、終焉の宣告。その音を聞いた者に、逃れる術はない。',
  },

  // トークンカード
  {
    id: 'token_knight',
    obtain: ['token'],
    name: '騎士',
    power: 2,
    isToken: true,
    voiceCategory: 'sword',
    flavor: '訓練を受けた騎士。',
  },
  {
    id: 'token_dragon',
    obtain: ['token'],
    name: 'ドラゴン',
    power: 6,
    isToken: true,
    voiceCategory: 'dragon',
    flavor: '空の支配者。',
  },
  {
    id: 'token_ignis',
    obtain: ['token'],
    name: 'イグニス',
    power: 7,
    isToken: true,
    skills: [{ id: 'legendary' }],
    flavor: '降臨した竜族の姫。',
  },
  {
    id: 'token_satan',
    obtain: ['token'],
    name: '魔王の化身',
    power: 10,
    isToken: true,
    flavor: '魔王サタンの強大な化身。',
  },
  {
    id: 'token_clone',
    obtain: ['token'],
    name: '分身',
    power: 1,
    isToken: true,
    flavor: '本体から生み出された分身。',
  },
  {
    id: 'token_reinforce',
    obtain: ['token'],
    name: '増援',
    power: 4,
    isToken: true,
    flavor: '呼び声に応え、現れた仲間。',
  },
  {
    id: 'token_legs',
    obtain: ['token'],
    name: '蛸足',
    power: 2,
    isToken: true,
    voiceCategory: 'sea',
    flavor: '切り離されてもなお蠢き続ける蛸の足。',
  },
  {
    id: 'token_void',
    obtain: ['token'],
    name: '虚空',
    power: 0,
    isToken: true,
    voiceCategory: 'stone',
    flavor:
      '形なき虚無の欠片。それは何も生み出さず、ただそこにあるだけの空虚。',
  },
  {
    id: 'token_ent',
    obtain: ['token'],
    name: 'エント',
    power: 5,
    isToken: true,
    voiceCategory: 'stone',
    flavor:
      '永き眠りから目覚めた大樹の精霊。森を脅かす者には、容赦のない鉄槌が下される。',
  },
  {
    id: 'token_statue',
    obtain: ['token'],
    name: '石像',
    power: 5,
    isToken: true,
    skills: [{ id: 'defender' }, { id: 'sturdy' }],
    voiceCategory: 'stone',
    flavor: '石化させられた哀れな姿。',
  },
  {
    id: 'token_drone',
    obtain: ['token'],
    name: 'ドローン',
    power: 1,
    isToken: true,
    voiceCategory: 'machine_new',
    flavor: '小型の索敵無人機。',
  },
  {
    id: 'token_golem',
    obtain: ['token'],
    name: 'ゴーレム',
    power: 5,
    isToken: true,
    voiceCategory: 'stone',
    flavor: '土と石で構成された自律型の魔法生物。',
  },
  {
    id: 'token_phoenix',
    obtain: ['token'],
    name: 'フェニックス',
    power: 6,
    isToken: true,
    voiceCategory: 'bird',
    flavor: '蘇った不死鳥。',
  },
  {
    id: 'token_soul',
    obtain: ['token'],
    name: '人魂',
    power: 1,
    isToken: true,
    voiceCategory: 'undead',
    flavor: '彷徨う人魂。',
  },
  {
    id: 'token_gearC',
    obtain: ['token'],
    name: '機神プロメテウス',
    power: 10,
    isToken: true,
    skills: [
      { id: 'spread', value: 3 },
      { id: 'artillery', value: 2 },
      { id: 'immune' },
    ],
    voiceCategory: 'machine_new',
    flavor:
      '天と地が交わり、鋼の機神が目を覚ます。その圧倒的な火力の前では、いかなる装甲も意味を成さない。',
  },
  {
    id: 'token_reinforceddrone',
    obtain: ['token'],
    name: '強化ドローン',
    power: 5,
    isToken: true,
    skills: [
      { id: 'snipe', value: 2 },
      { id: 'snipe', value: 2 },
      { id: 'snipe', value: 2 },
    ],
    voiceCategory: 'machine_new',
    flavor: '強化されたドローン。',
  },
  {
    id: 'token_polarbear',
    obtain: ['token'],
    name: 'ヴォイテク',
    power: 4,
    isToken: true,
    skills: [{ id: 'legendary' }, { id: 'pierce' }],
    voiceCategory: 'beast',
    flavor: 'リナと共に戦う白熊',
  },
  {
    id: 'token_daemon',
    obtain: ['token'],
    name: 'デーモン',
    power: 7,
    isToken: true,
    voiceCategory: 'devil',
    flavor: '契約により姿を現した悪魔。',
  },
  {
    id: 'token_angel',
    obtain: ['token'],
    name: '天使',
    power: 7,
    isToken: true,
    voiceCategory: 'human_female_cool',
    flavor: '祈りに応えた天使',
  },
  {
    id: 'token_whitewolf',
    obtain: ['token'],
    name: '白狼',
    power: 3,
    isToken: true,
    voiceCategory: 'wolf',
    flavor: '忍びの相棒',
  },
  {
    id: 'token_skeleton',
    obtain: ['token'],
    name: 'スケルトン',
    power: 3,
    isToken: true,
    voiceCategory: 'undead',
    flavor: '再生したスケルトン',
  },
  {
    id: 'token_automata',
    obtain: ['token'],
    name: 'オートマタ',
    power: 1,
    isToken: true,
    voiceCategory: 'machine_new',
    flavor: '暴走した自律人形',
  },
  {
    id: 'token_thebeast',
    obtain: ['token'],
    name: 'ザ・ビースト',
    power: 8,
    isToken: true,
    voiceCategory: 'beast',
    skills: [{ id: 'legendary' }],
    flavor: '内なる野獣の姿',
  },
];

// プレミアムカードとして解放可能なすべてのカードIDのリスト (網羅性を保証し、DRY原則を適用)
export const PREMIUM_CARD_IDS = [
  // --- 実績 ---
  'cleric',
  'cyberman',
  'dancer',
  'commander',
  'eye',
  'pray',
  'necromancer',
  'beginnermagic',
  'omyouji',
  'mummy',
  'light',
  // --- 防衛戦：交換所：ゴールド ---
  'cyborgninja',
  'cyberdragon',
  'dragoon',
  'dragon',
  'assassin',
  'champion',
  'hound',
  'oldgod',
  'caller',
  'wolf',
  'punisher',
  'empress',
  'vampire',
  'collector',
  'witch',
  'djinn',
  'fox',
  'shogun',
  'stormpriest',
  'pharaoh',
  'voidwalker',
  'samael',
  'dread',
  'darkgeneral',
  'motorcycle',
  'gungnir',
  // --- 防衛戦：交換所：シルバー ---
  'dreadnought',
  'armsuits',
  'babydragon',
  'berserker',
  'horse',
  'crusher',
  'shark',
  'parasite',
  'shaman',
  'darkelf',
  'doom',
  'acolyte',
  'plaguedoctor',
  'servant',
  'ring',
  'battlemage',
  'yukionna',
  'muramasa',
  'kitepriest',
  'snakepriest',
  'bountyhunter',
  'alraune',
  'priestess',
  'cavalry',
  'employee',
  'mjolnir',
  // --- 運命の邂逅 ---
  'liberator',
  'dwarf',
  // --- シリアルコード ---
  'sniper',
  'cheetah',
  'tortoise',
];
