export const UI_IMAGES = {
  MENU_SOLO: 'assets/ui/ui_solobutton01.png',
  MENU_STORY: 'assets/ui/ui_storybutton01.png',
  MENU_PRACTICE: 'assets/ui/ui_practice01.png',
  MENU_EVENT: 'assets/ui/ui_eventbutton01.png',
  MENU_RULES: 'assets/ui/ui_rulebutton01.png',
  MENU_FREE: 'assets/ui/ui_freebattlebutton01.png',
  MENU_GALLERY: 'assets/ui/ui_gallerybutton01.png',
  EVENT_HIGH_DIFF: 'assets/ui/ui_event_highdiffbutton01.png',
  EVENT_DEFENSE: 'assets/ui/ui_event_defensebutton01.png',
  GALLERY_CARD_LIST: 'assets/ui/ui_cardlistbutton01.png',
  GALLERY_ACHIEVEMENTS: 'assets/ui/ui_achievementsbutton01.png',
  MENU_DUNGEON: 'assets/ui/ui_dungionbutton01.png',
  MENU_ONLINE: 'assets/ui/ui_versusbutton01.png',
  MENU_DECK: 'assets/ui/ui_deckbutton01.png',
  EVENT_TOURNAMENT: 'assets/ui/ui_event_tournament01.png',
  GUIDE_RULES: 'assets/ui/ui_Instructionsbutton01.png',
  GUIDE_TUTORIAL: 'assets/ui/ui_tutorialbutton01.png',
  EVENT_FORTUNE: '',
};
