/**
 * Mini Card Battle - Card Master Data
 */
const CARD_MASTER = [
    { id: 'golem', name: '大理石のゴーレム', power: 5, skill: 'none', rarity: 1, flavor: '魔法によって生命を吹き込まれた大理石の彫像。美しさと硬固さを兼ね備えている。' },
    { id: 'sniper', name: '森の射手', power: 2, skill: 'snipe', skillValue: 4, rarity: 1, flavor: '静寂に包まれた深い森を守るエルフの狩人。その矢は木の葉の間を縫い、目標を違わず射抜く。' },
    { id: 'diviner', name: '星詠みの占術士', power: 4, skill: 'draw', skillValue: 2, rarity: 1, flavor: '天球の運行を読み解き、運命の糸を紡ぎ直す導き手。' },
    { id: 'clone', name: '鏡の戦士', power: 2, skill: 'clone', skillValue: 1, rarity: 1, flavor: '妖精の鏡から這い出した実体のない騎士。本体と寸分違わぬ動きで幻惑する。' },
    { id: 'dinosaur', name: '古代の大蜥蜴', power: 8, skill: 'takeover', rarity: 1, flavor: '古代の息吹を宿す巨大な爬虫類。その巨体を現すには、相応の代償が必要となる。', imgUrl: 'assets/card_dinosaur.jpg' },
    { id: 'cheetah', name: '稲妻の猟豹', power: 2, skill: 'quick', rarity: 1, flavor: '稲妻を纏って戦場を駆ける最速の野獣。その爪が空気を切り裂く。' },
    { id: 'scorpion', name: '黒サソリ', power: 2, skill: 'deadly', rarity: 1, flavor: '夜の砂漠に潜む漆黒の巨蠍。その尾から放たれる猛毒は対象を一瞬で絶命させる。' },
    { id: 'cleric', name: '見習い修道女', power: 3, skill: 'heal', skillValue: 2, rarity: 1, flavor: '救済を志し修業に励む乙女。未熟ながらもその祈りは傷ついた心を癒やす。' },
    { id: 'wall', name: '城壁', power: 10, skill: 'defender', rarity: 1, flavor: '幾多の戦火を耐え抜いた鉄壁の防塁。王国の平和を守り続ける沈黙の守護者。' },
    { id: 'ninja', name: '忍者', power: 2, skill: 'stealth', skillValue: 1, rarity: 1, flavor: '影に潜み、音もなく標的に近づく工作員。その姿を捉えることは困難である。', imgUrl: 'assets/card_ninja.jpg' },
    { id: 'charger', name: '虹ハチドリ', power: 1, skill: 'charge', skillValue: 1, rarity: 1, flavor: '七色の翼を持つ小さな鳥。その羽ばたきは見る者に活力を与える。', imgUrl: 'assets/card_charger.jpg' },
    { id: 'crenellatedwall', name: '民兵団の射手', power: 5, skills: [{ id: 'spread', value: 1 }, { id: 'defender' }], rarity: 1, flavor: '故郷を守るために立ち上がった志願兵たち。門の内側から放たれる矢は、侵略者を決して逃さない。', imgUrl: 'assets/card_crenellatedwall.jpg' },
    { id: 'titan', name: '旧式タイタン', power: 8, skill: 'growth', skillValue: -2, rarity: 2, flavor: '古代文明の造兵兵器。旧式ながらもその重厚な装甲は今なお健在である。', imgUrl: 'assets/card_titan.jpg' },
    { id: 'mantis', name: '旧式マンティス', power: 3, skills: [{ id: 'quick' }, { id: 'growth', value: -3 }], rarity: 2, flavor: '旧式の巨大なカマキリのロボット。鋭い鎌で獲物を伏せるが、過負荷による出力低下が激しい。', imgUrl: 'assets/card_mantis.jpg' },
    { id: 'bigai', name: 'サイクロプス Mk-II', power: 3, skills: [{ id: 'charge', value: -2 }, { id: 'snipe', value: 5 }], rarity: 2, flavor: '単眼の狙撃特化型自律ユニット。一撃必殺の精度を誇る。', imgUrl: 'assets/card_bigai.jpg' },
    { id: 'babydragon', name: 'ドラゴンの雛', power: 2, skill: 'growth', skillValue: 3, rarity: 2, flavor: 'まだ小さなドラゴンの幼体。秘めたる魔力は無限の可能性を感じさせる。' },
    { id: 'commander', name: '前線の司令官', power: 3, skill: 'support', skillValue: 2, rarity: 2, flavor: '最前線で兵を鼓舞し続ける老将。彼の掲げる軍旗は兵士たちの士気を極限まで高める。' },
    { id: 'bard', name: '森の歌うたい', power: 1, skills: [{ id: 'support', value: 2 }, { id: 'heal', value: 2 }], rarity: 2, flavor: 'ウクレレを奏でる彼を、森の動物たちは親しみを持って「先生」と呼ぶ。その歌声は傷ついた心も体も癒やす。', imgUrl: 'assets/card_bard.jpg' },
    { id: 'spider', name: 'スパイダー', power: 3, skill: 'bind', skillValue: 1, rarity: 2, flavor: '暗闇に潜み、粘着質の糸を紡ぐ毒蜘蛛。獲物の自由を奪い、死の抱擁へと誘う。' },
    { id: 'mage', name: '学院の雷撃魔導士', power: 2, skill: 'spread', skillValue: 2, rarity: 2, flavor: '魔導アカデミーの雷撃魔導士。周囲の魔力を吸収し、雷撃を放つ。' },
    { id: 'shade', name: '墓の亡霊', power: 4, skill: 'soul_bind', skillValue: 2, rarity: 2, flavor: '古い墓地に漂う無念の霧。生者の温もりを嫌い、その魂を冷たい死の淵へと引き摺り込む。' },
    { id: 'dealer', name: 'デビル・ディーラー', power: 4, skills: [{ id: 'draw', value: 4 }, { id: 'sacrifice', value: 2 }], rarity: 2, flavor: '「さあ、運命を選びな。代償は君の魂で十分だ。」不敵な笑みを浮かべる悪魔の占い師。', imgUrl: 'assets/card_dealer.jpg' },
    { id: 'tortoise', name: '鉄亀', power: 4, skill: 'sturdy', rarity: 2, flavor: '鉱石を食べて成長し、鋼鉄の如き硬度を得た霊亀。物理的な衝撃をほぼ無効化する。' },
    { id: 'berserker', name: '狂戦士', power: 7, skill: 'berserk', skillValue: 2, rarity: 2, flavor: '破壊の衝動に魂を売った禁忌の戦士。痛みすら悦びとして斧を振り回す。' },
    { id: 'lightpaladin', name: '光の聖騎士', power: 5, skill: 'guardian', rarity: 2, flavor: '「我が盾は、共に戦う友のためにある。」気高き精神を宿した聖なる騎士。', imgUrl: 'assets/card_lightpaladin.jpg' },
    { id: 'darkpaladin', name: '闇の聖騎士', power: 5, skills: [{ id: 'deadly' }, { id: 'sacrifice', value: 2 }], rarity: 2, flavor: '「勝利のためなら、この命すらも捨て石にすぎん。」黒鉄の鎧に身を包んだ冷徹な騎士。', imgUrl: 'assets/card_darkpaladin.jpg' },
    { id: 'copy', name: 'ホムンクルスの実験体', power: 1, skill: 'copy', rarity: 2, flavor: '錬金術の過程で生み出された不安定な生命。周囲の情報を読み取り、その姿を不完全に模倣する。' },
    { id: 'cyberdragoon', name: '試作型ドラグーン', power: 5, skills: [{ id: 'spread', value: 3 }, { id: 'charge', value: -3 }, { id: 'legendary' }], rarity: 3, flavor: '試作型の重機動兵器。圧倒的な面制圧力を持つ。', imgUrl: 'assets/card_cyberdragon.jpg' },
    { id: 'cyberman', name: 'ライオット・キーパー', power: 6, skills: [{ id: 'charge', value: -1 }], rarity: 3, flavor: '「システム始動……これより排除を開始する。」最新型の暴徒鎮圧用ドロイド。', imgUrl: 'assets/card_cyberman.jpg' },
    { id: 'dragon', name: 'ファイア・ドラゴン', power: 6, skills: [{ id: 'spread', value: 2 }, { id: 'berserk', value: 2 }, { id: 'legendary' }], rarity: 3, flavor: '炎を纏った紅蓮の翼。その咆哮は敵を焼き払い、荒ぶる魔力は周囲をも巻き込む。' },
    { id: 'warlock', name: '猛火の大魔導士', power: 3, skills: [{ id: 'berserk', value: 4 }, { id: 'spread', value: 4 }, { id: 'sacrifice', value: 4 }], rarity: 3, flavor: '真っ赤な業火を操る老人の魔法使い。その魔力は周囲を焼き尽くし、代償として自身の命も削る。', imgUrl: 'assets/card_warlock.jpg' },
    { id: 'champion', name: 'アリーナのチャンピオン', power: 1, skills: [{ id: 'hero', value: 3 }, { id: 'legendary' }], rarity: 3, flavor: '観衆の歓声こそが彼の力。その雄姿は味方を鼓舞し、敵を圧倒する。', imgUrl: 'assets/card_champion.jpg' },
    { id: 'assassin', name: 'ギルドの暗殺者', power: 1, skills: [{ id: 'quick' }, { id: 'deadly' }, { id: 'stealth', value: 1 }], rarity: 3, flavor: '黒い服と2つの短剣を持つ若い女暗殺者。一瞬の隙も逃さず、死の影から獲物を屠る。', imgUrl: 'assets/card_assassin.jpg' },
    { id: 'wolf', name: '真夜中の狩人', power: 3, skills: [{ id: 'lone_wolf', value: 3 }, { id: 'legendary' }], rarity: 3, flavor: '月の光を浴びて強靭な力を得る孤高の戦士。群れを嫌い、独りで獲物を追い詰める。' },
    { id: 'vampire', name: '渇きの王', power: 6, skills: [{ id: 'soul_bind', value: 4 }, { id: 'growth', value: -3 }, { id: 'sacrifice', value: 3 }], rarity: 2, flavor: '冷笑を浮かべる夜の支配者。彼の者に狙われた者は、魂の底まで吸い尽くされる。', imgUrl: 'assets/card_vampire.jpg' },
    { id: 'octopus', name: '深海の魔物', power: 4, skill: 'split', skillValue: 2, rarity: 3, flavor: '深海に潜む異形の魔物。全身が筋肉の塊で、足を失ってもすぐに生えてくる。' },
    { id: 'daemon', name: '魔界の尖兵', power: 7, skill: 'sacrifice', skillValue: 3, rarity: 3, flavor: '強固な力と引き換えに契約者の魂を喰らう悪魔の兵士。その渇望は主ですら例外ではない。' },
    // トークンカード
    { id: 'token_soldier', name: '騎士', power: 1, skill: 'none', isToken: true, rarity: 1, flavor: 'セレスティアの号令で召喚された騎士。' },
    { id: 'token_ignis', name: 'イグニス', power: 7, skill: 'none', isToken: true, rarity: 1, flavor: '降臨した竜族の姫。' },
    { id: 'token_satan', name: '魔王の化身', power: 10, skill: 'none', isToken: true, rarity: 1, flavor: '魔王サタンの強大な化身。' },
    { id: 'token_clone', name: '分身', power: 1, skill: 'none', isToken: true, rarity: 1, flavor: '本体から生み出された分身。' },
    { id: 'legs', name: '蛸足', power: 1, skill: 'none', isToken: true, rarity: 1, flavor: '切り離されてもなお蠢き続ける蛸の足。' },
];
