/**
 * Mini Card Battle - Enemy Decks Data
 */
const ENEMY_DECKS = {
    android: [
        'golem', 'golem', 'golem', 'golem',
        'cyberdragoon', 'cyberdragoon',
        'bigai', 'bigai',
        'titan', 'titan',
        'wall', 'wall',
        'diviner', 'diviner',
        'clone', 'clone', 'clone',
        'cleric', 'cleric', 'cleric',
    ],
    dragon: [
        'golem', 'golem', 'golem', 'golem',
        'dragon', 'dragon',
        'babydragon', 'babydragon',
        'berserker', 'berserker',
        'tortoise', 'tortoise',
        'cheetah', 'cheetah',
        'sniper', 'sniper', 'sniper',
        'mage', 'mage', 'mage',
    ],
    knight: [
        'golem', 'golem', 'golem', 'golem',
        'champion', 'champion',
        'commander', 'commander',
        'mage', 'mage',
        'wall', 'wall',
        'cleric', 'cleric',
        'sniper', 'sniper', 'sniper',
        'clone', 'clone', 'clone'
    ],
    cthulhu: [
        'golem', 'golem', 'golem', 'golem',
        'octopus', 'octopus',
        'tortoise', 'tortoise',
        'spider', 'spider',
        'shade', 'shade',
        'clone', 'clone',
        'scorpion', 'scorpion', 'scorpion',
        'diviner', 'diviner', 'diviner',
    ],
    elf: [
        'golem', 'golem', 'golem', 'golem',
        'wolf', 'wolf',
        'spider', 'spider',
        'cheetah', 'cheetah',
        'diviner', 'diviner',
        'cleric', 'cleric',
        'sniper', 'sniper', 'sniper',
        'scorpion', 'scorpion', 'scorpion',
    ],
    cleric: [
        'golem', 'golem', 'golem', 'golem',
        'copy', 'copy',
        'tortoise', 'tortoise',
        'scorpion', 'scorpion',
        'diviner', 'diviner',
        'clone', 'clone',
        'cleric', 'cleric', 'cleric',
        'wall', 'wall', 'wall',
    ],
    satan: [
        'golem', 'golem', 'golem', 'golem',
        'daemon', 'daemon', 'daemon', 'daemon',
        'cyberdragoon',
        'champion',
        'dragon',
        'octopus',
        'wolf',
        'copy',
        'babydragon',
        'bigai',
        'cheetah',
        'mage',
        'shade',
        'berserker',
        'tortoise'
    ]
};
